{
 "title": "Cartelera Min ELECTRICIDAD",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estatus",
    "label": "ESTATUS",
    "query": "SELECT nombre FROM gestion.estatus where id in (3,4,6,8);"
   }
  ]
 },
 "panels": [
  {
   "title": "LISTADO DE CASOS  DE ELECTRICIDAD EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT a.nombre::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\",\r\n    \te.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\",\r\n    \te.telefono_alt::Text \"TELEFONO ALT\",\r\n    \tb.nombre::Text \"ESTADO\",\r\n    \tc.nombre::Text \"MUNICIPIO\",\r\n    \td.nombre::Text \"PARROQ\",\r\n    \ta.direccion::Text \"DIRECCION\",\r\n    \ta.latitud::Text \"LATITUD\",\r\n    \ta.longitud::Text \"LONGUITUD\",\r\n    \ta.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\",\r\n\t  \tg.name::Text \"SUBCATEG\",\r\n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\ti.nombre::Text \"ESTATUS\",\r\n\t\tto_char(a.fecha,'dd-mm-YY') as \"FECHA GENERADO\",\r\n\t\tto_char(a.fecha_registro,'dd-mm-YY') as \"FECHA ESTATUS\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\r\n      where  j.id_resolutorio in (353)\r\n      and j.principal is true\r\n      and $__timeFilter(a.fecha_registro)\r\n      and i.nombre in ($estatus) --h.id_estatus in (3,4,8)"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE-DETALLADO-POR-ESTADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (3) and  e.id_resolutorio in (353) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (3) \nand b.id < 25 and  e.id_resolutorio in (353)\nand e.principal is true\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE ELECTRICIDAD ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (8)"
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (8)\n    and a.id_origen = 1\n    and a.id_estatus in (5) "
      }
     ]
    },
    {
     "title": "CASOS VALIDADO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 13 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n SELECT count(a.id)\n\t  FROM gestion.caso a\n    where a.id_sub_categoria in (8)\n    and a.id_origen = 2\n    and a.id_estatus not in (5) "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (8)\n    and a.id_estatus in (1,2,3,4,6,7,8)"
      }
     ]
    },
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere  b.id_resolutorio in (353) \nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere  b.id_resolutorio in (353) \nand b.principal is true\nand a.id_estatus in (3,4,8) "
      }
     ]
    },
    {
     "title": "ATENDIDOS CON BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere  b.id_resolutorio in (353) \nand b.principal is true\nand a.id_estatus in (6) \nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere  b.id_resolutorio in (353) \nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where  b.id_resolutorio in (353) \n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\n    FROM gestion.caso a\n    inner join gestion.responsable b on b.id_caso =  a.id\n    where  b.id_resolutorio in (353)\n    and b.principal is true\n    and a.id_estatus in (6)\n    and (a.feedback >= 3   or  a.verificado = 'SI');"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\n  select to_char(a.fecha, 'YY-mm-dd') as fechao, to_char(a.fecha, 'dd-mm-YY') as fecham, count(a.fecha) as total\n    \tfrom gestion.caso a\n    \twhere a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL) \n    \t\tand a.id_sub_categoria in (8)\n\t\t    and a.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham, fechao\n        order by fechao"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\nselect \n\tb.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t where a.id_estatus in (1,2,3,4,6,7,8)\n\t and a.id_sub_categoria in (8)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\nselect b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t where a.id_sub_categoria in (8) \n\t and a.id_estatus in (6)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CATEGORÍAS ELECTRICIDAD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE ELECTRICIDAD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select count(a.id) as TOTAL\n\tfrom gestion.caso a\n\t  where  a.id_sub_categoria in (8) \n\t        and a.id_estatus in (1,2,3,4,6,7,8)\n\t\t      "
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (ELECTRICIDAD)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\n      from gestion.caso a\n\t\t\twhere a.id_sub_categoria in (8) and \n      a.id_estatus in (1,2,3,4,6,7,8)\n\t\t\tand a.id_extra_categoria is not null"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (ELECTRICIDAD)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\n      from gestion.caso a\n\t\t\t where a.id_sub_categoria in (3) and \n       a.id_estatus in (1,2,3,4,6,7,8) and a.id_extra_categoria is null\n\t\t\t\t    "
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  ELECTRICIDAD)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "rawSql": "  SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n            inner join gestion.category c on c.id = a.id_sub_categoria\n\t\t\t\t    LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria   \n            where c.id in (8) and  a.id_estatus in (1,2,3,4,6,7,8) \n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE ELECTRICIDAD DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT i.nombre as estatus, count(a.id) as subtotal,\n            (SELECT count(a.id) FROM gestion.caso a\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n    \t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n    \t\t\t\t\tinner JOIN  gestion.estatus i ON i.id = a.id_estatus\n    \t\t\t \t\twhere a.id_estatus in (1,2,3,4,6,7,8) and a.id_sub_categoria in (8))::Text \"Total\"\n      FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n            inner JOIN  gestion.estatus i ON i.id = a.id_estatus\n\t\t\t      where a.id_estatus in (1,2,3,4,6,7,8) and a.id_sub_categoria in (8)\n         group by estatus"
      }
     ]
    },
    {
     "title": "REVISIÓN-UBCH",
     "type": "gauge",
     "description": "Total de casos generados",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 50 },
     "targets": [
      {
       "rawSql": "         SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\twhere a.id_estatus in (3,4,6,7,8) and a.id_sub_categoria in (8)\n\t\t\t\t"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 50 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n        SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\twhere a.id_estatus in (3,4,7,8) and a.id_sub_categoria in (8)\n\t\t\t\t"
      }
     ]
    },
    {
     "title": "ATENDIDOS-UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\n\t\t\t where a.id_estatus in (6) and a.id_sub_categoria in (8)\n\t\t\t\t\t"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 50 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 55 },
     "targets": [
      {
       "rawSql": " SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.denunciante e on e.id = a.id_denunciante\n                inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t          LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n            where a.id_sub_categoria in (8) and a.id_estatus in (1,2,3,4,6,7,8)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS ATENDIDOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 55 },
     "targets": [
      {
       "rawSql": "     SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.denunciante e on e.id = a.id_denunciante\n                inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t        LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n            where a.id_estatus in (6)\n\t\t\t      and a.id_sub_categoria in (8)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\twhere  a.id_estatus in (1,2,3,4,6,7,8) and a.id_sub_categoria in (3)\n            group by estado order by total desc Limit 10;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES-CASOS ATENDIDOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t        where a.id_estatus in (6) and a.id_sub_categoria in (8)\n            group by estado order by total desc Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE ELECTRICIDAD DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \n      --a.codigo::Text \"CODIGO CASO\",\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n            case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\n\t\t\ti.nombre::Text \"ESTATUS\",\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\n            case when w.username is null then 'Analizando' else (w.first_name || ' ' || w.last_name ) end::Text \"RESPONSABLE\",\n\t\t\tw.phone::Text \"TELF. RESP\"\n            FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      inner join lista.ubch z on z.cedula = e.cedula\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\n            where a.id_estatus in (1,2,3,4,6,7,8) and a.id_sub_categoria in (8);"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE ELECTRICIDAD POR ENTIDADES FEDERALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS  EN PROCESO  DE ELECTRICIDAD",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 79 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    where a.id_sub_categoria in (8)\n    and a.id_estatus in (3,4,7,8) "
      }
     ]
    },
    {
     "title": "CASOS  ATENDIDOS  DE ELECTRICIDAD",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 79 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  SELECT count(a.id)\n\t  FROM gestion.caso a\n    where  a.id_sub_categoria in (8)\n    and a.id_estatus in (6) "
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t where a.id_sub_categoria in (8)\n\t and a.id_estatus in (3,4,7,8)\n    group by estado\n    order by total desc;"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n  inner join gestion.estado b on b.id = a.id_estado\n\twhere  a.id_sub_categoria in (8) \n\tand a.id_estatus in (6)\n    group by estado\n    order by total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE ELECTRICIDAD DE UBCH RECIBIDOS-ATENDIDOS (POR ENTIDADES  FEDERALES) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE ELECTRICIDAD DE UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t  \twhere a.id_sub_categoria in (8) and a.id_estatus in (1,2,3,4,6,7,8)\n        group by b.nombre order by TOTAL desc"
      }
     ]
    },
    {
     "title": "TOTAL CASOS DE ELECTRICIDAD ATENDIDOS DE  UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t \twhere a.id_sub_categoria in (8) and a.id_estatus in (6)\n        group by b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE ELECTRICIDAD RECIBIDO-ATENDIDO POR MUNICIPIOS(CAPITALES DE ENTIDADES FEDERALES )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE ELECTRICIDAD POR MUN. CAPITALES",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 122 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\twhere a.id_sub_categoria in (8)\n    and a.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS - ELECTRICIDAD (MUN. CAPITALES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 122 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.estado b on b.id = a.id_estado\n    inner join gestion.municipio c on c.id = a.id_municipio\n\t\twhere a.id_sub_categoria in (8)\n    and a.id_estatus in (6) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t"
      }
     ]
    },
    {
     "title": "CASOS DE ELECTRICIDAD POR MUN. CAPITALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\twhere a.id_sub_categoria in (8) and a.id_estatus in (1,2,3,4,6,7,8)\n      and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n      group by c.nombre, b.nombre\n      order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS  - ELECTRICIDAD (MUN. CAPITALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t where a.id_sub_categoria in (8) and a.id_estatus in (6)\n\t\t\t and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE ELECTRICIDAD RECIBIDO-ATENDIDO DE OTROS MUNICIPIOS  (CIUDADES IMPORTANTES)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS -  ELECTRICIDAD  (CIUDADES IMPORTANTES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.estado b on b.id = a.id_estado\n    inner join gestion.municipio c on c.id = a.id_municipio\n\t\twhere a.id_sub_categoria in (8)\n    and a.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS- ELECTRICIDAD  (CD. IMPORTANTE)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.estado b on b.id = a.id_estado\n    inner join gestion.municipio c on c.id = a.id_municipio\n\t\twhere a.id_sub_categoria in (8) and a.id_estatus in (6) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t"
      }
     ]
    },
    {
     "title": "CASOS - ELECTRICIDAD (CIUDADES IMPORTANTES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 143 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\twhere a.id_sub_categoria in (8) and a.id_estatus in (1,2,3,4,6,7,8)\n      and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n      group by c.nombre, b.nombre\n      order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS - ELECTRICIDAD (CD. IMPORTANTE)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 143 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n     count(a.id) as TOTAL\n     from gestion.caso a\n     inner join gestion.estado b on b.id = a.id_estado\n     inner join gestion.municipio c on c.id = a.id_municipio\n\t\t where a.id_sub_categoria in (8) and a.id_estatus in (6)\n     and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n     group by c.nombre, b.nombre\n     order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE ELECTRICIDAD RECIBIDOS-ATENDIDOS  POR ENTIDADES PARROQUIALES (50 PRIMERAS PARROQUIAS) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n     count(a.id) as TOTAL\n     from gestion.caso a\n     inner join gestion.estado b on b.id = a.id_estado\n     inner join gestion.parroquia c on c.id = a.id_parroquia\n\t \twhere a.id_sub_categoria in (8) and a.id_estatus in (1,2,3,4,6,7,8)\n     group by c.nombre, b.nombre\n     order by TOTAL desc limit 50\n    "
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 11, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n\t\t\twhere a.id_sub_categoria in (8) and a.id_estatus in (6)\n      group by c.nombre, b.nombre\n      order by TOTAL desc limit 50"
      }
     ]
    }
   ]
  }
 ]
}