{
 "title": "INDICE DE SATISFACCIÓN AGUA V3",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ministerio",
    "label": "AGUA",
    "query": "SELECT nombre FROM gestion.resolutorio\n(358, 387, 388, 389,390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 405);"
   },
   {
    "name": "estados",
    "label": "ESTADOS",
    "query": "SELECT  nombre FROM gestion.estado WHERE id < 25 order by id"
   },
   {
    "name": "municipio",
    "label": "MUNICIPIO",
    "query": "SELECT a.nombre  FROM gestion.municipio a inner join gestion.estado b on a.id_estado = b.id where  b.nombre in ($estados) "
   }
  ]
 },
 "panels": [
  { "title": "INDICE DE SATISFACCIÓN AGUA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MUY SATISFECHO%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.historico d on d.id_caso = a.id \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.estado e on e.id = a.id_estado\n                                      \t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n                                      \t\t\twhere $__timeFilter(d.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n                                      \t\t\tand d.active = 1 and d.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(d.fecha_registro)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and  b.principal is true and r.id_tipo_resolutorio in (3,4)\n\t\t\tand d.active = 1 and d.id_estatus in (6) and a.feedback >= 3.5 \t"
    }
   ]
  },
  {
   "title": "SATISFECHO%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.estado e on e.id = a.id_estado\n                                      \t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 3.5 and a.feedback >= 2.5 \t"
    }
   ]
  },
  {
   "title": "INSATISFECHO %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.estado e on e.id = a.id_estado\n                                      \t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and e.nombre in ($estados) and m.nombre in ($municipio) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 2.5 and a.feedback >= 1.5 and a.verificado = 'SI'"
    }
   ]
  },
  {
   "title": "MUY POCO SATISFECHO %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.estado e on e.id = a.id_estado\n                                      \t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 1.5 and a.verificado = 'SI' \t"
    }
   ]
  },
  {
   "title": "CONFIRMADOS-SIN VALORACIÓN %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.estado e on e.id = a.id_estado\n                                      \t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI'\tand a.feedback is null"
    }
   ]
  },
  {
   "title": "REVISADO POR OPERADORES %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.estado e on e.id = a.id_estado\n                                      \t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))"
    }
   ]
  },
  {
   "title": "MUY SATISFECHO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback >= 3.5 \t"
    }
   ]
  },
  {
   "title": "SATISFECHO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 3.5 and a.feedback\t>= 2.5"
    }
   ]
  },
  {
   "title": "INSATISFECHO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand (a.feedback < 2.5 and a.feedback >= 1.5) and a.verificado = 'SI'\n\t\t\t\n\t\t\t"
    }
   ]
  },
  {
   "title": "MUY POCO SATISFECHO ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 1.5 and a.verificado = 'SI'"
    }
   ]
  },
  {
   "title": "CONFIRMADOS-SIN VALORACIÓN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI' and a.feedback is null"
    }
   ]
  },
  {
   "title": "REVISADO POR OPERADORES ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))\n\t\t"
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN POR ESTADOS ($estados)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \n      e.nombre as \"ESTADO\", \n      sum(CASE WHEN a.feedback >= 3.5 THEN 1 ELSE 0 END) AS \"MUY SATISFECHO\",\n      sum(CASE WHEN a.feedback < 3.5 and a.feedback >= 2.5 THEN 1 ELSE 0 END) AS \"SATISFECHO\",\n      sum(CASE WHEN a.feedback < 2.5 and a.feedback >= 1.5 THEN 1 ELSE 0 END) AS \"INSATISFECHO\",\n\t\t\tsum(CASE WHEN a.feedback < 1.5 THEN 1 ELSE 0 END) AS \"MUY POCO SATISFACHO\",\n\t\t  CONCAT(case when round(avg(a.feedback)) = 1 then 'MUY POCO SATISFACHO'\n                  when round(avg(a.feedback)) = 2 then 'INSATISFECHO'\n                  when round(avg(a.feedback)) = 3 then 'SATISFECHO'\n                  when round(avg(a.feedback)) > 3 then 'MUY SATISFECHO'\n                  when round(avg(a.feedback)) is null then 'SIN VALORACIÓN'\n                  end) as \"PROMEDIO\",\n      sum(CASE WHEN (a.feedback is null and a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"SIN VALORACIÓN Y CONFIRMADO\",\n      count(*) AS \"TOTAL ATENDIDO\"\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados)\n\t\t\tand r.id_tipo_resolutorio in (3,4)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) and ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n\t\t\tgroup by e.nombre ORDER BY \"MUY SATISFECHO\" desc\n"
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN POR MUNICIPIO ($municipio)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n      m.nombre || ' (' ||  e.nombre || ')'  as \"MUNICIPIO\", \n      sum(CASE WHEN a.feedback >= 3.5 THEN 1 ELSE 0 END) AS \"MUY SATISFECHO\",\n      sum(CASE WHEN a.feedback < 3.5 and a.feedback >= 2.5 THEN 1 ELSE 0 END) AS \"SATISFECHO\",\n      sum(CASE WHEN a.feedback < 2.5 and a.feedback >= 1.5 THEN 1 ELSE 0 END) AS \"INSATISFECHO\",\n\t\t\tsum(CASE WHEN a.feedback < 1.5 THEN 1 ELSE 0 END) AS \"MUY POCO SATISFACHO\",\n\t\t  CONCAT(case when round(avg(a.feedback)) = 1 then 'MUY POCO SATISFACHO'\n                  when round(avg(a.feedback)) = 2 then 'INSATISFECHO'\n                  when round(avg(a.feedback)) = 3 then 'SATISFECHO'\n                  when round(avg(a.feedback)) > 3 then 'MUY SATISFECHO'\n                  when round(avg(a.feedback)) is null then 'SIN VALORACIÓN'\n                  end) as \"PROMEDIO\",\n      sum(CASE WHEN (a.feedback is null and a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"SIN VALORACIÓN Y CONFIRMADO\",\n      count(*) AS \"TOTAL ATENDIDO\"\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\twhere $__timeFilter(a.fecha_registro)\n\t\t\tand r.nombre in ($ministerio) and e.nombre in ($estados) and m.nombre in ($municipio)\n\t\t\tand r.id_tipo_resolutorio in (3,4)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) and ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n\t\t\tgroup by m.nombre, e.nombre ORDER BY \"MUY SATISFECHO\" desc\n"
    }
   ]
  }
 ]
}