{
 "title": "CATEGORIA ELECTRICIDAD",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://images.carnet.org.ve/imagenes/CINTILLOELECTRICIDAD.jpg\" alt=\"texto_alternativo\" width=\"100%\" height=\"170\">\n"
   }
  },
  {
   "title": "EFECTIVIDAD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id \n                                            inner join gestion.responsable b on b.id_caso =  d.id\n                                            where b.id_resolutorio in (353) \n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (353) \nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 5 },
   "options": {
    "content": "<CENTER>\n <h2>FALLAS DEL\nALUMBRADO PÚBLICO</h2>\n</CENTER>"
   }
  },
  {
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"ESTADO\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and e.id_resolutorio in (353) THEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"EFECTIVIDAD\"\r\nfrom gestion.caso a\r\ninner join gestion.estado b on b.id = a.id_estado\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\nwhere  a.id_estatus in (1,2,3,4,6,7,8)\r\nand e.id_resolutorio in (353)\r\nand e.principal is true\r\ngroup by b.nombre\r\norder by \"RECIBIDO\" desc"
    }
   ]
  },
  {
   "title": "RECIBIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.category b on b.id = a.id_sub_categoria\r\ninner join gestion.category c on c.id = a.id_extra_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 29\r\nand e.id_resolutorio in (353) \r\nand a.id_estatus in (1,2,3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ATENDIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.category b on b.id = a.id_sub_categoria\r\ninner join gestion.category c on c.id = a.id_extra_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id \r\nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 29\r\nand e.id_resolutorio in (353)\r\nand a.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 29\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (353)\n\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.category b on b.id = a.id_sub_categoria\ninner join gestion.category c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 29\nand e.id_resolutorio in (354)\nand a.id_estatus in (6)"
    }
   ]
  },
  {
   "title": "CASOS RECIBIDO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id\n\twhere b.id_resolutorio in (353) \n  and b.principal is true\tand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 9 },
   "options": {
    "content": "<CENTER>\n <h2>FALLAS DEL\nSERVICIO ELÉCTRICO</h2>\n</CENTER>"
   }
  },
  {
   "title": "RECIBIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id \r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 28\r\n\t\t\tand e.id_resolutorio in (353) \r\n\t\t\tand a.id_estatus in (1,2,3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ATENDIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 28\r\n\t\t\tand e.id_resolutorio in (353)\r\n\t\t\tand a.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 28\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (353)\n\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.category b on b.id = a.id_sub_categoria\ninner join gestion.category c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id \nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 28\nand e.id_resolutorio in (353)\nand a.id_estatus in (6)"
    }
   ]
  },
  {
   "title": "CASOS ATENDIDO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (353) \nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 13 },
   "options": {
    "content": "<CENTER>\n <h2>SOLICITUD DE\nTRANSFORMADORES</h2>\n</CENTER>"
   }
  },
  {
   "title": "RECIBIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 31\r\n\t\t\tand e.id_resolutorio in (353) \r\n\t\t\tand a.id_estatus in (1,2,3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ATENDIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 31\r\n\t\t\tand e.id_resolutorio in (353)\r\n\t\t\tand a.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 31\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (353)\n\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.category b on b.id = a.id_sub_categoria\ninner join gestion.category c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id \nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 31\nand e.id_resolutorio in (353)\nand a.id_estatus in (6)"
    }
   ]
  },
  {
   "title": "CASO POR ATENDER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n((SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.responsable b on b.id_caso =  a.id\r\n\twhere b.id_resolutorio in (353) \r\n  and b.principal is true\tand a.id_estatus in (3,4,6,7,8))\r\n  -\r\n  (SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso = a.id\r\nwhere b.id_resolutorio in (353) \r\nand b.principal is true\r\nand a.id_estatus in (6) \r\nand (a.feedback >= 3   or  a.verificado = 'SI'))) as total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 17 },
   "options": {
    "content": "<CENTER>\n <h2>FALLAS EN\n LA PICA Y PODA\n</h2>\n</CENTER>"
   }
  },
  {
   "title": "RECIBIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 27\r\n\t\t\tand e.id_resolutorio in (353) \r\n\t\t\tand a.id_estatus in (1,2,3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ATENDIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id \r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 27\r\n\t\t\tand e.id_resolutorio in (353)\r\n\t\t\tand a.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 27\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (353)\n\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.category b on b.id = a.id_sub_categoria\ninner join gestion.category c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 27\nand e.id_resolutorio in (353)\nand a.id_estatus in (6)"
    }
   ]
  },
  {
   "title": "NIVEL DE SATISFACION",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\twhere  b.id_resolutorio in (353)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 21 },
   "options": {
    "content": "<CENTER>\n <h2>PROYECTOS DE\nELECTRIFICACIÓN</h2>\n</CENTER>"
   }
  },
  {
   "title": "RECIBIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id \r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 30\r\n\t\t\tand e.id_resolutorio in (353) \r\n\t\t\tand a.id_estatus in (1,2,3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ATENDIDO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\r\n\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\r\n\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 30\r\n\t\t\tand e.id_resolutorio in (353)\r\n\t\t\tand a.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\twhere a.id_sub_categoria = 8 and a.id_extra_categoria = 30\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (353)\n\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.category b on b.id = a.id_sub_categoria\ninner join gestion.category c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\nwhere a.id_sub_categoria = 8 and a.id_extra_categoria = 30\nand e.id_resolutorio in (353)\nand a.id_estatus in (6)"
    }
   ]
  }
 ]
}