{
 "title": "GOBERNACIONES Y ALCALDIAS DETALLADO",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "gobernaciones",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio where id_tipo_resolutorio = 1 ORDER BY nombre "
   },
   {
    "name": "alcaldia",
    "label": "ALCALDIA",
    "query": "SELECT a.nombre FROM gestion.resolutorio a\ninner join gestion.resolutorio aa ON aa.id = a.id_estado\nwhere a.id_tipo_resolutorio = 2 AND aa.nombre in ($gobernaciones) ;"
   }
  ]
 },
 "panels": [
  {
   "title": "GOBERNACION ($gobernaciones)",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"GOBERNACION\",\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3,4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = z.id_estado\nwhere  a.id_estatus in (1,2,3,4,6,8)\nand z.id_tipo_resolutorio in (1)  and b.id < 25\nand e.principal is true and z.nombre in ($gobernaciones)\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "ALCALDIAS ($gobernaciones)",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \n    m.nombre::Text \"ALCALDIAS\",\n\t\tsum(CASE WHEN a.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\n\t\tsum(CASE WHEN a.id_estatus in (3,4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\n\t\tsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \n\t\ttrunc(sum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\n\t\tfrom gestion.caso a\n\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\n\t\tinner join gestion.municipio m on m.id = z.id_municipio\n\t\twhere  a.id_estatus in (1,2,3,4,6,7,8)\n\t\tand z.id_tipo_resolutorio in (2)\n\t\tand z.nombre in ($alcaldia) and zz.nombre in ($gobernaciones)\n\t\tand e.principal is true\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" DESC"
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS EN PROCESO",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": " SELECT a.nombre::Text \"CODIGO\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \tk.nombre::Text \"RESPONSABLE\",\n    \tto_char(a.fecha_registro,'dd-mm-YY') as \"FECHA ULTIMO ESTATUS\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id and j.principal is true\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT join  gestion.resolutorio zz on zz.id =  k.id_estado \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n      \t\twhere k.nombre in ($gobernaciones, $alcaldia) and zz.nombre in ($gobernaciones)\n      \t\tand j.principal is true and a.id_estatus in (3,4,8) "
    }
   ]
  }
 ]
}