{
 "title": "GOBERNACIONES Y ALCALDIAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 25, "w": 1, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select id as \"RANKING\"\r\nfrom gestion.estado\r\nwhere  id < 25\r\norder by id asc"
    }
   ]
  },
  {
   "title": "EFICIENCIA REGIONAL",
   "type": "table",
   "gridPos": { "h": 25, "w": 7, "x": 1, "y": 0 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"REGION\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1,2) AND (a.feedback >= 2 or a.verificado = 'SI')\r\n\t\t  THEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\ninner join gestion.estado b on b.id = z.id_estado\r\nwhere  a.id_estatus in (1,2,3,4,6,7,8)\r\nand z.id_tipo_resolutorio in (1,2) and b.id < 25 \r\nand e.principal is true\r\ngroup by b.nombre\r\nHAVING count(*) >= 2\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "  ",
   "type": "table",
   "gridPos": { "h": 25, "w": 1, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "select id as \"RANKING\"\r\nfrom gestion.estado\r\nwhere  id < 25\r\norder by id asc"
    }
   ]
  },
  {
   "title": "GOBERNACION",
   "type": "table",
   "gridPos": { "h": 25, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"REGION\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1) AND (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\ninner join gestion.estado b on b.id = z.id_estado\r\nwhere  a.id_estatus in (1,2,3,4,6,7,8)\r\nand z.id_tipo_resolutorio in (1)  and b.id < 25\r\nand e.principal is true\r\ngroup by b.nombre\r\nHAVING count(*) > 1\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "  ",
   "type": "table",
   "gridPos": { "h": 25, "w": 1, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select id as \"RANKING\"\r\nfrom gestion.estado\r\nwhere  id < 25\r\norder by id asc"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "table",
   "gridPos": { "h": 25, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"REGION\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (2) \r\nAND (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\ninner join gestion.estado b on b.id = z.id_estado\r\nwhere  a.id_estatus in (1,2,3,4,6,7,8)\r\nand z.id_tipo_resolutorio in (2) and b.id < 25 \r\nand e.principal is true\r\ngroup by b.nombre\r\nHAVING count(*) > 1\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  }
 ]
}