{
 "title": "Cartelera Presidencial  CASOS POR ESTADO, MUNICIPIO Y PARROQUIA",
 "time": { "from": "2022-11-02T13:45:10.016Z", "to": "2022-11-02T13:55:10.016Z" },
 "templating": {
  "list": [
   {
    "name": "estado",
    "label": "Estado",
    "query": "SELECT nombre FROM gestion.estado where id < 26 order by id"
   },
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "SELECT a.nombre  FROM gestion.municipio a inner join gestion.estado b on a.id_estado = b.id where  b.nombre in ($estado) "
   },
   {
    "name": "parroquia",
    "label": "Parroquia",
    "query": "SELECT a.nombre FROM gestion.parroquia a \n\tinner join gestion.municipio b on a.id_municipio = b.id \n\tinner join gestion.estado c on c.id = b.id_estado\n\twhere  c.nombre in ($estado)  and b.nombre in ($municipio)"
   }
  ]
 },
 "panels": [
  {
   "title": "REPORTE GENERAL 1X10 DEL BUEN GOBIERNO ($estado)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT profile_pic\n\tFROM public.user_detail \n\twhere user_id = 3"
    }
   ]
  },
  {
   "title": "RECIBIDOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.estado b on b.id = a.id_estado\n\tinner join gestion.municipio c on c.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n  where b.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)"
    }
   ]
  },
  {
   "title": "SISTEMA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    --inner join gestion.historico d on d.id_caso = a.id  \n    inner join gestion.estado b on b.id = a.id_estado\n\t  inner join gestion.municipio c on c.id = a.id_municipio\n\t  inner join gestion.parroquia e on e.id = a.id_parroquia\n  where\n    b.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)\n    and a.id_estatus in (1,2,3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "DEVUELTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n  --inner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.estado b on b.id = a.id_estado\n\tinner join gestion.municipio c on c.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n  where\n\tb.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand a.id_estatus in (5) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 1, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "ATENDIDOS-MINISTERIOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (3,4)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and a.id_estatus in (6) and (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MINISTERIOS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (3,4)\n\t\t\t\t\t\t\t\t\t\t   \t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t  and a.id_sub_categoria in (1,2,3,4,5,6,7,8) and b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\t  and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (3,4)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 1, "x": 23, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "REVISIÓN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\t  FROM gestion.caso a\n    --inner join gestion.historico d on d.id_caso = a.id  \n    inner join gestion.estado b on b.id = a.id_estado\n  \tinner join gestion.municipio c on c.id = a.id_municipio\n  \tinner join gestion.parroquia e on e.id = a.id_parroquia\n    where b.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)\n    and a.id_estatus in (1,2) "
    }
   ]
  },
  {
   "title": "MINISTERIOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (3,4)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and a.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (1,2)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and a.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "ATENDIDOS-GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (1,2)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and a.id_estatus in (6) and (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOB-ALCALDIAS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1,2)\n\t\t\t\t\t\t\t\t\t\t   \tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (1,2)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "VENEZUELA",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 11, "x": 3, "y": 7 },
   "targets": [
    {
     "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\t\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\t\n\t\t\twhere\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\t--and b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,453,553,561,597,563,566,354,503,599)\n\t\t\tand b.principal is true and a.id_estatus in (6) and (a.feedback >= 3 or a.verificado = 'SI') --and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\twhere f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\tand a.id_estatus in (6) "
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\twhere c.id_padre in (478) \n\t--where a.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true\tand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere c.id in (357)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "MIN-EDUCA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id in (361)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "MIN-UNIVERS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (369)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (353)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (371,374,404)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (406)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (359)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "GOB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (1)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\nand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (2)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\nand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n                                            inner join gestion.resolutorio c on c.id = b.id_resolutorio\t\t\n                      \t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                      \t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n                      \t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\t\t\t\t\t\t\t\t\t\t\n                                            where c.id_padre in (478) \n\t\t\t\t\t\t\t\t\t\t\t                      and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id\n  inner join gestion.resolutorio c on c.id = b.id_resolutorio  \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_padre in (478)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\tand a.id_estatus in (6) \n\tand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc((count(a.id)::decimal * 100) / ( SELECT count(a.id)\n                                              FROM gestion.caso a\n                                              inner join gestion.responsable b on b.id_caso =  a.id\n                                              inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                              inner join gestion.estado f on f.id = a.id_estado\n                                              inner join gestion.municipio g on g.id = a.id_municipio\n                                              inner join gestion.parroquia e on e.id = a.id_parroquia\n                                              where b.id_resolutorio in (357)\n                                              and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                              and b.principal is true\n                                              and a.id_estatus in (3,4,6,7,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (357)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-EDUCA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / ( SELECT count(a.id) \n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n                                            inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                            inner join gestion.estado f on f.id = a.id_estado\n                                            inner join gestion.municipio g on g.id = a.id_municipio\n                                            inner join gestion.parroquia e on e.id = a.id_parroquia\n                                            where b.id_resolutorio in (553)\n                                            and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true\n                                            and d.active = 1\n                                            and d.id_estatus in (3,4,6,7,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (553)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-UNIVERS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (369)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (369)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (354)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (354)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (371,374,404)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (371,374,404)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (406)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (406)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (359)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (359)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOB",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                        inner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                        inner join gestion.municipio g on g.id = a.id_municipio\n                        inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1)\n\t\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.responsable b on b.id_caso =  a.id\n    inner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\twhere c.id_tipo_resolutorio in (1)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                        inner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                        inner join gestion.municipio g on g.id = a.id_municipio\n                        inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (2)\n\t\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n    inner join gestion.responsable b on b.id_caso =  a.id\n    inner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\twhere c.id_tipo_resolutorio in (2)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_padre in (478) \n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\tand a.id_estatus in (6) \n\tand (a.feedback >= 3  or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (357)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-EDUCA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (361)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-UNIVERS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (369)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (353)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (371,374,404)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (406)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (359)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere c.id_tipo_resolutorio in (1)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere c.id_tipo_resolutorio in (2)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  { "title": "REPORTE GENERAL DE MINISTERIOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT\n  \n" }
   ]
  },
  {
   "title": "MINAGUAS-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\t\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere c.id_padre in (478)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "SALUD-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (357)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "EDUCACIÓN -CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (361)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "E-UNIVERSITARIA-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (369)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ELECTRICIDAD-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (353)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "TELECOMUNICACIONES-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (371,374,404)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "GAS COMUNAL-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (406)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "GAS-PDVSA-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (359)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT \n \n" }
   ]
  },
  {
   "title": "MINAGUA %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso = a.id\n                                            inner join gestion.resolutorio c on c.id = b.id_resolutorio\n                                            inner join gestion.estado f on f.id = a.id_estado\n                                            inner join gestion.municipio g on g.id = a.id_municipio\n                                            inner join gestion.parroquia e on e.id = a.id_parroquia\t\n                                            where c.id_padre in (478)\n                                            and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere c.id_padre in (478)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "SALUD %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc((count(a.id)::decimal * 100) / ( SELECT count(a.id)\n                                              FROM gestion.caso a\n                                              inner join gestion.responsable b on b.id_caso =  a.id\n                                              inner join gestion.estado f on f.id = a.id_estado\n                                              inner join gestion.municipio g on g.id = a.id_municipio\n                                              inner join gestion.parroquia e on e.id = a.id_parroquia\n                                              where b.id_resolutorio in (357)\n                                              and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                              and b.principal is true\n                                              and a.id_estatus in (3,4,6,7,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (357)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "EDUCACIÓN %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / ( SELECT count(a.id) \n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n                                            inner join gestion.estado f on f.id = a.id_estado\n                                            inner join gestion.municipio g on g.id = a.id_municipio\n                                            inner join gestion.parroquia e on e.id = a.id_parroquia\n                                            where b.id_resolutorio in (361)\n                                            and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (361)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "UNIVERSITARIA %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (369)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (369)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ELECTRICIDAD %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (353)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (353)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOMUNICACIONES %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (371,374,404)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (371,374,404)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GAS %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (406)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (406)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GAS %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\t\n                                           where b.id_resolutorio in (359)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (359)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere c.id_padre in (478)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (357)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (361)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (369)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3 or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (353)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (371,374,404)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (406)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3  or a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (359)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n      inner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  c.id_padre in (478)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand a.feedback is not null"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (357)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (361)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (369)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\twhere  b.id_resolutorio in (353)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (371,374,404)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (406)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (359)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n      inner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  c.id_padre in (478)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (357)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (361)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (369)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (353)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\twhere  b.id_resolutorio in (371,374,404)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (406)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (359)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback is not null\t"
    }
   ]
  }
 ]
}