{
 "title": "Casos  Regionales",
 "time": { "from": "2022-07-21T23:26:07.561Z", "to": "2022-07-22T11:26:07.561Z" },
 "templating": {
  "list": [
   {
    "name": "subcateg",
    "label": "SUB CATEG",
    "query": "SELECT name FROM gestion.category WHERE id in (8,9,10,11,12,13)"
   },
   {
    "name": "resolutorg",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio a where a.id_tipo_resolutorio = 1 order by nombre"
   },
   {
    "name": "resolutorea",
    "label": "ALCALDIAS",
    "query": "SELECT a.nombre FROM gestion.resolutorio a inner join gestion.resolutorio b on a.id_estado = b.id_estado where a.id_tipo_resolutorio = 2 and b.nombre in ($resolutorg) "
   }
  ]
 },
 "panels": [
  {
   "title": "CASOS  REGIONALES",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT (\r\n(SELECT count(a.nombre)\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n        where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t  and k.nombre in ($resolutorg) \r\n\t\t\t  and a.id not in (SELECT a.id \r\n        \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n        \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg)))\r\n+\r\n (SELECT count(a.nombre)\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n      where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\tand k.nombre in ($resolutorea) \r\n\t\t\tand a.id not in (SELECT a.id \r\n      \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n      \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n      \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n                  \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n      \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n      \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea))\r\n      and b.id in (SELECT id_estado FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n+\r\n(SELECT count(distinct a.nombre)\r\n\t   \tFROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n            inner JOIN gestion.responsable j ON j.id_caso = a.id \r\n            inner JOIN gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n        where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t  and k.nombre in ($resolutorg,$resolutorea)\r\n\t\t\t  and a.id not in (SELECT a.id\r\n        \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n        \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg,$resolutorea))\r\n\t\t\t and a.id not in (SELECT a.id\r\n\t\t\t\t\t\t\t\tFROM gestion.caso a\r\n\t\t\t\t\t\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\r\n\t\t\t\t\t\t\t\t\tinner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\t\t\t\t\t\t\tinner join gestion.parroquia d on d.id = a.id_parroquia\r\n\t\t\t\t\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\t\t\t\t\tinner join gestion.category f on f.id = a.id_categoria\r\n\t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\t\tinner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  public.user w ON w.id = j.id_user\r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n\t\t\t\t\t\t\t  where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t\t\tand k.nombre in ($resolutorea) \r\n\t\t\t\t\t\t\t\t\tand a.id not in (SELECT a.id \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea)))\r\n\t\t\t and a.id not in (SELECT a.id FROM gestion.caso a\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.municipio c on c.id = a.id_municipio\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.parroquia d on d.id = a.id_parroquia\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.category f on f.id = a.id_categoria\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n          \t\t\t\t\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  public.user w ON w.id = j.id_user\r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n          \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n          \t\t\t\t\t\t\t\t\t  and k.nombre in ($resolutorg) \r\n          \t\t\t\t\t\t\t\t\t  and a.id not in (SELECT a.id \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg))))\r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t) as total;"
    }
   ]
  },
  {
   "title": "GOBERNACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "       SELECT count(*)\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n        where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\n\t\t\t  and k.nombre in ($resolutorg) \n\t\t\t  and a.id not in (SELECT a.id \n        \t\t\t\t\t\t\t \tFROM gestion.caso a \n        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\n        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\n                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n        \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\n        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg));"
    }
   ]
  },
  {
   "title": " ATENDIDOS GOB.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "       SELECT count(*)\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n        where a.id_estatus in (6) and g.name in ($subcateg)\n\t\t\t  and k.nombre in ($resolutorg) \n\t\t\t  and a.id not in (SELECT a.id \n        \t\t\t\t\t\t\t \tFROM gestion.caso a \n        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\n        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \n                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n        \t\t\t\t\t\t\t\twhere a.id_estatus in (6) and g.name in ($subcateg)\n        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg));"
    }
   ]
  },
  {
   "title": "GOBERNACIÓN %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / ( SELECT count(*)\r\n\t\t\t\t\t\t\t\t\t        FROM gestion.caso a\r\n\t\t\t\t\t\t\t\t\t            inner join gestion.estado b on b.id = a.id_estado\r\n\t\t\t\t\t\t\t\t\t            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\t\t\t\t\t\t\t            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n\t\t\t\t\t\t\t\t\t            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\t\t\t\t\t            inner join gestion.category f on f.id = a.id_categoria\r\n\t\t\t\t\t\t\t\t\t            inner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\t\t            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n\t\t\t\t\t\t\t\t\t            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n\t\t\t\t\t\t\t\t\t            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\t\t            LEFT JOIN  public.user w ON w.id = j.id_user\r\n\t\t\t\t\t\t\t\t\t            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n\t\t\t\t\t\t\t\t\t        where a.id_estatus in (3,4,6,7,8) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t\t\t\t\t\tand k.nombre in ($resolutorg) \r\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id not in (SELECT a.id \r\n\t\t\t\t        \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n\t\t\t\t        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n\t\t\t\t                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t        \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,6,7,8) and g.name in ($subcateg)\r\n\t\t\t\t        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg)))::decimal,2) as porcentaje\r\n\t      \r\n\r\n\r\n\t    FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n        where a.id_estatus in (6) and g.name in ($subcateg)\r\n\t\t\t  and k.nombre in ($resolutorg) \r\n\t\t\t  and a.id not in (SELECT a.id \r\n\t\t\t\t\t\t\t \tFROM gestion.caso a \r\n\t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n            \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\twhere a.id_estatus in (6) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg));"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "       SELECT COUNT(*)\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n      where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\n\t\t\tand k.nombre in ($resolutorea) \n\t\t\tand a.id not in (SELECT a.id \n      \t\t\t\t\t\t\t \tFROM gestion.caso a \n      \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\n      \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \n                  \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n      \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\n      \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea))\n      and b.id in (SELECT id_estado FROM gestion.resolutorio where nombre in ($resolutorg));\n      "
    }
   ]
  },
  {
   "title": "ATENDIDOS  ALCALDIAS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "       SELECT COUNT(*)\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n      where a.id_estatus in (6) and g.name in ($subcateg)\n\t\t\tand k.nombre in ($resolutorea) \n\t\t\tand a.id not in (SELECT a.id \n      \t\t\t\t\t\t\t \tFROM gestion.caso a \n      \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\n      \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \n                  \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n      \t\t\t\t\t\t\t\twhere a.id_estatus in (6) and g.name in ($subcateg)\n      \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea))\n      and b.id in (SELECT id_estado FROM gestion.resolutorio where nombre in ($resolutorg));\n      "
    }
   ]
  },
  {
   "title": "ALCALDÍA  %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT COUNT(*)\r\n\t\t\t\t\t\t\t\t\t\t        FROM gestion.caso a\r\n\t\t\t\t\t\t\t\t\t\t            inner join gestion.estado b on b.id = a.id_estado\r\n\t\t\t\t\t\t\t\t\t\t            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\t\t\t\t\t\t\t\t            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n\t\t\t\t\t\t\t\t\t\t            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\t\t\t\t\t\t            inner join gestion.category f on f.id = a.id_categoria\r\n\t\t\t\t\t\t\t\t\t\t            inner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\t\t\t            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n\t\t\t\t\t\t\t\t\t\t            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n\t\t\t\t\t\t\t\t\t\t            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\t\t\t            LEFT JOIN  public.user w ON w.id = j.id_user\r\n\t\t\t\t\t\t\t\t\t\t            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n\t\t\t\t\t\t\t\t\t\t      where a.id_estatus in (3,4,6,7,8) and g.name in ($subcateg) and k.nombre in ($resolutorea) \r\n\t\t\t\t\t\t\t\t\t\t\t  and a.id not in (SELECT a.id \r\n\t\t\t\t\t\t\t      \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n\t\t\t\t\t\t\t      \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t      \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n\t\t\t\t\t\t\t                  \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t      \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,6,7,8) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t      \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea))\r\n\t\t\t\t\t\t\t\t\t\t      and b.id in (SELECT id_estado FROM gestion.resolutorio where nombre in ($resolutorg))\r\n\t\t\t\t\t\t\t\t\t\t      )::decimal,2) as porcentaje\r\n\t    FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n      \twhere a.id_estatus in (6) and g.name in ($subcateg)\r\n\t\t\tand k.nombre in ($resolutorea) \r\n\t\t\tand a.id not in (SELECT a.id \r\n      \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n      \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n      \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n                  \t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n      \t\t\t\t\t\t\t\twhere a.id_estatus in (6) and g.name in ($subcateg) and k.nombre not in ($resolutorea))\r\n      \t\tand b.id in (SELECT id_estado FROM gestion.resolutorio where nombre in ($resolutorg));"
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS CON RESPONSABILIDAD COMPARTIDA  ($resolutorg )",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "\t(SELECT a.nombre::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\ti.nombre::Text \"ESTATUS\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n        where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t  and k.nombre in ($resolutorg) \r\n\t\t\t  and a.id not in (SELECT a.id \r\n        \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n        \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg)))\r\nunion\r\n (SELECT a.nombre::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\t  i.nombre::Text \"ESTATUS\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n      where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\tand k.nombre in ($resolutorea) \r\n\t\t\tand a.id not in (SELECT a.id \r\n      \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n      \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n      \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n                  \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n      \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n      \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea))\r\n      and b.id in (SELECT id_estado FROM gestion.resolutorio where nombre in ($resolutorg)))\r\nunion\r\n\t(SELECT  DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\",\r\n\t    --a.codigo::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\", case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\ti.nombre::Text \"ESTATUS\"\r\n\t   \tFROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n        where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t  and k.nombre in ($resolutorg,$resolutorea)\r\n\t\t\t  and a.id not in (SELECT a.id\r\n        \t\t\t\t\t\t\t \tFROM gestion.caso a \r\n        \t\t\t\t\t\t \t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n        \t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n                    \t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n        \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n        \t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg,$resolutorea))\r\n\t\t\t and a.id not in (SELECT a.id\r\n\t\t\t\t\t\t\t\tFROM gestion.caso a\r\n\t\t\t\t\t\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\r\n\t\t\t\t\t\t\t\t\tinner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\t\t\t\t\t\t\tinner join gestion.parroquia d on d.id = a.id_parroquia\r\n\t\t\t\t\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\t\t\t\t\tinner join gestion.category f on f.id = a.id_categoria\r\n\t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  public.user w ON w.id = j.id_user\r\n\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n\t\t\t\t\t\t\t  where a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t\t\tand k.nombre in ($resolutorea) \r\n\t\t\t\t\t\t\t\t\tand a.id not in (SELECT a.id \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tand k.nombre not in ($resolutorea)))\r\n\t\t\t and a.id not in (SELECT a.id FROM gestion.caso a\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.municipio c on c.id = a.id_municipio\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.parroquia d on d.id = a.id_parroquia\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.category f on f.id = a.id_categoria\r\n          \t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n          \t\t\t\t\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id\r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  public.user w ON w.id = j.id_user\r\n          \t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n          \t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n          \t\t\t\t\t\t\t\t\t  and k.nombre in ($resolutorg) \r\n          \t\t\t\t\t\t\t\t\t  and a.id not in (SELECT a.id \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.category g on g.id = a.id_sub_categoria\r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,7,8) and g.name in ($subcateg)\r\n          \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tand k.nombre not in ($resolutorg))));"
    }
   ]
  }
 ]
}