{
 "title": "JEFE CALLE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CASOS EN SISTEMA-JEFE DE CALLE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "         SELECT i.nombre as estatus, count(a.id) as subtotal,\n            (SELECT count(a.id) FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            --inner join lista.base_politica z on z.cedula = e.cedula  --Descomentar cuando la agreguen\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id\n            where a.id_estatus in (1,2,3,4,6,7,8))::Text \"Total\"\n            FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            --inner join lista.base_politica z on z.cedula = e.cedula     --Descomentar cuando la agreguen\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id\n         where a.id_estatus in (1,2,3,4,6,7,8) \n         group by estatus\n         order by subtotal desc"
    }
   ]
  },
  {
   "title": "REVISIÓN-UBCH",
   "type": "gauge",
   "description": "Total de casos generados",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": " SELECT count(a.id)\n            FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            --inner join lista.base_politica z on z.cedula = e.cedula --Descomentar cuando la agreguen\n            where a.id_estatus in (1,2) "
    }
   ]
  },
  {
   "title": "PROCESO-UBCH",
   "type": "gauge",
   "description": "Total de casos Asignados",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": " SELECT count(a.id)\n            FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            --inner join lista.base_politica z on z.cedula = e.cedula --Descomentar cuando la agreguen\n            where a.id_estatus in (3,4,7,8) "
    }
   ]
  },
  {
   "title": "ATENDIDO-UBCH",
   "type": "gauge",
   "description": "Total de casos cerrados",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "            SELECT count(a.id)\n            FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            --inner join lista.base_politica z on z.cedula = e.cedula --Descomentar cuando la agreguen\n            where a.id_estatus in (6) "
    }
   ]
  },
  {
   "title": "HORA VENEZUELA",
   "type": "grafana-clock-panel",
   "description": "FECHA HORA",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
    }
   ]
  },
  {
   "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
   "type": "barchart",
   "description": "Total de Casos por Estado",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "        select b.nombre as estado, count(a.id) as total\n        from gestion.caso a\n\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\n\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t--inner join lista.base_politica z on z.cedula = e.cedula --Descomentar cuando la agreguen\n\t\t\t\twhere  a.id_estatus in (1,2,3,4,6,7,8)\n\t\t\t\tgroup by estado\n\t\t\t\torder by total desc\n\t\t\t\tLimit 10;"
    }
   ]
  },
  {
   "title": "UBCH-ENTIDADES FEDERALES-CASOS ATENDIDO  ",
   "type": "barchart",
   "description": "Total de Casos por Estado",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "        select b.nombre as estado, count(a.id) as total\n               from gestion.caso a\n\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\n\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t--inner join lista.base_politica z on z.cedula = e.cedula  --Descomentar cuando la agreguen\n\t\t\t\twhere  a.id_estatus in (6)\n\t\t\t\tgroup by estado\n\t\t\t\torder by total desc\n\t\t\t\tLimit 10;\n            \n            \n            "
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "     SELECT a.nombre::Text \"CODIGO CASO\", \n     \t\t    e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n\t\t\t      e.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \n\t\t\t      f.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n      case when n.name is null then 'SIN CATEG 5TO NIVEL' else n.name end::Text \"CATEG ADI\",\n\t    --case when nv.nombre is null then 'SIN CATEG DE 5TO NIVEL' else nv.nombre end::Text \"CATEG 5TO NIVEL\",\n\t\t\t      i.nombre::Text \"ESTATUS\",\n\t\t\t      to_char(a.fecha, 'dd-mm-YY')::Text \"FECHA CREACION\",\n\t\t\t      to_char(a.fecha_registro, 'dd-mm-YY')::Text \"FECHA INCIDENCIA\",\n      case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\n      case when w.username is null then 'Analizando' else (w.first_name || ' ' || w.last_name ) end::Text \"RESPONSABLE\",\n\t\t\t      w.phone::Text \"TELF. RESP\"\n      FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      --inner join lista.base_politica z on z.cedula = e.cedula --Descomentar cuando la agreguen\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id and j.principal = true\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\n\t\t\t      --LEFT JOIN  gestion.categoria_n_v nv ON nv.id = a.id_categoria_n_v --Descomentar cuando lo agreguen\n            where a.id_estatus in (1,2,3,4,6,7,8)"
    }
   ]
  }
 ]
}