{
 "title": "REVISION DE DATA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOTAL DE CASOS POR ESTATUS",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select e.nombre::Text \"ESTATUS\", count(a.id) as \"TOTAL\"\n\tfrom gestion.caso a\n\tinner join gestion.estatus e on e.id = a.id_estatus\n\twhere a.id_estatus in (1,2,3,4,5,6,7,8)\n\tgroup by e.id, e.nombre\n\torder by e.id asc"
    }
   ]
  },
  {
   "title": "TOTAL DE CASOS POR ESTATUS",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "  select \n  sum(CASE WHEN a.id_estatus in (3,4,6,7,8) THEN 1 ELSE 0 END) AS \"EN EL SISTEMA\",\n\tsum(CASE WHEN a.id_estatus in (3,4,7,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\n\tsum(CASE WHEN a.id_estatus = 6 and (a.feedback >= 2   or  a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ALTA VALORACION O VERIFICACION\",\n\t(sum(CASE WHEN a.id_estatus = 6 THEN 1 ELSE 0 END) - sum(CASE WHEN a.id_estatus = 6 and (a.feedback >= 2   or  a.verificado = 'SI') THEN 1 ELSE 0 END)) AS \"CASOS POR EVALUAR\",\n\tsum(CASE WHEN a.id_estatus = 6 THEN 1 ELSE 0 END) AS \"TOTAL ATENDIDO\" --count(a.id) as \"TOTAL\"\n\tfrom gestion.caso a\n\tinner join gestion.estatus e on e.id = a.id_estatus\n\twhere a.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "TOTAL ATENDIDOS CON VERIFICACION Y EVALUCION POSITIVA%",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\r\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\r\n\t\t\t\t\t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\r\n\t\tFROM gestion.caso a\r\n\t\twhere a.id_estatus in (6) \r\n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL ATENDIDOS SIN VERIFICACION Y EVALUCION POSITIVA%",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\r\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\r\n\t\t\t\t\t\t\t\t\t\t\t\twhere a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\r\n\t\tFROM gestion.caso a\r\n\t\twhere a.id_estatus in (6) \r\n\t\t--and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL DE CASOS POR ESTATUS ATENDIDO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "  select e.nombre::Text \"ESTATUS\",\r\n\t--sum(CASE WHEN d.id_estatus in (3,4,7,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\r\n\tsum(CASE WHEN a.id_estatus = 6 and (a.feedback >= 2   or  a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ALTA VALORACION O VERIFICACION\",\r\n\tsum(CASE WHEN a.id_estatus = 6 and (a.feedback < 2) THEN 1 ELSE 0 END) AS \"BAJA VALORACION\",\r\n\tsum(CASE WHEN a.id_estatus = 6 and (a.feedback >= 2) THEN 1 ELSE 0 END) AS \"ALTA VALORACION\",\r\n\tsum(CASE WHEN a.id_estatus = 6 and (a.feedback < 2 AND  a.verificado  = 'SI') THEN 1 ELSE 0 END) AS \"BAJA VALORACION Y VERIFICADO\",\r\n\tsum(CASE WHEN a.id_estatus = 6 and (a.feedback IS NULL  AND  a.verificado IS NULL) THEN 1 ELSE 0 END) AS \"SIN VALORACION\",\r\n\tcount(a.id) as \"TOTAL\"\r\n\tfrom gestion.caso a\r\n\tinner join gestion.estatus e on e.id = a.id_estatus\r\n\twhere a.id_estatus in (6)\r\n\tgroup by e.id, e.nombre\r\n\torder by e.id asc"
    }
   ]
  }
 ]
}