{
 "title": "Cartelera PDVSA Gas Comunal",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "LISTADO DE CASOS  DE PDVSA GAS COMUNAL EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT a.nombre::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\",\r\n    \te.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\",\r\n    \tb.nombre::Text \"ESTADO\",\r\n    \tc.nombre::Text \"MUNICIPIO\",\r\n    \td.nombre::Text \"PARROQ\",\r\n    \ta.direccion::Text \"DIR\",\r\n    \ta.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\",\r\n\t  \tg.name::Text \"SUBCATEG\",\r\n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\ti.nombre::Text \"ESTATUS\",\r\n\t\tto_char(a.fecha, 'dd-mm-YY  hh:mm:ss')::Text \"FECHA\",\r\n\t\tto_char(a.fecha_registro,'dd-mm-YY hh:mm:ss') as \"FECHA ESTATUS\",\r\n    case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n\t\tk.nombre::Text \"RESPONSABLE\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\r\n      where  j.id_resolutorio in (406)\r\n      and j.principal is true\r\n      and a.id_estatus in (3,4,8)"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE - DETALLADO - ESTADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (406) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (4) \nand b.id < 25 and  e.id_resolutorio in (406)\nand e.principal is true\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE PDVSA GAS COMUNAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (5)"
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 33 },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (5)\n    and a.id_estatus in (5) "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 33 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (5)\n    and a.id_estatus in (1) "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (5)\n    and a.id_estatus in (1,2,3,4,6,7,8) \n"
      }
     ]
    },
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (3,4,8)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (406)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select to_char(a.fecha, 'dd-mm-YY') as fecham, to_char(a.fecha, 'mm-dd') as fechaa, count(a.fecha) as total\n    \tfrom gestion.caso a\n    \t\tinner join gestion.responsable b on b.id_caso = a.id\n    \t \tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\twhere a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)\n\t  and b.id_resolutorio in (406) \n\t\tand a.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham, fechaa \n        order by fechaa"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n   from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t inner join gestion.responsable d on d.id_caso = a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (406) \n\t and a.id_estatus in (1,2,3,4,6,7,8)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n   from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t inner join gestion.responsable d on d.id_caso = a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (406) \n\t and a.id_estatus in (6)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CATEGORÍAS PDVSA GAS COMUNAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE PDVSA GAS COMUNAL",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select count(a.id) as TOTAL\n\tfrom gestion.caso a\n\t  inner join gestion.responsable c on c.id_caso = a.id\n\t  where a.id_sub_categoria in (5) \n\t        and a.id_estatus in (3,4,6,7,8)\n\t\t      and c.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (PDVSA GAS COMUNAL)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\n        from gestion.caso a\n\t\t\t\tinner join gestion.responsable d on d.id_caso = a.id\n        where a.id_sub_categoria in (5) and a.id_estatus in (1,2,3,4,6,7,8)\n\t\t\t\t        and a.id_extra_categoria is not null\n\t\t\t\t        and d.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (PDVSA GAS COMUNAL)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\n      from gestion.caso a\n      inner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n      where a.id_sub_categoria in (5) and \n            d.id_estatus in (1,2,3,4,6,7,8) and a.id_extra_categoria is null\n\t\t\t\t    and b.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  PDVSA GAS COMUNAL)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "rawSql": "  SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t       FROM gestion.caso a \n         inner join gestion.category c on c.id = a.id_sub_categoria\n\t\t\t\t inner join gestion.responsable b on b.id_caso = a.id\n         LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria   \n         where a.id_sub_categoria in (5) and \n\t\t\t   a.id_estatus in (1,2,3,4,6,7,8) \n\t\t\t   and b.id_resolutorio in (406)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE PDVSA GAS COMUNAL DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "rawSql": "  SELECT i.nombre as estatus, count(a.id) as subtotal,\n            (SELECT count(a.id) FROM gestion.caso a\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n    \t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n    \t\t\t\t\tinner JOIN gestion.estatus i ON a.id_estatus = i.id\n    \t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n    \t\t\t\t\twhere a.id_estatus in (1,2,3,4,6,7,8) \n    \t\t\t\t\tand c.id_resolutorio in (406))::Text \"Total\"\n      FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n         where a.id_estatus in (1,2,3,4,6,7,8)\n\t\t     and c.id_resolutorio in (406)\n         group by estatus"
      }
     ]
    },
    {
     "title": "REVISIÓN-UBCH",
     "type": "gauge",
     "description": "Total de casos generados",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 61 },
     "targets": [
      {
       "rawSql": "         SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere a.id_estatus in (3,4,6,7,8)\n\t\t\t\t\tand c.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 61 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n        SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere a.id_estatus in (3,4,7,8) --and a.id_sub_categoria in (1)\n\t\t\t\t\tand c.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "ATENDIDOS-UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 61 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere a.id_estatus in (6)\n\t\t\t\t\tand c.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 61 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 66 },
     "targets": [
      {
       "rawSql": " SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.denunciante e on e.id = a.id_denunciante\n                inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t        inner join gestion.responsable b on b.id_caso = a.id\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n            where a.id_estatus in (1,2,3,4,6,7,8)\n\t\t\t      and b.id_resolutorio in (406)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS ATENDIDOS SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 66 },
     "targets": [
      {
       "rawSql": "     SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.denunciante e on e.id = a.id_denunciante\n                inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t          inner join gestion.responsable b on b.id_caso = a.id\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n            where a.id_estatus in (6)\n\t\t\t      and b.id_resolutorio in (406)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n\t          where  a.id_estatus in (1,2,3,4,6,7,8) --and a.id_sub_categoria in (1)\n\t\t\t      and c.id_resolutorio in (406)\n            group by estado order by total desc Limit 10;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES-CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n\t          where a.id_estatus in (6) --and a.id_sub_categoria in (1)\n\t\t\t      and c.id_resolutorio in (406)\n            group by estado order by total desc Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE PDVSA GAS COMUNAL DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \n      --a.codigo::Text \"CODIGO CASO\",\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n      case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\n\t\t\ti.nombre::Text \"ESTATUS\",\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\n            case when w.first_name is null then 'Analizando' else (w.first_name || ' ' || w.last_name ) end::Text \"RESPONSABLE\",\n\t\t\tw.phone::Text \"TELF. RESP\"\n            FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      inner join lista.ubch z on z.cedula = e.cedula \n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id \n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\n            where a.id_estatus in (1,2,3,4,6,7,8)\n            and j.id_resolutorio in (406);"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE PDVSA GAS POR ENTIDADES FEDERALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS  EN PROCESO DE PDVSA GAS COMUNAL",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.responsable b on b.id_caso = a.id\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (406) \n    and a.id_estatus in (3,4,7,8) "
      }
     ]
    },
    {
     "title": "CASOS  ATENDIDOS DE PDVSA GAS COMUNAL",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  SELECT count(a.id)\n\t  FROM gestion.caso a\n\t  inner join gestion.responsable b on b.id_caso = a.id\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (406) \n    and a.id_estatus in (6) "
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t inner join gestion.responsable d on d.id_caso = a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (406) \n\t and a.id_estatus in (3,4,7,8)\n    group by estado\n    order by total desc;"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t inner join gestion.responsable d on d.id_caso = a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (406) \n\t and a.id_estatus in (6)\n    group by estado\n    order by total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS COMUNAL DE UBCH RECIBIDOS-ATENDIDOS (POR ENTIDADES  FEDERALES) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE PDVSA GAS COMUNAL DE UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado \r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\tinner join gestion.responsable c on c.id_caso = a.id\r\n       \twhere  a.id_estatus in (1,2,3,4,6,8)\r\n\t\t\tand c.id_resolutorio in (406)\r\n        group by b.nombre order by TOTAL desc"
      }
     ]
    },
    {
     "title": "TOTAL CASOS DE PDVSA GAS COMUNAL ATENDIDOS DE  UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\tinner join gestion.responsable c on c.id_caso = a.id\n      where  a.id_estatus in (6)\n\t\t\tand c.id_resolutorio in (406)\n      group by b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS COMUNAL RECIBIDOS-ATENDIDOS POR MUNICIPIOS(CAPITALES DE ENTIDADES FEDERALES )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE PDVSA GAS COMUNAL POR MUN. CAPITALES",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\n      inner join gestion.estado b on b.id = a.id_estado\n      inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t  and e.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS  - PDVSA GAS COMUNAL (MUN. CAPITALES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (6) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t  and e.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "CASOS DE PDVSA GAS COMUNAL POR MUN. CAPITALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t      \tinner join gestion.responsable e on e.id_caso = a.id\n       where a.id_estatus in (1,2,3,4,6,7,8)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t     and e.id_resolutorio in (406)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS  - PDVSA GAS COMUNAL (MUN. CAPITALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t inner join gestion.responsable e on e.id_caso = a.id\n       where a.id_estatus in (6)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t     and e.id_resolutorio in (406)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS COMUNAL RECIBIDOS-ATENDIDOS DE OTROS MUNICIPIOS  (CIUDADES IMPORTANTES)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS -  PDVSA GAS COMUNAL  (CIUDADES IMPORTANTES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t  and e.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS - PDVSA GAS COMUNAL (CD. IMPORTANTE)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (6) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t  and e.id_resolutorio in (406)"
      }
     ]
    },
    {
     "title": "CASOS - PDVSA GAS COMUNAL (CIUDADES IMPORTANTES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n            where a.id_estatus in (1,2,3,4,6,7,8)\n            and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t          and e.id_resolutorio in (406)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS - PDVSA GAS COMUNAL (CD. IMPORTANTE)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n      where a.id_sub_categoria in (4) and a.id_estatus in (6)\n      and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t    and e.id_resolutorio in (406)\n       group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS COMUNAL RECIBIDOS-ATENDIDOS  POR ENTIDADES PARROQUIALES (50 PRIMERAS PARROQUIAS) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n\t\t        inner join gestion.responsable e on e.id_caso = a.id\n            where a.id_estatus in (1,2,3,4,6,7,8)\n\t  \t\tand e.id_resolutorio in (406)\n        group by c.nombre, b.nombre\n        order by TOTAL desc limit 50\n    "
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 11, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n        where a.id_estatus in (6)\n\t  \t\tand e.id_resolutorio in (406)\n        group by c.nombre, b.nombre\n        order by TOTAL desc limit 50"
      }
     ]
    }
   ]
  }
 ]
}