{
 "title": "REPORTES GENERAL EFECTIVIDAD GLOBAL",
 "time": { "from": "2024-03-05T23:22:13.812Z", "to": "2024-03-06T23:22:13.812Z" },
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 }, "options": { "content": "\n\n\n  # NIVEL NACIONAL\n" } },
  {
   "title": "MINISTERIOS Y ENTES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                    \t\tinner join gestion.municipio g on g.id = a.id_municipio\n                    \t\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (3,4)\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (3,4) \n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback > 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOBERNACIONES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (1)\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (1)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (2)\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (2)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback > 2  or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (1,2,3,4)\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4)\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"ESTADOS\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (3,4) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/sum(CASE WHEN a.id_estatus in (3,4,6,8) and z.id_tipo_resolutorio in (3,4) THEN 1 ELSE 0 END)::decimal,2) AS \"MINISTERIOS Y ENTES\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/sum(CASE WHEN a.id_estatus in (3,4,6,8) and z.id_tipo_resolutorio in (1) THEN 1 ELSE 0 END)::decimal,2) AS \"GOBERNACIONES\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (2) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/sum(CASE WHEN a.id_estatus in (3,4,6,8) and z.id_tipo_resolutorio in (2) THEN 1 ELSE 0 END)::decimal,2) AS \"ALCALDIAS\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1,2,3,4) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"TOTAL\"\nfrom gestion.caso a\ninner join gestion.estado b on b.id = A.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia p on p.id = a.id_parroquia\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (1,2,3,4) and b.id < 25 \nand e.principal is true\ngroup by b.nombre\nHAVING count(*) >= 2\norder by \"TOTAL\" desc\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 28 }, "options": { "content": "# CORREDORES" } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t                      inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (3,4) and bb.corredor = 'SI'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\t  and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (3,4) and bb.corredor = 'SI'\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t                      inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'SI'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'SI'\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t                      inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (2) and bb.corredor = 'SI'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (2) and bb.corredor = 'SI'\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia p on p.id = a.id_parroquia\t\n\t                     \tinner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'SI'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t  inner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia p on p.id = a.id_parroquia\t\n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'SI'\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"ESTADOS\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (3,4) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/sum(CASE WHEN a.id_estatus in (3,4,6,8) and z.id_tipo_resolutorio in (3,4) THEN 1 ELSE 0 END)::decimal,2) AS \"MINISTERIOS Y ENTES\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/sum(CASE WHEN a.id_estatus in (3,4,6,8) and z.id_tipo_resolutorio in (1) THEN 1 ELSE 0 END)::decimal,2) AS \"GOBERNACIONES\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (2) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/sum(CASE WHEN a.id_estatus in (3,4,6,8) and z.id_tipo_resolutorio in (2) THEN 1 ELSE 0 END)::decimal,2) AS \"ALCALDIAS\",\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1,2,3,4) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\t  THEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"TOTAL\"\nfrom gestion.caso a\ninner join gestion.estado b on b.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia p on p.id = a.id_parroquia\ninner join psuv.corredor_electoral_nacional bb on bb.estado = b.nombre\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\nwhere a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (1,2,3,4) and b.id < 25 \nand bb.corredor = 'SI'\nand e.principal is true\ngroup by  b.nombre\nHAVING count(*) > 1\norder by \"TOTAL\" desc"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 43 }, "options": { "content": "# NO CORREDORES" } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t                      inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'NO'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'NO'\n\t\tand b.principal is true\n\t\tand a.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t                      inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (2) and bb.corredor = 'NO'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (2) and bb.corredor = 'NO'\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t                     \tinner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'NO'\n\t\t\t\t\t\t\t\t\t\t   \tand b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.estado e on e.id = a.id_estado\n\t  inner join psuv.corredor_electoral_nacional bb on bb.estado = e.nombre\n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4) and bb.corredor = 'NO'\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  }
 ]
}