{
 "title": "GOBERNACIONES Y ALCALDIAS DETALLADO V3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "gobernaciones",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio where id_tipo_resolutorio = 1 and id_estado = 9 ORDER BY nombre "
   },
   {
    "name": "alcaldia",
    "label": "ALCALDIA",
    "query": "SELECT a.nombre FROM gestion.resolutorio a\ninner join gestion.resolutorio aa ON aa.id = a.id_estado\nwhere a.id_tipo_resolutorio = 2 AND aa.nombre in ($gobernaciones) ;"
   }
  ]
 },
 "panels": [
  {
   "title": "GOBERNACION ($gobernaciones)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"GOBERNACION\",\r\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\r\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (1) AND (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\ninner join gestion.estado b on b.id = z.id_estado\r\nwhere  a.id_estatus in (3,4,6,8)\r\nand z.id_tipo_resolutorio in (1)  and b.id < 25\r\nand e.principal is true and z.nombre in ($gobernaciones)\r\ngroup by b.nombre\r\nHAVING count(*) > 1\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "ALCALDIAS ($gobernaciones)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \r\n    m.nombre::Text \"ALCALDIAS\",\r\n\t\tsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\n\t\tsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\r\n\t\tsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\r\n\t\tsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\", \r\n\t\tsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \r\n\t\ttrunc(sum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\r\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\n\t\tfrom gestion.caso a\r\n\t\tinner join gestion.responsable e on e.id_caso =  a.id\r\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\r\n\t\tinner join gestion.municipio m on m.id = z.id_municipio\r\n\t\twhere a.id_estatus in (1,2,3,4,6,8)\r\n\t\tand z.id_tipo_resolutorio in (2)\r\n\t\tand z.nombre in ($alcaldia) and zz.nombre in ($gobernaciones)\r\n\t\tand e.principal is true\r\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" DESC"
    }
   ]
  },
  {
   "title": "CASOS DETALLADOS EN PROCESOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS EN PROCESO",
     "type": "table",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": " SELECT a.nombre::Text \"CODIGO\",\r\n    \te.cedula::Text \"CEDULA\",\r\n    \te.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\",\r\n    \tk.nombre::Text \"RESPONSABLE\",\r\n    \tto_char(h.fecha_registro,'dd-mm-YY') as \"FECHA ULTIMO ESTATUS\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            inner join gestion.historico h ON a.id = h.id_caso\r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id and j.principal is true\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT join gestion.resolutorio zz on zz.id =  k.id_estado \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n      \t\twhere k.nombre in ($gobernaciones, $alcaldia) and zz.nombre in ($gobernaciones)\r\n      \t\t     and j.principal is true and a.id_estatus in (3,4,8) \r\n      \t\t    -- AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
      }
     ]
    }
   ]
  }
 ]
}