{
 "title": "MINISTERIOS DE EDUCACION BASICA",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "LISTADO DE CASOS  DE EDUCACION BASICA EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT --DISTINCT ON (a.id) a.id::Text \"CODIGO CASOS\", \r\n      a.nombre::Text \"CODIGO CASO\", \r\n      e.cedula::Text \"CEDULA\", \r\n      e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", \r\n\t\t\tb.nombre::Text \"ESTADO\", \r\n\t\t\tc.nombre::Text \"MUNICIPIO\", \r\n\t\t\td.nombre::Text \"PARROQ\", \r\n\t\t\ta.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", \r\n\t\t\tg.name::Text \"SUBCATEG\",\r\n\t    case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n\t\t\tto_char(a.fecha, 'dd-mm-YY')::Text \"FECHA\",\r\n      case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n      k.nombre::Text \"RESPONSABLE\"\r\n            FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id and j.id_user is not null\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n           -- LEFT JOIN  public.user_detail v ON w.id = v.user_id\r\n            where a.id_estatus in (3,4,8) \r\n            and a.id_sub_categoria in (2,12) \r\n            and j.id_resolutorio in (361) \r\n            order by a.id desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE-ESTADOS-DETALLADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (3) and  e.id_resolutorio in (361) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\n--inner join gestion.historico d on d.id_caso = a.id\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (3) \nand a.id_sub_categoria in (2,12)\nand b.id < 25 and  e.id_resolutorio in (361)\nand e.principal is true \ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE EDUCACION BASICA ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n   where \n    a.id_sub_categoria in (2,12)\n    and a.id_origen in (1) "
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    where a.id_sub_categoria in (2,12)\n    and a.id_origen in (1)\n    and a.id_estatus in (5)"
      }
     ]
    },
    {
     "title": "CASOS RECIBIDO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    where a.id_sub_categoria in (2,12)\n    and a.id_origen in (2) "
      }
     ]
    },
    {
     "title": "DEVUELTO A PATRIA",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    where a.id_sub_categoria in (2,12)\n    and a.id_origen in (2)\n    and a.id_estatus in (5)"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\n     from gestion.caso a\n     inner join gestion.category c on c.id = a.id_sub_categoria\n     where a.id_sub_categoria in (2,12) and a.id_estatus in (1,2,3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (361)\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (553)\nand b.principal is true\nand a.id_estatus in (3,4,7,8)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (361)\nand b.principal is true\nand a.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (361)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id) \n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n                                            where b.id_resolutorio in (361)\n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::Decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (361)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\n      select to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'mm-dd') as fechaa, count(a.fecha) as total\n\t\t\t\tfrom gestion.caso a\n\t\t\t\t\tinner join gestion.category c on c.id = a.id_sub_categoria\n\t\t\t\t\t--inner join gestion.historico d on d.id_caso = a.id  \n\t\t\t\t\tinner JOIN  gestion.responsable j ON j.id_caso = a.id\n\t\t\t\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL) \n\t\t\t\t  and a.id_sub_categoria in (2,12) \n\t\t\t\t  and a.id_estatus in (1,2,3,4,6,7,8) \n\t\t\t\t  and j.id_resolutorio in (361)\n\t\t\t\t\tgroup by fecham, fechaa\n\t\t\t\t\torder by fechaa"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\n        select \n\t\t\t\t\t\tb.nombre as estado, count(a.id) as total\n\t\t\t\t\t\tfrom gestion.caso a\n\t\t\t\t\t\tinner join gestion.estado b on b.id = a.id_estado\n\t\t\t\t\t\tinner join  gestion.responsable j ON j.id_caso = a.id\n\t\t\t\t\t\twhere  a.id_sub_categoria in (2,12) \n\t\t\t\t\t\tand a.id_estatus in (1,2,3,4,6,7,8) and j.id_resolutorio in (361)\n\t\t\t\t\t\tgroup by estado\n\t\t\t\t\t\torder by total desc\n\t\t\t\t\t\tLimit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS RESUELTOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\nselect b.nombre as estado, count(a.id) as total\n\t\t\t\t\t\tfrom \tgestion.caso a\n\t\t\t\t\t\t   inner join gestion.estado b on b.id = a.id_estado\n\t\t\t\t\t\t   inner JOIN  gestion.responsable j ON j.id_caso = a.id\n\t\t\t\t\t\twhere  a.id_sub_categoria in (2,12) and a.id_estatus in (6) and j.id_resolutorio in (361)\n\t\t\t\t\t\tgroup by estado\n\t\t\t\t\t\torder by total desc\n\t\t\t\t\t\tLimit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CATEGORÍAS EDUCACION BASICA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE EDUCACION BASICA EN PROCESO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select count(a.id) as TOTAL\r\n\tfrom gestion.caso a\r\n\t  inner join gestion.responsable c on c.id_caso = a.id\r\n\t  where a.id_sub_categoria in (2,12) \r\n\t        and a.id_estatus in (3,4,6,7,8)\r\n\t\t      and c.id_resolutorio in (361)"
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (EDUCACION BASICA)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\r\n                from gestion.caso a\r\n\t\t\t\tinner join gestion.responsable d on d.id_caso = a.id\r\n            where a.id_sub_categoria in (2,12) and \r\n                a.id_estatus in (1,2,3,4,6,7,8)\r\n\t\t\t\t        and a.id_extra_categoria is not null\r\n\t\t\t\t        and d.id_resolutorio in (361)"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (EDUCACION BASICA)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select count(*) as TOTAL\n      from gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n      where a.id_sub_categoria in (2,12)\n      and a.id_estatus in (1,2,3,4,6,7,8) and a.id_extra_categoria is null\n\t\t\tand b.id_resolutorio in (361)"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  EDUCACION BASICA)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \r\n\t     FROM gestion.caso a \r\n        inner join gestion.category c on c.id = a.id_sub_categoria \r\n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\r\n        left join gestion.category m ON m.id = a.id_extra_categoria   \r\n        where a.id_sub_categoria in (2,12) \r\n        and a.id_estatus in (1,2,3,4,6,7,8) \r\n\t\t\t  and b.id_resolutorio in (361)\r\n        GROUP BY sub_categoria\r\n        ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE EDUCACION BASICA DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "  SELECT i.nombre as estatus, count(a.id) as subtotal,\r\n            (SELECT count(a.id) FROM gestion.caso a\r\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n    \t\t\t\t\t--inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n    \t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n    \t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\r\n    \t\t\t\t\twhere a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (7)\r\n    \t\t\t\t\tand c.id_resolutorio in (361))::Text \"Total\"\r\n      FROM gestion.caso a\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            --inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\r\n         where a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (7)\r\n\t\t and c.id_resolutorio in (361)\r\n         group by estatus"
      }
     ]
    },
    {
     "title": "EDUCACIÓN BASICA -UBCH",
     "type": "gauge",
     "description": "Total de casos generados",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
     "targets": [
      {
       "rawSql": "         SELECT count(a.id)\n            FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            where a.id_estatus in (3,4,6) and a.id_sub_categoria in (2,12) and j.id_resolutorio in (361)"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) \n          FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n           -- inner join lista.ubch z on z.cedula = e.cedula\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            where a.id_estatus in (3,4,8) and a.id_sub_categoria in (2,12) \n            and j.id_resolutorio in (361)"
      }
     ]
    },
    {
     "title": "ATENDIDOS-UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n            FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            where a.id_estatus in (6) and a.id_sub_categoria in (2,12) and j.id_resolutorio in (361)"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n           inner join gestion.category c on c.id = a.id_sub_categoria  \r\n           inner join gestion.denunciante e on e.id = a.id_denunciante\r\n           --inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n\t\t\t     inner join gestion.responsable b on b.id_caso = a.id\r\n           LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \r\n           where a.id_estatus in (1,2,3,4,6,8)\r\n\t\t\t     and b.id_resolutorio in (361)\r\n           GROUP BY sub_categoria\r\n           ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS RESUELTOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n           inner join gestion.category c on c.id = a.id_sub_categoria \r\n           inner join gestion.denunciante e on e.id = a.id_denunciante\r\n           --inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n\t\t\t\t   inner join gestion.responsable b on b.id_caso = a.id\r\n           LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \r\n           where a.id_estatus in (6)\r\n\t\t\t     and b.id_resolutorio in (361)\r\n           GROUP BY sub_categoria\r\n           ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\r\n  from gestion.caso a\r\n\tinner join gestion.estado b on b.id = a.id_estado\r\n  inner join gestion.denunciante e on e.id = a.id_denunciante\r\n  --inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n\tinner join gestion.responsable c on c.id_caso = a.id\r\n\twhere  a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (1)\r\n\tand c.id_resolutorio in (361)\r\n  group by estado order by total desc Limit 10;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES-CASOS RESUELTOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\r\n    from gestion.caso a\r\n\t  inner join gestion.estado b on b.id = a.id_estado\r\n    inner join gestion.denunciante e on e.id = a.id_denunciante\r\n    --inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n\t\tinner join gestion.responsable c on c.id_caso = a.id\r\n\t  where  a.id_estatus in (6) --and a.id_sub_categoria in (1)\r\n\t\tand c.id_resolutorio in (503)\r\n    group by estado order by total desc Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE EDUCACION BASICA DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \r\n      --a.codigo::Text \"CODIGO CASO\",\r\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n            case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n            case when w.username is null then 'Analizando' else (w.first_name || ' ' || w.last_name) end::Text \"RESPONSABLE\",\r\n\t\t\tw.phone::Text \"TELF. RESP\"\r\n            FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t      --inner join lista.ubch z on z.cedula = e.cedula -- usuario ubch --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id \r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\r\n            where a.id_estatus in (1,2,3,4,6,8)\r\n            and j.id_resolutorio in (361);"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE EDUCACION BASICA POR ENTIDADES FEDERALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS  EN PROCESO  DE EDUCACION BASICA ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.responsable b on b.id_caso = a.id\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (361) \n\t  --c.id_sub_categoria in (1)\n    and a.id_estatus in (3,4,7,8) "
      }
     ]
    },
    {
     "title": "CASOS  RESUELTOS  DE EDUCACION BASICA ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner JOIN  gestion.responsable j ON j.id_caso = a.id\n    inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n    where a.id_estatus in (6) and k.id in (361)"
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t   inner join gestion.estado b on b.id = a.id_estado\n     inner JOIN  gestion.responsable j ON j.id_caso = a.id\n     inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n\t   where  a.id_estatus in (3,4,7,8) and k.id in (361)\n     group by estado\n     order by total desc\n     Limit 10;"
      }
     ]
    },
    {
     "title": "CASOS RESUELTOS POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t   inner join gestion.estado b on b.id = a.id_estado\n     inner JOIN  gestion.responsable j ON j.id_caso = a.id\n     inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n\t  where  a.id_estatus in (6) and k.id in (361)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE EDUCACION BASICA DE UBCH RECIBIDOS-RESUELTOS (POR ENTIDADES  FEDERALES) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE EDUCACION BASICA DE UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  select b.nombre as estado, count(a.id) as total\n            from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t          where a.id_estatus in (1,2,3,4,6,7,8) and k.id in (361)\n            group by estado\n            order by total desc\n            Limit 10;"
      }
     ]
    },
    {
     "title": "TOTAL CASOS DE EDUCACION BASICA RESUELTOS DE  UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n       from gestion.caso a\n\t     inner join gestion.estado b on b.id = a.id_estado\n       inner JOIN  gestion.responsable j ON j.id_caso = a.id\n       inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n       --inner JOIN  public.user bb ON bb.id = d.id_user_reg\n       LEFT JOIN  public.user w ON w.id = j.id_user\n       inner join gestion.denunciante e on e.id = a.id_denunciante\n       inner join lista.ubch z on z.cedula = e.cedula\n\t     where  a.id_estatus in (6) and k.id in (361)\n       group by estado\n       order by total desc\n       Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE EDUCACION BASICA RECIBIDO-RESUELTO POR MUNICIPIOS(CAPITALES DE ENTIDADES FEDERALES )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE EDUCACION BASICA POR MUN. CAPITALES",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN gestion.responsable j ON j.id_caso = a.id\n            inner JOIN gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n    where a.id_estatus in (1,2,3,4,6,7,8) and k.id in (361)\n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS  - EDUCACION BASICA (MUN. CAPITALES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN gestion.responsable j ON j.id_caso = a.id\n            inner JOIN gestion.resolutorio k ON k.id = j.id_resolutorio\n            left  JOIN public.user w ON w.id = j.id_user\n    where a.id_estatus in (6) and k.id in (361)\n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)"
      }
     ]
    },
    {
     "title": "CASOS DE EDUCACION BASICA POR MUN. CAPITALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select \n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            left  JOIN  public.user w ON w.id = j.id_user\n       where a.id_estatus in (1,2,3,4,6,7,8) and k.id in (361)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS RESUELTOS  - EDUCACION BASICA (MUN. CAPITALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n       where a.id_estatus in (6) and k.id in (361)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335,214,250,296)\n       group by c.nombre, b.nombre\n       order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE EDUCACION BASICA RECIBIDO-RESUELTOS DE OTROS MUNICIPIOS  (CIUDADES IMPORTANTES)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS -  EDUCACION BASICA  (CIUDADES IMPORTANTES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n    where a.id_estatus in (1,2,3,4,6,7,8) and k.id in (361)\n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) "
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS - EDUCACION BASICA  (CD. IMPORTANTE)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n    where a.id_estatus in (6) and k.id in (361)\n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) "
      }
     ]
    },
    {
     "title": "CASOS - EDUCACION BASICA (CIUDADES IMPORTANTES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n       where a.id_estatus in (1,2,3,4,6,7,8) and k.id in (361)\n       and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n       group by c.nombre, b.nombre\n       order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS RESUELTO - EDUCACION BASICA (CD. IMPORTANTE)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "Select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n       where a.id_estatus in (6) and k.id in (361)\n       and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n       group by c.nombre, b.nombre\n       order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE EDUCACION BASICA RECIBIDOS-RESUELTOS  POR ENTIDADES PARROQUIALES (50 PRIMERAS PARROQUIAS) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n     where a.id_estatus in (1,2,3,4,6,7,8) and k.id in (361)\n     group by c.nombre, b.nombre\n     order by TOTAL desc limit 50"
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n            LEFT JOIN  public.user w ON w.id = j.id_user\n       where a.id_estatus in (6) and k.id in (361)\n       group by c.nombre, b.nombre\n       order by TOTAL desc limit 50"
      }
     ]
    }
   ]
  }
 ]
}