{
 "title": "GOBERNACIONES Y ALCALDIAS POR CATEGORIAS V3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "gobernaciones",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio where id_tipo_resolutorio = 1 AND id_estado =  20 ORDER BY nombre "
   },
   {
    "name": "alcaldia",
    "label": "ALCALDIA",
    "query": "SELECT a.nombre FROM gestion.resolutorio a\ninner join gestion.resolutorio aa ON aa.id = a.id_estado\nwhere a.id_tipo_resolutorio = 2 AND aa.nombre in ($gobernaciones) ;"
   },
   {
    "name": "estatus",
    "label": "ESTATUS",
    "query": "SELECT nombre FROM gestion.estatus Where id in (3,4,6,8)"
   }
  ]
 },
 "panels": [
  {
   "title": "GOBERNACION ($gobernaciones)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"GOBERNACION\",\nsum(CASE WHEN a.id_sub_categoria in (10) THEN 1 ELSE 0 END) AS \"AGUA\",\nsum(CASE WHEN a.id_sub_categoria in (8) THEN 1 ELSE 0 END) AS \"ELECTRICIDAD\",\nsum(CASE WHEN a.id_sub_categoria in (11) THEN 1 ELSE 0 END) AS \"GAS DOMESTICO\",\nsum(CASE WHEN a.id_sub_categoria in (13) THEN 1 ELSE 0 END) AS \"SALUD\",\nsum(CASE WHEN a.id_sub_categoria in (7) THEN 1 ELSE 0 END) AS \"TRANSP. PÚB\",\nsum(CASE WHEN a.id_sub_categoria in (9) THEN 1 ELSE 0 END) AS \"TELECOM\",\nsum(CASE WHEN a.id_sub_categoria in (16) THEN 1 ELSE 0 END) AS \"METRO CSC\",\nsum(CASE WHEN a.id_sub_categoria in (17) THEN 1 ELSE 0 END) AS \"HURACANES\",\nsum(CASE WHEN a.id_sub_categoria in (5) THEN 1 ELSE 0 END) AS \"GAS COMUNAL\",\nsum(CASE WHEN a.id_sub_categoria in (6) THEN 1 ELSE 0 END) AS \"GAS DIRECTO\",\nsum(CASE WHEN a.id_sub_categoria in (12) THEN 1 ELSE 0 END) AS \"EDUCACION\",\nsum(CASE WHEN a.id_sub_categoria in (14) THEN 1 ELSE 0 END) AS \"EDU. BÁSICA\",\nsum(CASE WHEN a.id_sub_categoria in (15) THEN 1 ELSE 0 END) AS \"EDU. UNIVER.\",\ncount(*)AS \"TOTAL\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = z.id_estado\ninner join gestion.estatus est on est.id = a.id_estatus\nwhere  a.id_estatus in (3,4,6,8)\n--and a.id_sub_categoria in (1,2,3,4,5,7,10,11,12,13)\nand z.id_tipo_resolutorio in (1)  and b.id < 25\nand e.principal is true and z.nombre in ($gobernaciones)\nand est.nombre in ($estatus)\ngroup by b.nombre\nHAVING count(*) > 1\n--order by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "ALCALDIAS ($gobernaciones)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \n    m.nombre::Text \"ALCALDIAS\",\n\t sum(CASE WHEN a.id_sub_categoria in (1) THEN 1 ELSE 0 END) AS \"AGUA\",\n    sum(CASE WHEN a.id_sub_categoria in (3) THEN 1 ELSE 0 END) AS \"ELECTRICIDAD\",\n    sum(CASE WHEN a.id_sub_categoria in (4) THEN 1 ELSE 0 END) AS \"GAS DOMESTICO\",\n    sum(CASE WHEN a.id_sub_categoria in (5) THEN 1 ELSE 0 END) AS \"SALUD\",\n    sum(CASE WHEN a.id_sub_categoria in (6) THEN 1 ELSE 0 END) AS \"TRANSP. PÚB\",\n    sum(CASE WHEN a.id_sub_categoria in (7) THEN 1 ELSE 0 END) AS \"TELECOM\",\n    sum(CASE WHEN a.id_sub_categoria in (8) THEN 1 ELSE 0 END) AS \"METRO CSC\",\n    sum(CASE WHEN a.id_sub_categoria in (9) THEN 1 ELSE 0 END) AS \"HURACANES\",\n    sum(CASE WHEN a.id_sub_categoria in (10) THEN 1 ELSE 0 END) AS \"GAS COMUNAL\",\n    sum(CASE WHEN a.id_sub_categoria in (11) THEN 1 ELSE 0 END) AS \"GAS DIRECTO\",\n    sum(CASE WHEN a.id_sub_categoria in (2) THEN 1 ELSE 0 END) AS \"EDUCACION\",\n    sum(CASE WHEN a.id_sub_categoria in (12) THEN 1 ELSE 0 END) AS \"EDU. BÁSICA\",\n    sum(CASE WHEN a.id_sub_categoria in (13) THEN 1 ELSE 0 END) AS \"EDU. UNIVER.\",\n    count(*)AS \"TOTAL\"\n\t\tfrom gestion.caso a\n\t\tinner join gestion.responsable e on e.id_caso =  a.id\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\n\t\tinner join gestion.municipio m on m.id = z.id_municipio\n\t\tinner join gestion.estatus est on est.id = a.id_estatus\n\t\twhere a.id_estatus in (3,4,6,8)\n\t\tand z.id_tipo_resolutorio in (2)\n\t\tand z.nombre in ($alcaldia) and zz.nombre in ($gobernaciones)\n\t\tand est.nombre in ($estatus)\n\t\tand e.principal is true\n\t\tgroup by m.nombre \n\t\t--order by \"% EFECTIVIDAD %\" DESC"
    }
   ]
  },
  { "title": "CASOS DETALLADOS EN PROCESOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "LISTADO DE CASOS EN PROCESO",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": " SELECT a.nombre::Text \"CODIGO\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \tk.nombre::Text \"RESPONSABLE\",\n    \tto_char(a.fecha,'dd-mm-YY') as \"FECHA\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id and j.principal is true\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT join gestion.resolutorio zz on zz.id =  k.id_estado \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n      \t\twhere k.nombre in ($gobernaciones, $alcaldia) and zz.nombre in ($gobernaciones)\n      \t\t     and j.principal is true and a.id_estatus in (3,4,8) \n      \t\t   "
    }
   ]
  }
 ]
}