{
 "title": "CATEGORIA CANTV (ESTADOS Y MUNICIPIOS)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "categoria",
    "label": "CATEGORIA",
    "query": "SELECT name FROM gestion.category where parent in (9)"
   },
   {
    "name": "categnuevas",
    "label": "NUEVAS CATEGORIAS",
    "query": "SELECT name FROM gestion.category where parent = 60"
   },
   {
    "name": "estado",
    "label": "ESTADOS",
    "query": "SELECT  nombre FROM gestion.estado WHERE id < 25 order by id"
   },
   {
    "name": "municipio",
    "label": "MUNICIPIO",
    "query": "SELECT a.nombre  FROM gestion.municipio a inner join gestion.estado b on a.id_estado = b.id where  b.nombre in ($estado) "
   }
  ]
 },
 "panels": [
  {
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT imagen\n\tFROM vw.imagenes_grafana \n\twhere id = 9"
    }
   ]
  },
  {
   "title": "EFECTIVIDAD ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\t                      inner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\t                      inner join gestion.estado e on e.id = a.id_estado\n\t\t\t                                      inner join gestion.municipio m on m.id = a.id_municipio\n\t\t\t                                      left join gestion.category ca on ca.id =  a.id_adicional_categoria\n                                            where $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) \n\t\t\t\t\t\t\t\t\t\t\t                      and (c.name in ($categoria) or ca.name in ($categnuevas))\n\t\t\t\t\t\t\t\t\t\t\t                      and e.nombre in ($estado) and m.nombre in ($municipio)\n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.category c on c.id =  a.id_extra_categoria\ninner join gestion.estado e on e.id = a.id_estado\ninner join gestion.municipio m on m.id = a.id_municipio\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) \nand (c.name in ($categoria) or ca.name in ($categnuevas))\nand e.nombre in ($estado) and m.nombre in ($municipio)\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASOS  POR ESTADO ($estado)",
   "type": "table",
   "gridPos": { "h": 21, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"ESTADO\", count(*) as \"RECIBIDOS\", \nsum(CASE WHEN a.id_estatus in (3,4,7,8) THEN 1 ELSE 0 END) AS \"POR ATENDER\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2.5 or a.verificado = 'SI') THEN 1 ELSE 0 END)\n|| ' (' || (ROUND(sum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2.5 or a.verificado = 'SI') THEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2)) || '%)'AS \"ATENDIDO\", \nROUND(sum(CASE WHEN a.id_estatus in (3,4,7,8) and e.id_resolutorio in (371) THEN 1 ELSE 0 END)::decimal*100/\n\t  (SELECT count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) \n\t\t\tand (c.name in ($categoria) or ca.name in ($categnuevas))\n\t\t\tand e.nombre in ($estado)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (3,4,7,8))::decimal,2) AS \"PROPORCIÓN\"\nfrom gestion.caso a\ninner join gestion.estado b on b.id = a.id_estado\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.category cc on cc.id =  a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere $__timeFilter(a.fecha_registro) and e.principal is true\nand (cc.name in ($categoria) or ca.name in ($categnuevas)) \nand b.nombre in ($estado)\nand e.id_resolutorio in (371) and a.id_estatus in (3,4,6,7,8) \ngroup by b.nombre\norder by \"POR ATENDER\" desc"
    }
   ]
  },
  {
   "title": "CASOS  POR MUNICIPIO ($municipio)",
   "type": "table",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "select  m.nombre || ' (' ||  b.nombre || ')'  as \"MUNICIPIO\", count(*) as \"RECIBIDOS\", \nsum(CASE WHEN a.id_estatus in (3,4,7,8) THEN 1 ELSE 0 END) AS \"POR ATENDER\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2.5 or a.verificado = 'SI') THEN 1 ELSE 0 END)\n|| ' (' || (ROUND(sum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2.5 or a.verificado = 'SI') THEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2)) || '%)'AS \"ATENDIDO\", \nROUND(sum(CASE WHEN a.id_estatus in (3,4,7,8) and e.id_resolutorio in (371) THEN 1 ELSE 0 END)::decimal*100/\n\t  (SELECT count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n      inner join gestion.municipio m on m.id = a.id_municipio\n      left join gestion.category ca on ca.id =  a.id_adicional_categoria\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) \n\t\t\tand (c.name in ($categoria) or ca.name in ($categnuevas)) \n\t\t\tand e.nombre in ($estado)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (3,4,7,8))::decimal,2) AS \"PROPORCIÓN\"\nfrom gestion.caso a\ninner join gestion.estado b on b.id = a.id_estado\ninner join gestion.municipio m on m.id = a.id_municipio\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.category cc on cc.id =  a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere $__timeFilter(a.fecha_registro) and e.principal is true\nand (cc.name in ($categoria) or ca.name in ($categnuevas)) \nand b.nombre in ($estado) and m.nombre in ($municipio)\nand e.id_resolutorio in (371) and a.id_estatus in (3,4,6,7,8) \ngroup by m.nombre, b.nombre\norder by \"POR ATENDER\" desc"
    }
   ]
  },
  {
   "title": "CASOS RECIBIDO ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id \n\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\tinner join gestion.estado e on e.id = a.id_estado\n\tinner join gestion.municipio m on m.id = a.id_municipio\n\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\n\twhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) \n\tand (c.name in ($categoria) or ca.name in ($categnuevas)) \n\tand e.nombre in ($estado) and m.nombre in ($municipio)\n  and b.principal is true\t\n  and a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "CASOS ATENDIDO ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.category c on c.id =  a.id_extra_categoria\ninner join gestion.estado e on e.id = a.id_estado\ninner join gestion.municipio m on m.id = a.id_municipio\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) \nand (c.name in ($categoria) or ca.name in ($categnuevas)) \nand e.nombre in ($estado) and m.nombre in ($municipio)\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 2.5   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASO POR ATENDER ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n((SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.responsable b on b.id_caso =  a.id\r\n\tinner join gestion.category c on c.id =  a.id_extra_categoria\r\n\tinner join gestion.estado e on e.id = a.id_estado\r\n\tinner join gestion.municipio m on m.id = a.id_municipio\r\n\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\r\n\twhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) and e.nombre in ($estado) and m.nombre in ($municipio)\r\n\tand (c.name in ($categoria) or ca.name in ($categnuevas))\r\n  and b.principal is true\tand a.id_estatus in (3,4,6,7,8))\r\n  -\r\n  (SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso = a.id\r\ninner join gestion.category c on c.id =  a.id_extra_categoria\r\ninner join gestion.estado e on e.id = a.id_estado\r\ninner join gestion.municipio m on m.id = a.id_municipio\r\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\r\nwhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371) and e.nombre in ($estado) and m.nombre in ($municipio)\r\nand (c.name in ($categoria) or ca.name in ($categnuevas))\r\nand b.principal is true\r\nand a.id_estatus in (6) )) as total"
    }
   ]
  },
  {
   "title": "NIVEL DE SATISFACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\tinner join gestion.estado e on e.id = a.id_estado\n\t\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\t\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.id_resolutorio in (371)\n\t\t\tand (c.name in ($categoria) or ca.name in ($categnuevas)) \n\t\t\tand e.nombre in ($estado) and m.nombre in ($municipio)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "CASOS DETALLADOS POR ANTENDER ($categoria)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n      a.descripcion::TEXT \"DESCRIP\",\n      a.nombre::Text \"CODIGO\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n\t  \ta.fecha::Text \"FECHA CREACION\"\n\t  \tFROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      inner join gestion.responsable r on r.id_caso = a.id\n            inner JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            left join gestion.category ca on ca.id =  a.id_adicional_categoria\n      where $__timeFilter(a.fecha_registro) and r.id_resolutorio in (371) and r.principal is true\n\t  \t\t    and (m.name in ($categoria) or ca.name in ($categnuevas))\n\t  \t\t    and b.nombre in ($estado) and c.nombre in ($municipio)\n\t\t\t      and a.id_estatus in (3,4,7,8)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.sub_categoria b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.extra_categoria c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\twhere \n\t\t\t\t\t\t\t\t\t\t\ta.id_sub_categoria = 7 and a.id_extra_categoria = 25\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (597,563,566)\n\t\t\t\t\t\t\t\t\t\t\tand d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.sub_categoria b on b.id = a.id_sub_categoria\ninner join gestion.extra_categoria c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso \nwhere \na.id_sub_categoria = 7 and a.id_extra_categoria = 25\nand e.id_resolutorio in (597,563,566)\nand d.active = 1 and d.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.sub_categoria b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.extra_categoria c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\twhere \n\t\t\t\t\t\t\t\t\t\t\ta.id_sub_categoria = 7 and a.id_extra_categoria = 31\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (597,563,566)\n\t\t\t\t\t\t\t\t\t\t\tand d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.sub_categoria b on b.id = a.id_sub_categoria\ninner join gestion.extra_categoria c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso \nwhere \na.id_sub_categoria = 7 and a.id_extra_categoria = 31\nand e.id_resolutorio in (597,563,566)\nand d.active = 1 and d.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.sub_categoria b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.extra_categoria c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\twhere \n\t\t\t\t\t\t\t\t\t\t\ta.id_sub_categoria = 7 and a.id_extra_categoria = 27\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (597,563,566)\n\t\t\t\t\t\t\t\t\t\t\tand d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.sub_categoria b on b.id = a.id_sub_categoria\ninner join gestion.extra_categoria c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso \nwhere \na.id_sub_categoria = 7 and a.id_extra_categoria = 27\nand e.id_resolutorio in (597,563,566)\nand d.active = 1 and d.id_estatus in (6)"
    }
   ]
  }
 ]
}