{
 "title": "CATEGORIA CANTV (V2) NUEVAS CATEGORIAS Y VIEJAS CATEGORIAS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "categoria",
    "label": "CATEGORIA",
    "query": "SELECT name FROM gestion.category where parent in (9) and id not in (59,60,61)"
   },
   {
    "name": "categnuevas",
    "label": "Nuevas Categorias",
    "query": "SELECT name FROM gestion.category where parent = 60"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://images.carnet.org.ve/imagenes/cintillos_cantv2.png\" alt=\"texto_alternativo\" width=\"100%\" height=\"170\">"
   }
  },
  {
   "title": "EFECTIVIDAD ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n\t\t\t\t\t\t\t\t\t\t\t                      inner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\t                      left join gestion.category ca on ca.id =  a.id_adicional_categoria\n                                            where b.id_resolutorio in (371) \n\t\t\t\t\t\t\t\t\t\t\t                      and (c.name in ($categoria) or ca.name in ($categnuevas))\n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.category c on c.id =  a.id_extra_categoria\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere b.id_resolutorio in (371) \nand (c.name in ($categoria) or ca.name in ($categnuevas))\nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASOS  ($categoria)",
   "type": "table",
   "gridPos": { "h": 21, "w": 5, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"ESTADO\",\nsum(CASE WHEN a.id_estatus in (3,4,7,8) THEN 1 ELSE 0 END) AS \"POR ATENDER\",\ntrunc(sum(CASE WHEN a.id_estatus in (3,4,7,8) and e.id_resolutorio in (371) THEN 1 ELSE 0 END)::decimal*100/\n\t  (SELECT count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\n\t\t\twhere b.id_resolutorio in (371) \n\t\t\tand (c.name in ($categoria) or ca.name in ($categnuevas)) \n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (3,4,7,8))::decimal,2) AS \"PROPORCIÓN\"\nfrom gestion.caso a\ninner join gestion.estado b on b.id = a.id_estado\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.category cc on cc.id =  a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere e.principal is true\nand (cc.name in ($categoria) or ca.name in ($categnuevas)) \nand e.id_resolutorio in (371)\ngroup by b.nombre\norder by \"POR ATENDER\" desc"
    }
   ]
  },
  {
   "title": "CASOS DETALLADOS ($categoria)",
   "type": "table",
   "gridPos": { "h": 21, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT a.descripcion::TEXT \"DESCRIP\",\n      a.nombre::Text \"CODIGO\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n\t  \ta.fecha::Text \"FECHA CREACION\"\n\t  \tFROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      inner join gestion.responsable r on r.id_caso = a.id\n            inner JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            left join gestion.category ca on ca.id =  a.id_adicional_categoria\n      where r.id_resolutorio in (371) and r.principal is true\n\t  \t\t    and (m.name in ($categoria) or ca.name in ($categnuevas)) \n\t\t\t      and a.id_estatus in (3,4,7,8)\n"
    }
   ]
  },
  {
   "title": "CASOS RECIBIDO ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso =  a.id \n\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\n\twhere b.id_resolutorio in (371) \n\tand (c.name in ($categoria) or ca.name in ($categnuevas)) \n  and b.principal is true\t\n  and a.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "CASOS ATENDIDO ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.category c on c.id =  a.id_extra_categoria\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\nwhere b.id_resolutorio in (371) \nand (c.name in ($categoria) or ca.name in ($categnuevas)) \nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASO POR ATENDER ($categoria)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n((SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.responsable b on b.id_caso =  a.id\r\n\tinner join gestion.category c on c.id =  a.id_extra_categoria\r\n\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\r\n\twhere b.id_resolutorio in (371) \r\n\tand (c.name in ($categoria) or ca.name in ($categnuevas)) \r\n  and b.principal is true\tand a.id_estatus in (3,4,6,7,8))\r\n  -\r\n  (SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso = a.id\r\ninner join gestion.category c on c.id =  a.id_extra_categoria\r\nleft join gestion.category ca on ca.id =  a.id_adicional_categoria\r\nwhere b.id_resolutorio in (371) \r\nand (c.name in ($categoria) or ca.name in ($categnuevas))\r\nand b.principal is true\r\nand a.id_estatus in (6) \r\n)) as total"
    }
   ]
  },
  {
   "title": "NIVEL DE SATISFACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.category c on c.id =  a.id_extra_categoria\n\t\t\tleft join gestion.category ca on ca.id =  a.id_adicional_categoria\n\t\t\twhere  b.id_resolutorio in (371)\n\t\t\tand (c.name in ($categoria) or ca.name in ($categnuevas))\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.sub_categoria b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.extra_categoria c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\twhere \n\t\t\t\t\t\t\t\t\t\t\ta.id_sub_categoria = 7 and a.id_extra_categoria = 25\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (597,563,566)\n\t\t\t\t\t\t\t\t\t\t\tand d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.sub_categoria b on b.id = a.id_sub_categoria\ninner join gestion.extra_categoria c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso \nwhere \na.id_sub_categoria = 7 and a.id_extra_categoria = 25\nand e.id_resolutorio in (597,563,566)\nand d.active = 1 and d.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.sub_categoria b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.extra_categoria c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\twhere \n\t\t\t\t\t\t\t\t\t\t\ta.id_sub_categoria = 7 and a.id_extra_categoria = 31\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (597,563,566)\n\t\t\t\t\t\t\t\t\t\t\tand d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.sub_categoria b on b.id = a.id_sub_categoria\ninner join gestion.extra_categoria c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso \nwhere \na.id_sub_categoria = 7 and a.id_extra_categoria = 31\nand e.id_resolutorio in (597,563,566)\nand d.active = 1 and d.id_estatus in (6)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.sub_categoria b on b.id = a.id_sub_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.extra_categoria c on c.id = a.id_extra_categoria\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\twhere \n\t\t\t\t\t\t\t\t\t\t\ta.id_sub_categoria = 7 and a.id_extra_categoria = 27\n\t\t\t\t\t\t\t\t\t\t\tand e.id_resolutorio in (597,563,566)\n\t\t\t\t\t\t\t\t\t\t\tand d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.sub_categoria b on b.id = a.id_sub_categoria\ninner join gestion.extra_categoria c on c.id = a.id_extra_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso \nwhere \na.id_sub_categoria = 7 and a.id_extra_categoria = 27\nand e.id_resolutorio in (597,563,566)\nand d.active = 1 and d.id_estatus in (6)"
    }
   ]
  }
 ]
}