{
 "title": "Cartelera Telecomunicaciones",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estatuscasos",
    "label": "Estatus de los Casos",
    "query": "SELECT nombre FROM gestion.estatus where id in (3,4,6,8)"
   }
  ]
 },
 "panels": [
  {
   "title": "REPORTE GENERAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS-REVISIÓN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n    inner join gestion.category c on c.id = a.id_sub_categoria\r\n    where a.id_sub_categoria in (9)\r\n    and a.id_estatus in (1,2)"
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404) \nand b.principal is true\nand a.id_estatus in (3,4,8)"
      }
     ]
    },
    {
     "title": "BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404) \nand b.principal is true\nand a.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDO -VALOR",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id \nwhere b.id_resolutorio in (371,374,404) \nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (371,374,404)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8) )::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id \nwhere b.id_resolutorio in (371,374,404) \nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "TOTAL CASOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404) \nand b.principal is true\nand a.id_estatus in (3,4,6,8) \n"
      }
     ]
    },
    {
     "title": "CANTV-CASOS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371) \nand b.principal is true\nand a.id_estatus in (3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "CANTV-PROCESO",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (371) \nand b.principal is true\nand a.id_estatus in (3,4,7,8)"
      }
     ]
    },
    {
     "title": "BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (371) \nand b.principal is true\nand a.id_estatus in (6) \nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDO -VALOR",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (371) \nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "SATISFACCIÓN CANTV",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\twhere  b.id_resolutorio in (371)\n\t\t\tand a.feedback is not null\t"
      }
     ]
    },
    {
     "title": "CANTV %",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.responsable b on b.id_caso =  a.id\n                                            where b.id_resolutorio in (371) \n                                            and b.principal is true\n                                            and a.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (371) \nand b.principal is true\nand a.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "MOVILNET-CASOS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (374) \nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
      }
     ]
    },
    {
     "title": "MOVILNET-PROCESO",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\nwhere b.id_resolutorio in (374) \nand b.principal is true\nand a.id_estatus in (3,4,7,8)"
      }
     ]
    },
    {
     "title": "BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (374)\nand b.principal is true\nand a.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDO -VALOR",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (374)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "SATISFACCIÓN MOVILNET",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\twhere  b.id_resolutorio in (374)\n\t\t\tand a.feedback is not null\t"
      }
     ]
    },
    {
     "title": "MOVILNET %",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (374)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (374)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "CONATEL-CASOS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (404)\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
      }
     ]
    },
    {
     "title": "CONATEL-PROCESO",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (404)\nand b.principal is true\nand a.id_estatus in (3,4,7,8)"
      }
     ]
    },
    {
     "title": "BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (404)\nand b.principal is true\nand a.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDO -VALOR",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (404)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "SATISFACCIÓN CONATEL",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\twhere  b.id_resolutorio in (404)\n\t\t\tand a.feedback is not null\t"
      }
     ]
    },
    {
     "title": "CONATEL %",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (404)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (404)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t where  a.id_sub_categoria in (9) and a.id_estatus in (1,2,3,4,6,7,8)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDO",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t where  a.id_sub_categoria in (9) and a.id_estatus in (6)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 19 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select  to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'YYYY-mm-dd') as fechao,\n\tcount(a.fecha) as total\n    from gestion.caso a\n\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)  \n\tand a.id_sub_categoria in (9) \n\tand a.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham, fechao\n        order by fechao"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE-CASOS-DATALLADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SET CLIENT_ENCODING TO 'UTF8';\nSELECT a.nombre::Text \"CANTV\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \te.telefono_alt::Text \"TELEFONO ALT\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n    \ta.titulo::Text \"ASUNTO\", \n    \ta.telefono_suscrip::Text \"TELEF./NUMERO SUSCRIP\",\n    \ta.descripcion::TEXT \"DESCRIP\", \n\t  \tf.name::Text \"CATEGORIA\",\n\t  \tg.name::Text \"SUBCATEG\",\n\t  \ta.fecha::Text \"FECHA CREACION\",\n\t  \ta.fecha_registro::Text \"FECHA STATUS\", \n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n\t\ti.nombre::Text \"ESTATUS\",\n\t\tk.nombre::Text \"RESPONSABLE\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            left join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n      where  j.id_resolutorio in (371)\n      and j.principal is true\n      and i.nombre in ($estatuscasos)\n      and a.id_estatus in (3,4,6,8)\n      and $__timeFilter(a.fecha_registro)"
      },
      {
       "rawSql": "SET CLIENT_ENCODING TO 'UTF8';\nSELECT a.nombre::Text \"MOVILNET\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono_alt::Text \"TELEFONO ALT\",\n    \te.telefono::Text \"TELEFONO\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n    \ta.titulo::Text \"ASUNTO\",\n    \ta.telefono_suscrip::Text \"TELEF./NUMERO SUSCRIP\",\n    \ta.descripcion::TEXT \"DESCRIP\", \n\t  \tf.name::Text \"CATEGORIA\",\n\t  \tg.name::Text \"SUBCATEG\",\n\t  \ta.fecha::Text \"FECHA CREACION\",\n\t  \ta.fecha_registro::Text \"FECHA STATUS\", \n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n\t\ti.nombre::Text \"ESTATUS\",\n\t\tk.nombre::Text \"RESPONSABLE\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            left join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n      where  j.id_resolutorio in (374)\n      and j.principal is true\n      and i.nombre in ($estatuscasos)\n      and a.id_estatus in (3,4,6,8)\n      and $__timeFilter(a.fecha_registro)"
      },
      {
       "rawSql": "SET CLIENT_ENCODING TO 'UTF8';\nSELECT a.nombre::Text \"CONATEL\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono_alt::Text \"TELEFONO ALT\",\n    \te.telefono::Text \"TELEFONO\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n    \ta.titulo::Text \"ASUNTO\",\n    \ta.telefono_suscrip::Text \"TELEF./NUMERO SUSCRIP\",\n    \ta.descripcion::TEXT \"DESCRIP\", \n\t  \tf.name::Text \"CATEGORIA\",\n\t  \tg.name::Text \"SUBCATEG\",\n\t  \ta.fecha::Text \"FECHA CREACION\",\n\t  \ta.fecha_registro::Text \"FECHA STATUS\", \n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n\t\ti.nombre::Text \"ESTATUS\",\n\t\tk.nombre::Text \"RESPONSABLE\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            left join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\n      where  j.id_resolutorio in (404)\n      and j.principal is true\n      and i.nombre in ($estatuscasos)\n      and a.id_estatus in (3,4,6,8)\n      and $__timeFilter(a.fecha_registro)"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE-DETALLADO-ESTADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS CANTV\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (563) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (4) \nand b.id < 25 and  e.id_resolutorio in (371)\nand e.principal is true\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      },
      {
       "rawSql": "select b.nombre::Text \"ESTADOS MOVILNET\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (566) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (4) \nand b.id < 25 and  e.id_resolutorio in (374)\nand e.principal is true --and z.nombre in ($gobernaciones)\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      },
      {
       "rawSql": "select b.nombre::Text \"ESTADOS CONATEL\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (597) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (4) \nand b.id < 25 and  e.id_resolutorio in (404)\nand e.principal is true --and z.nombre in ($gobernaciones)\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  }
 ]
}