{
 "title": "Cartelera PDVSA GAS",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "LISTADO DE CASOS  DE PDVSA GAS EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT a.nombre::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\",\r\n    \te.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\",\r\n    \tb.nombre::Text \"ESTADO\",\r\n    \tc.nombre::Text \"MUNICIPIO\",\r\n    \td.nombre::Text \"PARROQ\",\r\n    \ta.direccion::Text \"DIR\",\r\n    \ta.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\",\r\n\t  \tg.name::Text \"SUBCATEG\",\r\n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\ti.nombre::Text \"ESTATUS\",\r\n\t\tto_char(a.fecha, 'dd-mm-YY  hh:mm:ss')::Text \"FECHA\",\r\n\t\t--to_char(h.fecha_registro,'dd-mm-YY hh:mm:ss') as \"FECHA ESTATUS\",\r\n       case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n\t\tk.nombre::Text \"RESPONSABLE\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\r\n      where  j.id_resolutorio in (503)\r\n      and j.principal is true\r\n      and a.id_estatus in (3,4,8)"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE - DETALLADO - ESTADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\r\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\r\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (503) AND (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.responsable e on e.id_caso =  a.id\r\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\ninner join gestion.estado b on b.id = a.id_estado\r\nwhere a.id_estatus in (3,4,6,8)\r\nand z.id_tipo_resolutorio in (4) \r\nand b.id < 25 and  e.id_resolutorio in (503)\r\nand e.principal is true --and z.nombre in ($gobernaciones)\r\ngroup by b.nombre\r\nHAVING count(*) > 1\r\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE PDVSA GAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id \r\nwhere b.id_resolutorio in (503) \r\nand b.principal is true\r\nand a.id_estatus in (3,4,6,8)"
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n    inner join gestion.category c on c.id = a.id_sub_categoria\r\n    where a.id_sub_categoria in (4)\r\n    and a.id_estatus in (5) "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 3 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\r\n SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n    inner join gestion.category c on c.id = a.id_sub_categoria \r\n    where a.id_sub_categoria in (4)\r\n    and a.id_estatus in (15) "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\nwhere b.id_resolutorio in (503)\r\nand b.principal is true\r\nand a.id_estatus in (3,4,8)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\nwhere b.id_resolutorio in (503)\r\nand b.principal is true\r\nand a.id_estatus in (6)\r\nand a.verificado is null \r\nand (a.feedback < 2 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\nwhere b.id_resolutorio in (503)\r\nand b.principal is true\r\nand a.id_estatus in (6)\r\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\r\n                                           FROM gestion.caso a\r\n                                           inner join gestion.responsable b on b.id_caso =  a.id\r\n                                           where b.id_resolutorio in (503)\r\n                                           and b.principal is true\r\n                                           and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\nwhere b.id_resolutorio in (503)\r\nand b.principal is true\r\nand a.id_estatus in (6)\r\nand (a.feedback >= 2   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\r\nselect to_char(a.fecha, 'dd-mm-YY') as fecham, to_char(a.fecha, 'mm-dd') as fechaa, count(a.fecha) as total\r\n    \tfrom gestion.caso a \r\n    \t\tinner join gestion.responsable b on b.id_caso = a.id\r\n    \t \tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\twhere a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL) --and c.id_sub_categoria in (1)\r\n\t  and b.id_resolutorio in (503) \r\n\t\tand a.id_estatus in (1,2,3,4,6,8)\r\n        group by fecham , fechaa\r\n        order by fechaa"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\r\nselect \r\n\tb.nombre as estado, count(a.id) as total\r\n    from gestion.caso a\r\n\t inner join gestion.estado b on b.id = a.id_estado \r\n\t inner join gestion.responsable d on d.id_caso = a.id\r\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\r\n\t where  d.id_resolutorio in (503) \r\n\t and a.id_estatus in (1,2,3,4,6,8)\r\n    group by estado\r\n    order by total desc\r\n    Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\r\nselect \r\n\tb.nombre as estado, count(a.id) as total\r\n    from gestion.caso a\r\n\t inner join gestion.estado b on b.id = a.id_estado  \r\n\t inner join gestion.responsable d on d.id_caso = a.id\r\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\r\n\t where  d.id_resolutorio in (503) \r\n\t and a.id_estatus in (6)\r\n    group by estado\r\n    order by total desc\r\n    Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CATEGORÍAS PDVSA GAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE PDVSA GAS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select count(a.id) as TOTAL\r\n\tfrom gestion.caso a\r\n\t  inner join gestion.responsable c on c.id_caso = a.id\r\n\t  where a.id_sub_categoria in (4) \r\n\t        and a.id_estatus in (3,4,6,8)\r\n\t\t      and c.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (PDVSA GAS)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\r\n                from gestion.caso a\r\n\t\t\t\tinner join gestion.responsable d on d.id_caso = a.id\r\n            where a.id_sub_categoria in (4) and \r\n                a.id_estatus in (1,2,3,4,6,8)\r\n\t\t\t\t        and a.id_extra_categoria is not null\r\n\t\t\t\t        and d.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (PDVSA GAS)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select count(*) as TOTAL\n      from gestion.caso a \n\t\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n      where a.id_sub_categoria in (4) and \n            a.id_estatus in (1,2,3,4,6,8) and a.id_extra_categoria is null\n\t\t\t\t    and b.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  PDVSA GAS)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n                inner join gestion.category c on c.id = a.id_sub_categoria \r\n\t\t\t\t        inner join gestion.responsable b on b.id_caso = a.id\r\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria   \r\n            where a.id_sub_categoria in (4) and \r\n\t\t\t   a.id_estatus in (1,2,3,4,6,8) \r\n\t\t\t   and b.id_resolutorio in (503)\r\n            GROUP BY sub_categoria\r\n            ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE PDVSA GAS DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "  SELECT i.nombre as estatus, count(a.id) as subtotal,\r\n            (SELECT count(a.id) FROM gestion.caso a\r\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n    \t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula \r\n    \t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n    \t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\r\n    \t\t\t\t\twhere a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (7)\r\n    \t\t\t\t\tand c.id_resolutorio in (503))::Text \"Total\"\r\n      FROM gestion.caso a\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join lista.ubch z on z.cedula = e.cedula \r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\r\n         where a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (7)\r\n\t\t and c.id_resolutorio in (503)\r\n         group by estatus"
      }
     ]
    },
    {
     "title": "REVISIÓN-UBCH",
     "type": "gauge",
     "description": "Total de casos generados",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\r\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula \r\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\r\n\t\t\t\t\twhere a.id_estatus in (3,4,6,8) --and a.id_sub_categoria in (1)\r\n\t\t\t\t\tand c.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\r\n        SELECT count(a.id) FROM gestion.caso a\r\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\r\n\t\t\t\t\twhere a.id_estatus in (3,4,8) --and a.id_sub_categoria in (1)\r\n\t\t\t\t\tand c.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "ATENDIDOS - UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\r\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id\r\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\r\n\t\t\t\t\twhere a.id_estatus in (6) --and a.id_sub_categoria in (1)\r\n\t\t\t\t\tand c.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n                inner join gestion.category c on c.id = a.id_sub_categoria  \r\n                inner join gestion.denunciante e on e.id = a.id_denunciante\r\n                inner join lista.ubch z on z.cedula = e.cedula \r\n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\r\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \r\n            where a.id_estatus in (1,2,3,4,6,8)\r\n\t\t\tand b.id_resolutorio in (503)\r\n            GROUP BY sub_categoria\r\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS ATENDIDOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n                inner join gestion.category c on c.id = a.id_sub_categoria \r\n                inner join gestion.denunciante e on e.id = a.id_denunciante\r\n                inner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\r\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \r\n            where a.id_estatus in (6)\r\n\t\t\tand b.id_resolutorio in (503)\r\n            GROUP BY sub_categoria\r\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\r\n  from gestion.caso a\r\n\t          inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\r\n\t where  a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (1)\r\n\t\t\tand c.id_resolutorio in (503)\r\n            group by estado order by total desc Limit 10;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES-CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\r\n  from gestion.caso a\r\n\t          inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\r\n\t where  a.id_estatus in (6) --and a.id_sub_categoria in (1)\r\n\t\t\tand c.id_resolutorio in (503)\r\n            group by estado order by total desc Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE PDVSA GAS DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \r\n      --a.codigo::Text \"CODIGO CASO\",\r\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n            case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n            case when w.username is null then 'Analizando' else (w.first_name || ' ' || w.last_name) end::Text \"RESPONSABLE\",\r\n\t\t\tw.phone::Text \"TELF. RESP\"\r\n            FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t      inner join lista.ubch z on z.cedula = e.cedula\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id --and j.id_user is not null\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\r\n            where a.id_estatus in (1,2,3,4,6,8) --and a.id_sub_categoria in (7)\r\n            and j.id_resolutorio in (503);"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE PDVSA GAS POR ENTIDADES FEDERALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS  EN PROCESO DE PDVSA GAS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\r\n\t  FROM gestion.caso a \r\n    inner join gestion.responsable b on b.id_caso = a.id\r\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n    where b.id_resolutorio in (503) \r\n\t  --c.id_sub_categoria in (1)\r\n    and a.id_estatus in (3,4,8) "
      }
     ]
    },
    {
     "title": "CASOS  ATENDIDOS DE PDVSA GAS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  SELECT count(a.id)\r\n\t  FROM gestion.caso a \r\n\t  inner join gestion.responsable b on b.id_caso = a.id\r\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n    where b.id_resolutorio in (503) \r\n\t  --c.id_sub_categoria in (1)\r\n    and a.id_estatus in (6) "
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select \r\n\tb.nombre as estado, count(a.id) as total\r\n    from gestion.caso a\r\n\t inner join gestion.estado b on b.id = a.id_estado \r\n\t inner join gestion.responsable d on d.id_caso = a.id\r\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\r\n\t where  d.id_resolutorio in (503) \r\n\t and a.id_estatus in (3,4,8)\r\n    group by estado\r\n    order by total desc;"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "        select \r\n\tb.nombre as estado, count(a.id) as total\r\n    from gestion.caso a\r\n\t inner join gestion.estado b on b.id = a.id_estado  \r\n\t inner join gestion.responsable d on d.id_caso = a.id\r\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\r\n\t where  d.id_resolutorio in (503) \r\n\t and a.id_estatus in (6)\r\n    group by estado\r\n    order by total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS DE UBCH RECIBIDOS-ATENDIDOS (POR ENTIDADES  FEDERALES) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE PDVSA GAS DE UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select \r\n            b.nombre::Text \"ESTADO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado \r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\tinner join gestion.responsable c on c.id_caso = a.id\r\n       \twhere  a.id_estatus in (1,2,3,4,6,8)\r\n\t\t\tand c.id_resolutorio in (503)\r\n        group by b.nombre order by TOTAL desc"
      }
     ]
    },
    {
     "title": "TOTAL CASOS DE PDVSA GAS ATENDIDOS DE  UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select \r\n            b.nombre::Text \"ESTADO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join lista.ubch z on z.cedula = e.cedula\r\n\t\t\tinner join gestion.responsable c on c.id_caso = a.id\r\n       \twhere a.id_estatus in (6)\r\n\t\t\tand c.id_resolutorio in (503)\r\n        group by b.nombre\r\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS RECIBIDOS-ATENDIDOS POR MUNICIPIOS(CAPITALES DE ENTIDADES FEDERALES )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE PDVSA GAS POR MUN. CAPITALES",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio \r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n    where --a.id_sub_categoria in (7)and \r\n    a.id_estatus in (1,2,3,4,6,8) \r\n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\r\n\tand e.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS  - PDVSA GAS (MUN. CAPITALES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n    where --a.id_sub_categoria in (7) and \r\n    a.id_estatus in (6) \r\n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\r\n\tand e.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "CASOS DE PDVSA GAS POR MUN. CAPITALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select \r\n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio  \r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n       where --a.id_sub_categoria in (1) and\r\n       a.id_estatus in (1,2,3,4,6,8)\r\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\r\n\t   and e.id_resolutorio in (503)\r\n        group by c.nombre, b.nombre\r\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS - PDVSA GAS (MUN. CAPITALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "        select \r\n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n       where --a.id_sub_categoria in (1) and \r\n       a.id_estatus in (6)\r\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\r\n\t   and e.id_resolutorio in (503)\r\n        group by c.nombre, b.nombre\r\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS RECIBIDOS-ATENDIDOS DE OTROS MUNICIPIOS  (CIUDADES IMPORTANTES)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS -  PDVSA GAS  (CIUDADES IMPORTANTES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n    where --a.id_sub_categoria in (7) and \r\n    a.id_estatus in (1,2,3,4,6,8) \r\n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \r\n\tand e.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS - PDVSA GAS  (CD. IMPORTANTE)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n    where --a.id_sub_categoria in (7) and \r\n    a.id_estatus in (6) \r\n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \r\n\tand e.id_resolutorio in (503)"
      }
     ]
    },
    {
     "title": "CASOS - PDVSA GAS (CIUDADES IMPORTANTES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n     where --a.id_sub_categoria in (7) and \r\n        a.id_estatus in (1,2,3,4,6,8)\r\n       and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \r\n\t   and e.id_resolutorio in (503)\r\n       group by c.nombre, b.nombre\r\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS - PDVSA GAS (CD. IMPORTANTE)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n     where a.id_sub_categoria in (4) and a.id_estatus in (6)\r\n      and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \r\n\t   and e.id_resolutorio in (503)\r\n       group by c.nombre, b.nombre\r\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE PDVSA GAS RECIBIDOS-ATENDIDOS  POR ENTIDADES PARROQUIALES (50 PRIMERAS PARROQUIAS) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia \n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n     where --a.id_sub_categoria in (7) and \n        a.id_estatus in (1,2,3,4,6,8)\n\t  \t\tand e.id_resolutorio in (503)\n       group by c.nombre, b.nombre\n        order by TOTAL desc limit 50\n    "
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 11, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \r\n            count(a.id) as TOTAL\r\n            from gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.parroquia c on c.id = a.id_parroquia \r\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n     where --a.id_sub_categoria in (7) and \r\n        a.id_estatus in (6)\r\n\t  \t\tand e.id_resolutorio in (503)\r\n       group by c.nombre, b.nombre\r\n        order by TOTAL desc limit 50"
      }
     ]
    }
   ]
  }
 ]
}