{
 "title": "GAS COMUNAL Y GAS DIRECTO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estatus",
    "label": "ESTATUS",
    "query": "SELECT nombre FROM gestion.estatus Where id in (3,4,6,8)"
   }
  ]
 },
 "panels": [
  {
   "title": "LISTADOS DE CASOS DETALLADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT a.nombre::Text \"CODIGO CASO\",\r\n    \te.cedula::Text \"CEDULA\",\r\n    \te.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\",\r\n    \tb.nombre::Text \"ESTADO\",\r\n    \tc.nombre::Text \"MUNICIPIO\",\r\n    \td.nombre::Text \"PARROQ\",\r\n    \ta.direccion::Text \"DIR\",\r\n    \ta.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\",\r\n\t  \tg.name::Text \"SUBCATEG\",\r\n\t  \tk.nombre::Text \"RESOLUTOR\",\r\n\t  \tcase when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\ti.nombre::Text \"ESTATUS\",\r\n\t\tto_char(a.fecha, 'dd-mm-YY  hh:mm:ss')::Text \"FECHA\",\r\n\t\tto_char(a.fecha_registro,'dd-mm-YY hh:mm:ss') as \"FECHA ESTATUS\",\r\n       case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n\t\tk.nombre::Text \"RESPONSABLE\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            inner JOIN  gestion.estatus i ON a.id_estatus = i.id            \r\n            inner JOIN  gestion.responsable j ON j.id_caso = a.id\r\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio\r\n      where  j.id_resolutorio in (359,406)\r\n      and j.principal is true\r\n      and i.nombre in ($estatus)"
      }
     ]
    }
   ]
  },
  { "title": "REPORTE GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CASOS EN EL SISTEMA GAS DIRECTO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\nwhere b.id_resolutorio in (359) \r\nand b.principal is true\r\nand a.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "ASIGNADO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (359)\nand b.principal is true\nand a.id_estatus in (3)"
    }
   ]
  },
  {
   "title": "EN PROCESO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (359)\nand b.principal is true\nand a.id_estatus in (4,8)"
    }
   ]
  },
  {
   "title": "POR CONFIRMAR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (359)\nand b.principal is true\nand a.id_estatus in (6)\nAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))\n"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (359)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "PORCENTAJE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (359)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (359)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASOS EN EL SISTEMA GAS COMUNAL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.responsable b on b.id_caso =  a.id\r\nwhere b.id_resolutorio in (406) \r\nand b.principal is true\r\nand a.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "ASIGNADO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (3)"
    }
   ]
  },
  {
   "title": "EN PROCESO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (4,8)"
    }
   ]
  },
  {
   "title": "POR CONFIRMAR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (6)\nAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "PORCENTAJE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (406)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (406)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "DETALLE POR ESTADOS  - GAS COMUNAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS GAS COMUNAL",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (599) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (4) \nand b.id < 25 and  e.id_resolutorio in (406)\nand e.principal is true --and z.nombre in ($gobernaciones)\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  },
  {
   "title": "DETALLE POR ESTADOS - GAS DIRECTO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\nsum(CASE WHEN a.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN a.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN a.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN a.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN a.id_estatus in (6) and z.id_tipo_resolutorio in (4) and  e.id_resolutorio in (503) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  a.id\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  a.id_estatus in (3,4,6,8)\nand z.id_tipo_resolutorio in (4) \nand b.id < 25 and  e.id_resolutorio in (359)\nand e.principal is true\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  }
 ]
}