{
 "title": "Cartelera CONATEL",
 "time": { "from": "2021-01-01T04:00:00.000Z", "to": "2025-01-02T03:59:59.000Z" },
 "panels": [
  {
   "title": "LISTADO DE CASOS  DE CONATEL EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT --DISTINCT ON (a.id) a.id::Text \"CODIGO CASOS\", \r\n      a.nombre::Text \"CODIGO CASO\", \r\n      e.cedula::Text \"CEDULA\", \r\n      e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", \r\n\t\t\tb.nombre::Text \"ESTADO\", \r\n\t\t\tc.nombre::Text \"MUNICIPIO\", \r\n\t\t\td.nombre::Text \"PARROQ\", \r\n\t\t\ta.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", \r\n\t\t\tg.name::Text \"SUBCATEG\",\r\n\t    case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n\t\t\tto_char(a.fecha, 'dd-mm-YY')::Text \"FECHA\",\r\n      case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n      k.nombre::Text \"RESPONSABLE\"\r\n            FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            left JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id and j.id_user is not null\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n           -- LEFT JOIN  public.user_detail v ON w.id = v.user_id\r\n            where a.id_estatus in (3,4,8) \r\n            and j.id_resolutorio in (371,374,404) \r\n            order by a.id desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE CONATEL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (7)"
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (7)\n    and a.id_estatus in (5) "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (1)\n    and a.id_estatus in (15) "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    where a.id_sub_categoria in (7)\n    and a.id_estatus in (1,2,3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404)\nand b.principal is true\nand a.id_estatus in (3,4,6,7,8)"
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404)\nand b.principal is true\nand a.id_estatus in (3,4,7,8)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404)\nand b.principal is true\nand a.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.responsable b on b.id_caso =  a.id\n                                           where b.id_resolutorio in (371,374,404)\n                                           and b.principal is true\n                                           and a.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso =  a.id\nwhere b.id_resolutorio in (371,374,404)\nand b.principal is true\nand a.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\nselect to_char(a.fecha, 'mm-dd') as fecham, count(a.fecha) as total\n    \tfrom gestion.caso a\n    \t\tinner join gestion.responsable b on b.id_caso = a.id\n    \t \tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t      where a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)\n\t      and b.id_resolutorio in (371,374,404) \n\t\t    and a.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham \n        order by fecham"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t  inner join gestion.estado b on b.id = a.id_estado\n\t  inner join gestion.responsable d on d.id_caso = a.id\n\t  inner join gestion.resolutorio e on e.id = d.id_resolutorio\n  \twhere  d.id_resolutorio in (371,374,404) \n\t  and a.id_estatus in (1,2,3,4,6,7,8)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t inner join gestion.responsable d on d.id_caso = a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (371,374,404) \n\t and a.id_estatus in (6)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CATEGORÍAS TELECOM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE TELECOM",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select count(a.id) as TOTAL\n\tfrom gestion.caso a\n\t  inner join gestion.responsable c on c.id_caso = a.id\n\t  where a.id_estatus in (3,4,6,7,8)\n\t\t      and c.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (TELECOM)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as TOTAL\n        from gestion.caso a\n\t\t\t\tinner join gestion.responsable d on d.id_caso = a.id\n            where a.id_estatus in (1,2,3,4,6,7,8)\n\t\t\t\t        and a.id_extra_categoria is not null\n\t\t\t\t        and d.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (TELECOM)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select count(*) as TOTAL\n      from gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n      where a.id_estatus in (1,2,3,4,6,7,8) and a.id_extra_categoria is null\n\t\t\tand b.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  TELECOM)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": " SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t     FROM gestion.caso a \n        inner join gestion.category c on c.id = a.id_sub_categoria \n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n        left join gestion.category m ON m.id = a.id_extra_categoria   \n        where a.id_estatus in (1,2,3,4,6,7,8) \n\t\t\t  and b.id_resolutorio in (371,374,404)\n        GROUP BY sub_categoria\n        ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE CONATEL DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "  SELECT i.nombre as estatus, count(a.id) as subtotal,\n            (SELECT count(a.id) FROM gestion.caso a\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n    \t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n    \t\t\t\t\tinner join gestion.estatus i ON a.id_estatus = i.id\n    \t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n    \t\t\t\t\twhere a.id_estatus in (1,2,3,4,6,7,8)\n    \t\t\t\t\tand c.id_resolutorio in (371,374,404))::Text \"Total\"\n      FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n         where a.id_estatus in (1,2,3,4,6,7,8) and c.id_resolutorio in (371,374,404)\n         group by estatus"
      }
     ]
    },
    {
     "title": "REVISIÓN-UBCH",
     "type": "gauge",
     "description": "Total de casos generados",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "targets": [
      {
       "rawSql": "         SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere a.id_estatus in (3,4,6,7,8)\n\t\t\t\t\tand c.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere a.id_estatus in (3,4,7,8)\n\t\t\t\t\tand c.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "ATENDIDOS-UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner JOIN gestion.estatus i ON a.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere a.id_estatus in (6)\n\t\t\t\t\tand c.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n           inner join gestion.category c on c.id = a.id_sub_categoria  \n           inner join gestion.denunciante e on e.id = a.id_denunciante\n           inner join lista.ubch z on z.cedula = e.cedula \n\t\t\t     inner join gestion.responsable b on b.id_caso = a.id\n           LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n           where a.id_estatus in (1,2,3,4,6,8)\n\t\t\t     and b.id_resolutorio in (371,374,404)\n           GROUP BY sub_categoria\n           ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS ATENDIDOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n           inner join gestion.category c on c.id = a.id_sub_categoria \n           inner join gestion.denunciante e on e.id = a.id_denunciante\n           inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t   inner join gestion.responsable b on b.id_caso = a.id\n           LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n           where a.id_estatus in (6)\n\t\t\t     and b.id_resolutorio in (371,374,404)\n           GROUP BY sub_categoria\n           ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\r\n  from gestion.caso a\r\n\tinner join gestion.estado b on b.id = a.id_estado\r\n  inner join gestion.denunciante e on e.id = a.id_denunciante\r\n  inner join lista.ubch z on z.cedula = e.cedula --ACTIVAR CUANDO EL PERSONAL DE YSRAEL SUBAN ESA TABLA A LA ORGANIZACION Lista\r\n\tinner join gestion.responsable c on c.id_caso = a.id\r\n\twhere  a.id_estatus in (1,2,3,4,6,8)\r\n\tand c.id_resolutorio in (371,374,404)\r\n  group by estado order by total desc Limit 10;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES-CASOS RESUELTOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t  inner join gestion.estado b on b.id = a.id_estado\n    inner join gestion.denunciante e on e.id = a.id_denunciante\n    inner join lista.ubch z on z.cedula = e.cedula\n\t\tinner join gestion.responsable c on c.id_caso = a.id\n\t  where  a.id_estatus in (6)\n\t\tand c.id_resolutorio in (371,374,404)\n    group by estado order by total desc Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE CONATEL DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \n      --a.codigo::Text \"CODIGO CASO\",\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n            case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\n\t\t\ti.nombre::Text \"ESTATUS\",\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\n            case when w.username is null then 'Analizando' else (w.first_name || ' ' || w.last_name) end::Text \"RESPONSABLE\",\n\t\t\tw.phone::Text \"TELF. RESP\"\n            FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      inner join lista.ubch z on z.cedula = e.cedula\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.estatus i ON a.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id \n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\n            where a.id_estatus in (1,2,3,4,6,8)\n            and j.id_resolutorio in (371,374,404);"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE CONATEL POR ENTIDADES FEDERALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS  EN PROCESO",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.responsable b on b.id_caso = a.id\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (371,374,404)\n    and a.id_estatus in (3,4,7,8) "
      }
     ]
    },
    {
     "title": "CASOS  ATENDIDOS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  SELECT count(a.id)\n\t  FROM gestion.caso a\n\t  inner join gestion.responsable b on b.id_caso = a.id\n\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (371,374,404) \n    and a.id_estatus in (6) "
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n     from gestion.caso a\n  \t inner join gestion.estado b on b.id = a.id_estado\n  \t inner join gestion.responsable d on d.id_caso = a.id\n  \t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n  \t where  d.id_resolutorio in (371,374,404)\n  \t and a.id_estatus in (3,4,7,8)\n     group by estado\n     order by total desc;"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n   from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n\t inner join gestion.responsable d on d.id_caso = a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (371,374,404)\n\t and a.id_estatus in (6)\n    group by estado\n    order by total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE CONATEL DE UBCH RECIBIDOS-ATENDIDOS (POR ENTIDADES  FEDERALES) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS  DE UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n       \twhere a.id_estatus in (1,2,3,4,6,7,8)\n\t\t\t  and c.id_resolutorio in (371,374,404)\n        group by b.nombre \n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "TOTAL CASOS  ATENDIDOS DE  UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n       \twhere a.id_estatus in (6)\n\t\t\t  and c.id_resolutorio in (371,374,404)\n        group by b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE CONATEL RECIBIDOS-ATENDIDOS POR MUNICIPIOS(CAPITALES DE ENTIDADES FEDERALES )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS  POR MUN. CAPITALES",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\tand e.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS  (MUN. CAPITALES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (6) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t  and e.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "CASOS POR MUN. CAPITALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t      \tinner join gestion.responsable e on e.id_caso = a.id\n        where a.id_estatus in (1,2,3,4,6,7,8)\n        and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t      and e.id_resolutorio in (371,374,404)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS  (MUN. CAPITALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n       where a.id_estatus in (6)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t     and e.id_resolutorio in (371,374,404)\n       group by c.nombre, b.nombre\n       order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE CONATEL RECIBIDOS-ATENDIDOS DE OTROS MUNICIPIOS  (CIUDADES IMPORTANTES)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS  (CIUDADES IMPORTANTES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t        inner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t  and e.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS  (CD. IMPORTANTE)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n    where a.id_estatus in (6) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t  and e.id_resolutorio in (371,374,404)"
      }
     ]
    },
    {
     "title": "CASOS  (CIUDADES IMPORTANTES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t      \tinner join gestion.responsable e on e.id_caso = a.id\n            where a.id_estatus in (1,2,3,4,6,7,8)\n            and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t          and e.id_resolutorio in (371,374,404)\n            group by c.nombre, b.nombre\n            order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS (CD. IMPORTANTE)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n            where a.id_estatus in (6)\n            and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n      \t    and e.id_resolutorio in (371,374,404)\n            group by c.nombre, b.nombre\n            order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS RECIBIDOS-ATENDIDOS  POR ENTIDADES PARROQUIALES (50 PRIMERAS PARROQUIAS) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n            where a.id_estatus in (1,2,3,4,6,7,8)\n\t  \t\t    and e.id_resolutorio in (371,374,404)\n            group by c.nombre, b.nombre\n            order by TOTAL desc limit 50"
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 11, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n\t\t\t      inner join gestion.responsable e on e.id_caso = a.id\n            where a.id_estatus in (6)\n\t  \t\t    and e.id_resolutorio in (371,374,404)\n            group by c.nombre, b.nombre\n            order by TOTAL desc limit 50"
      }
     ]
    }
   ]
  }
 ]
}