{
 "title": "BUSQUEDA DETALLE DE DENUNCIANTE  1X10  EN CDLP Y PSUV V3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cedula", "label": "CEDULA", "query": "v18424409" }
  ]
 },
 "panels": [
  {
   "title": "DATOS DENUNCIANTE 1X10",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "\nSELECT d.nombre::Text \"Nombres Apellidos\", d.cedula::Text \"Cedula\", d.correo::Text \"Correo\", d.telefono::Text \"Telefono\", \n\t   d.telefono_alt::Text \"Telefono Alt\", p.nombre::Text \"Pueblo Indigena\", c.nombre::Text \"Comunidad Indigena\", \n\t   jefe_comunidad_indigena::Text \"Jefe Comunidad Indigena\"\n\t   FROM gestion.denunciante d\n\tleft join gestion.pueblo_indigena p on d.pueblo_indigena_id = p.id\n\tleft join gestion.comunidad_indigena c on c.id = d.comunidad_indigena_id\n\tleft join lista.ubch u on d.cedula ilike '%u.cedula%' \n\twhere d.cedula ilike '%$cedula%' LIMIT 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<BR>\n<center>\nUBCH\n</center>"
   }
  },
  {
   "title": "ESTRUCTURA UBCH",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT dni::Text \"CEDULA\", fullname::Text \"NOMBRE APELLIDO\", state::Text \"ESTADO\", municipality::Text \"MUNICIPIO\", parish::Text \"PARROQUIA\", ubch::Text \"UBCH\", \n\t\tphone::Text \"TELEFONO\", gender::Text \"GENERO\", cruce_cne::Text \"CNE\"\n\tFROM psuv.ubch_structures \n\tWHERE dni ILIKE '%$cedula%' LIMIT 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<BR>\n<center>\nCARNET DE LA PATRIA \n</center>"
   }
  },
  {
   "title": "FOTO CDLP",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT foto\n  FROM public.partner_card \n  WHERE ci ilike '%$cedula%' limit 1 "
    }
   ]
  },
  {
   "title": "CDLP",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT  p.ci::Text \"Cedula\",  CONCAT(p.name, ' ', p.name2, ' ', p.apellido1, ' ', p.apellido2)::Text \"Nombres Apellidos\", \n      p.fecha_nacimiento::Text \"Fecha Nacimiento\", p.movil1::Text \"Telefono\", s.name::Text \"Estado\", r.name::Text \"Municipio\", z.name::Text \"Parroquia\",\n      CONCAT('Urbanismo: ', p.urbanismo, ', Bloque/Edificio: ', p.bloque, ', Barrio/Sector: ', p.sector_barrio, ', Casa: ', p.casa)::Text \"Direccion\", p.serial_ciudadano::Text \"Num Carnet\"\n  FROM public.partner_card p, res_country_state s, res_city r, res_parish z\n  WHERE \n  p.state_id = s.id\n  and  p.city_id = r.id\n  and z.id =  p.parish_id\n  and p.ci ILIKE '%$cedula%' limit 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<BR>\n<center>\nCARNET PSUV\n</center>"
   }
  },
  {
   "title": "FOTO PSUV",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT foto\n  FROM public.partner_card \n  WHERE ci ILIKE '%$cedula%' limit 1 "
    }
   ]
  },
  {
   "title": "PSUV",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT  p.ci::Text \"Cedula\",  CONCAT(p.name, ' ', p.name2, ' ', p.apellido1, ' ', p.apellido2)::Text \"Nombres Apellidos\", \n      p.fecha_nacimiento::Text \"Fecha Nacimiento\", p.movil1::Text \"Telefono\", s.name::Text \"Estado\", r.name::Text \"Municipio\", \n      p.direccion::Text \"Direccion\",p.serial_ciudadano::Text \"Num Carnet\"\n  FROM public.partner_card p\n  left join res_country_state s on  p.state_id = s.id\n  left join res_city r on p.city_id = r.id\n  WHERE  p.ci ILIKE '%$cedula%' limit 1"
    }
   ]
  }
 ]
}