{
 "title": "CASOS POR CONFIRMAR DONDE EL USUARIO A HECHO UN COMENTARIO V3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rol",
    "label": "ROL USUARIO",
    "query": "SELECT distinct(c.nombre)\nfrom public.rol c \nwhere c.nombre not in ('admin','root','supervisor-especial','resolutor-nacional','resolutor','consulta','user')"
   },
   {
    "name": "operadores",
    "label": "USUARIO OPERADORES",
    "query": "SELECT a.username \nFROM public.\"user\" a\ninner join public.user_rol b ON b.id_usuario = a.id\nINNER join public.rol c ON c.id = b.id_role\nwhere c.nombre in ($rol) and status = 10"
   }
  ]
 },
 "panels": [
  {
   "title": "USUARIOS PCP",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT a.username as \"USUARIOS\", a.first_name || ' ' || a.last_name::TEXT \"NOMBRES APELLIDOS\", \n'(' || a.address || ')'::TEXT \"GRUPO DE TRABAJO\"\nFROM public.\"user\" a\nINNER join public.user_rol b on b.id_usuario = a.id\nwhere --c.item_name in ('operador','operador-nacional') and\na.status = 10\nAND a.username = '$operadores'"
    }
   ]
  },
  {
   "title": "POR CONFIRMAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT a.id)\n\tFROM gestion.caso a\n\tinner join gestion.observacion o on o.id_caso = a.id\n\tinner join public.user u on u.id= o.id_user\n\twhere \n\ta.id_estatus in (6) \n\tand ((a.feedback is null and verificado is null) or (a.feedback < 2.5 and verificado is null))\n\tand u.username =  '$operadores'\n\tand $__timeFilter(a.fecha_registro)\n\n"
    }
   ]
  },
  { "title": "CASOS DETALLADOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CASOS DETALLADO POR CONFIRMAR",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT  DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO\", \n    \t\t  e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n    \t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", \n    \t\t\ta.descripcion::TEXT \"DESCRIP\", g.name::Text \"SUBCATEG\",\n    \t\t\tto_char(a.fecha_registro,'dd-mm-YY hh:mm:ss') as \"FECHA ESTATUS\",\n\t\t\t\t  o.observacion::Text \"OBSERVACIÓN REALIZADA\"\n        \tFROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n           \tinner join gestion.observacion o on o.id_caso = a.id\n\t\t\t      inner join public.user u on u.id= o.id_user\t\t\n            where a.id_estatus in (6)\n\t\t\t\t    and ((a.feedback is null and verificado is null) or (a.feedback < 2.5 and verificado is null))\n            and u.username = '$operadores'\n\t\t\t\t    and $__timeFilter(a.fecha_registro)\n            order by a.nombre, o.id desc;"
    }
   ]
  }
 ]
}