{
 "title": "CORREDOR ELECTORAL PARROQUIAL V3 A LA ESPERA DE ESQUEMA PSUV",
 "time": { "from": "2022-11-02T13:45:10.016Z", "to": "2022-11-02T13:55:10.016Z" },
 "templating": {
  "list": [
   {
    "name": "corredor",
    "label": "Corredor Electoral",
    "query": "SELECT distinct a.corredor\n\tFROM psuv.corredor_electoral_parroquial a"
   },
   {
    "name": "estado",
    "label": "Estado",
    "query": "SELECT distinct estado\n\tFROM psuv.corredor_electoral_parroquial \n\twhere corredor = '$corredor'"
   },
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "SELECT distinct a.municipio\n\tFROM psuv.corredor_electoral_parroquial a\n\twhere a.corredor = '$corredor' and estado  in ($estado) "
   },
   {
    "name": "parroquia",
    "label": "Parroquia",
    "query": "SELECT distinct a.parroquia\n\tFROM psuv.corredor_electoral_parroquial a\n\twhere a.corredor = '$corredor' and a.estado in ($estado)  AND a.municipio in ($municipio)"
   }
  ]
 },
 "panels": [
  {
   "title": "REPORTE GENERAL 1X10 DEL BUEN GOBIERNO ($estado)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT profile_pic\n\tFROM public.user_detail \n\twhere user_id = 3"
    }
   ]
  },
  {
   "title": "RECIBIDOS POR VENAPP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n  inner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado b on b.id = a.id_estado\n\tinner join gestion.municipio c on c.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n  where b.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)\n  AND d.active = 1"
    }
   ]
  },
  {
   "title": "SISTEMA 1X10",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.historico d on d.id_caso = a.id  \n    inner join gestion.estado b on b.id = a.id_estado\n\t  inner join gestion.municipio c on c.id = a.id_municipio\n\t  inner join gestion.parroquia e on e.id = a.id_parroquia\n  where\n    b.nombre in ($estado) AND c.nombre in ($municipio) \n    AND e.nombre in ($parroquia)\n    and d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "DEVUELTO A VENAPP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n  inner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.estado b on b.id = a.id_estado\n\tinner join gestion.municipio c on c.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n  where\n\tb.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tAND d.active = 1 and d.id_estatus in (5) "
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\twhere \n\t\t\t--b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,453,553,561,597,563,566,354,503,599)\n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\t--and a.feedback is not null\t"
    }
   ]
  },
  {
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT profile_pic\n\tFROM public.user_detail \n\twhere user_id = 3"
    }
   ]
  },
  {
   "title": "REVISIÓN 1X10",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\t  FROM gestion.caso a\r\n    inner join gestion.historico d on d.id_caso = a.id  \r\n    inner join gestion.estado b on b.id = a.id_estado\r\n  \tinner join gestion.municipio c on c.id = a.id_municipio\r\n  \tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n    where\r\n    b.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia) and\r\n  \td.active = 1 and d.id_estatus in (1,2) "
    }
   ]
  },
  {
   "title": "ATENDIDOS-MINISTERIOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (3,4)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and d.active = 1 and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDOS-GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (1,2)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and d.active = 1 and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "CASOS-VALORADOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.feedback)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \t\t\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\t\n\t\t\twhere \n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\t--and b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,453,553,561,597,563,566,354,503,599)\n\t\t\tand b.principal is true and d.active = 1 and d.id_estatus in (6) and (a.feedback >= 3   or  a.verificado = 'SI') --and a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "ASIGNADOS MINISTERIOS ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (3,4)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,8) \n"
    }
   ]
  },
  {
   "title": "ASIGNADOS GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (1,2)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "TOTAL ATENDIDOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\twhere c.id_tipo_resolutorio in (1,2,3,4) and\n\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true \n\tand d.active = 1 \n\tand d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL GOB-ALCALDIAS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1,2)\n\t\t\t\t\t\t\t\t\t\t   \tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (1,2)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL  MINISTERIOS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (3,4)\n\t\t\t\t\t\t\t\t\t\t   \t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t  and a.id_sub_categoria in (1,2,3,4,5,6,7,8) and b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\t  and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (3,4)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL ATENDIDOS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1,2,3,4)\n\t\t\t\t\t\t\t\t\t\t   \t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t  and a.id_sub_categoria in (1,2,3,4,5,6,7,8) and b.principal is true and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\t  and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\twhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true\tand d.active = 1 and d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (354)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (553)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "EDUCA-UNIVERS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (561)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (597,563,566)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (599)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (503)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (453)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "GOB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.historico d on d.id_caso = a.id \r\ninner join gestion.responsable b on b.id_caso =  d.id_caso \r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (1)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\nand d.active = 1\r\nand d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.historico d on d.id_caso = a.id \r\ninner join gestion.responsable b on b.id_caso =  d.id_caso \r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (2)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\nand d.active = 1\r\nand d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id \n                                            inner join gestion.responsable b on b.id_caso =  d.id_caso\t\t\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\t\t\t\t\t\t\t\t\t\t\n                                            where b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true and d.active = 1\n                                            and d.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\tand d.active = 1 and d.id_estatus in (6) \n\tand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (354)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (354)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / ( SELECT count(a.id) \n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id\n                                            inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                            inner join gestion.estado f on f.id = a.id_estado\n                                            inner join gestion.municipio g on g.id = a.id_municipio\n                                            inner join gestion.parroquia e on e.id = a.id_parroquia\n                                            where b.id_resolutorio in (553)\n                                            and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true\n                                            and d.active = 1\n                                            and d.id_estatus in (3,4,6,7,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (553)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-UNIVERSI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (561)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (561)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (597,563,566)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (597,563,566)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (599)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (599)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (503)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n                                           and b.principal is true\n                                           and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (503)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc((count(a.id)::decimal * 100) / ( SELECT count(a.id)\n                                              FROM gestion.caso a\n                                              inner join gestion.historico d on d.id_caso = a.id\n                                              inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                              inner join gestion.estado f on f.id = a.id_estado\n                                              inner join gestion.municipio g on g.id = a.id_municipio\n                                              inner join gestion.parroquia e on e.id = a.id_parroquia\n                                              where b.id_resolutorio in (453)\n                                              and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                              and b.principal is true\n                                              and d.active = 1\n                                              and d.id_estatus in (3,4,6,7,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (453)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOB",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                        inner join gestion.municipio g on g.id = a.id_municipio\n                        inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1)\n\t\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\tand d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\twhere c.id_tipo_resolutorio in (1)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                        inner join gestion.municipio g on g.id = a.id_municipio\n                        inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (2)\n\t\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\t\t\t\t\t\t\t\t\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\tand d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\twhere c.id_tipo_resolutorio in (2)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\tand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\tand d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\tand d.active = 1\tand d.id_estatus in (6) \n\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (354)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (553)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-UNIVERSI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (561)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (597,563,566)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (599)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (503)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true and d.active = 1 and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (453)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere c.id_tipo_resolutorio in (1)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere c.id_tipo_resolutorio in (2)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\nand d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "SATISF-AGUAS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-ELECTRI",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (354)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-BASICA",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (553)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-UNIVERS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (561)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-TELECOM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (597,563,566)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-G-COMUNAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (599)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-G-DIRECTO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (503)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-SALUD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (453)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-GOB",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  \n\t\t\t--b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t\t\tc.id_tipo_resolutorio in (1) AND \n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-ALCAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  \n\t\t\t--b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t\t\tc.id_tipo_resolutorio in (2) AND \n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\tand d.active = 1 and d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": " CORREDOR ELECTORAL NACIONAL DETALLADO (MUNICIPIO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "MUNICIPIO ($estado)",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \n    e.nombre::Text \"ESTADO\", m.nombre::Text \"MUNICIPIO\",\n\t\tsum(CASE WHEN d.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\n\t\tsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \n\t\ttrunc(sum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\n\t\tfrom gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id\n\t\tinner join gestion.estado e  on e.id = a.id_estado\n\t\tinner join gestion.municipio m on m.id = a.id_municipio\n\t\twhere  d.active = 1 and d.id_estatus in (1,2,3,4,6,7,8)\n\t\tand m.nombre in ($municipio) and e.nombre in ($estado)\n\t\tgroup by m.nombre, e.nombre order by \"% EFECTIVIDAD %\" DESC"
      }
     ]
    }
   ]
  }
 ]
}