{
 "title": "DATOS DENUNCIANTES V3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOTAL DENUNCIANTES REGISTRADOS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   count(*)::Text \"TOTAL\"\n  FROM gestion.denunciante\n  where genero is not null\n"
    }
   ]
  },
  {
   "title": "TOTAL POR SEXO",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  genero::Text \"GENERO\", count(*)::Text \"TOTAL\"\n  FROM gestion.denunciante\n  where genero is not null\n  group by genero\n"
    }
   ]
  },
  {
   "title": "CANT. POR EDADES",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT  EXTRACT('YEAR' FROM AGE(fecha_nacimiento))::Text \"EDAD\", count(*)::Text \"TOTAL\"\n  FROM gestion.denunciante\n  where fecha_nacimiento is not null AND EXTRACT('YEAR' FROM AGE(fecha_nacimiento)) BETWEEN  15 AND 95\n  group by EXTRACT('YEAR' FROM AGE(fecha_nacimiento))\n  order BY count(*) desc\n"
    }
   ]
  },
  {
   "title": "LISTADO COMPLETO DENUNCIANTE",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT  cedula::TEXT \"CEDULA\", UPPER(nombre)::TEXT \"NOMBRES APELLIDOS\", UPPER(correo)::TEXT \"CORREO\", telefono::TEXT \"TELEFONO\", telefono_alt::TEXT \"TELEFONO ALT.\", \n\t\tgenero::TEXT \"GENERO\", to_char (fecha_nacimiento,'DD-MM-YYYY')::TEXT \"FECHA NAC.\", EXTRACT('YEAR' FROM AGE(fecha_nacimiento))::Text \"EDAD\"\n\tFROM gestion.denunciante \n\tWHERE genero IS NOT NULL AND fecha_nacimiento IS NOT NULL\n\tLIMIT 50000"
    }
   ]
  }
 ]
}