{
 "title": "DETALLES DE REGISTRO Y TAMAÑO POR ESQUEMA Y TABLA V3",
 "time": { "from": "2023-11-10T01:01:17.965Z", "to": "2023-11-11T01:01:17.965Z" },
 "panels": [
  {
   "title": "Cantidad de Registro por Tabla",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nnspname AS \"ESQUEMA\",relname as \"TABLA\",reltuples::integer as \"TOTAL REGISTRO\"\nFROM pg_class C\nLEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)\nWHERE\nnspname NOT IN ('pg_catalog', 'information_schema') AND\nrelkind='r'\nORDER BY reltuples DESC;"
    }
   ]
  },
  {
   "title": "VISTA DE BASE DE DATOS",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT viewname::TEXT \"VISTA\" FROM pg_catalog.pg_views WHERE schemaname = 'vw' ORDER BY viewname ASC;"
    }
   ]
  },
  {
   "title": "TAMAÑO DEL BD",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "\nSELECT  db.datname AS \"BASE DE DATOS\",\npg_size_pretty( pg_database_size(db.datname)) AS \"TAMAÑO\",\npg_database_size(db.datname) AS \"DETALLE TAMAÑO\"\nFROM  pg_database AS db \norder by \"DETALLE TAMAÑO\" desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "TAMAÑO DEL BD",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT nspname || '.' || relname AS \"TABLA\",\n    pg_size_pretty(pg_total_relation_size(C.oid)) AS \"TAMAÑO\"\n  FROM pg_class C\n  LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)\n  WHERE nspname NOT IN ('pg_catalog', 'information_schema')\n    AND C.relkind <> 'i'\n    AND nspname !~ '^pg_toast'\n  ORDER BY pg_total_relation_size(C.oid) DESC\n  LIMIT 50;"
    }
   ]
  }
 ]
}