{
 "title": "ESTADOS,  MUNICIPIOS, PARROQUIA Y MINISTERIOS CON UBCH V3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estado",
    "label": "Estado",
    "query": "SELECT nombre FROM gestion.estado where id < 26 order by id"
   },
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "SELECT a.nombre  FROM gestion.municipio a inner join gestion.estado b on a.id_estado = b.id where  b.nombre in ($estado) "
   },
   {
    "name": "parroquia",
    "label": "Parroquia",
    "query": "SELECT a.nombre FROM gestion.parroquia a \n\tinner join gestion.municipio b on a.id_municipio = b.id \n\tinner join gestion.estado c on c.id = b.id_estado\n\twhere  c.nombre in ($estado)  and b.nombre in ($municipio)"
   },
   {
    "name": "sub_categoria",
    "label": "CATEGORIA",
    "query": "SELECT name FROM gestion.category WHERE id  in (1,2,3,4,5,6,7)"
   },
   {
    "name": "resolutor",
    "label": "MINISTERIOS",
    "query": "SELECT  r.nombre\n\tFROM gestion.resolutorio r\n\twhere r.id_tipo_resolutorio = 3"
   },
   {
    "name": "subresolutor",
    "label": "INSTITUCION",
    "query": "SELECT a.nombre\n\tFROM gestion.resolutorio a\n\tinner join gestion.resolutorio b ON b.id = a.id_padre\n\twhere\n       b.nombre IN ($resolutor)"
   }
  ]
 },
 "panels": [
  {
   "title": "RECIBIDOS POR VENAPP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"TOTAL\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.estado b on b.id = a.id_estado\r\ninner join gestion.municipio mun on mun.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\r\ninner join gestion.denunciante de on de.id = a.id_denunciante\r\ninner join psuv.ubch_structures ub on ub.dni = de.cedula\r\ninner join gestion.responsable f on f.id_caso = a.id\r\ninner join gestion.resolutorio h on h.id = f.id_resolutorio\r\nwhere b.id < 25 and f.principal is true\r\nand b.nombre in ($estado) \r\nand mun.nombre in ($municipio)\r\nAND e.nombre in ($parroquia)\r\nand c.name in ($sub_categoria)\r\nand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\nAND a.id_estatus in (1,2,3,4,6,8)\r\norder by \"TOTAL\" desc"
    }
   ]
  },
  {
   "title": "POR ATENDER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select count(*) as \"TOTAL\"\r\nfrom gestion.caso a\r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.estado b on b.id = a.id_estado\r\ninner join gestion.municipio mun on mun.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\r\ninner join gestion.denunciante de on de.id = a.id_denunciante\r\ninner join psuv.ubch_structures ub on ub.dni = de.cedula\r\ninner join gestion.responsable f on f.id_caso = a.id\r\ninner join gestion.resolutorio h on h.id = f.id_resolutorio\r\nwhere b.id < 25 \r\nand b.nombre in ($estado) \r\nand mun.nombre in ($municipio)\r\nAND e.nombre in ($parroquia)\r\nand c.name in ($sub_categoria)\r\nand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\nAND a.id_estatus in (1,2,3,4,6,8))\r\n-\r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\t--inner JOIN  gestion.estatus i ON d.id_estatus = i.id \r\n\tinner join gestion.category c on c.id = a.id_sub_categoria\r\n\tinner join gestion.estado b on b.id = a.id_estado\r\n\tinner join gestion.municipio mun on mun.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\tinner join gestion.denunciante de on de.id = a.id_denunciante\r\n  inner join psuv.ubch_structures ub on ub.dni = de.cedula\r\n  inner join gestion.responsable f on f.id_caso = a.id\r\n  inner join gestion.resolutorio h on h.id = f.id_resolutorio\r\n\twhere\r\n\tb.nombre in ($estado) \r\n\tand mun.nombre in ($municipio)\r\n\tAND e.nombre in ($parroquia)\r\n\tand c.name in ($sub_categoria)\r\n\tand (h.nombre in ($resolutor) or h.nombre in ($subresolutor)) \r\n\tand a.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')) as total"
    }
   ]
  },
  {
   "title": "TOTAL CASOS ATENDIDOS ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\t--inner JOIN  gestion.estatus i ON d.id_estatus = i.id \r\n\tinner join gestion.category c on c.id = a.id_sub_categoria\r\n\tinner join gestion.estado b on b.id = a.id_estado\r\n\tinner join gestion.municipio mun on mun.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\tinner join gestion.denunciante de on de.id = a.id_denunciante\r\n  inner join psuv.ubch_structures ub on ub.dni = de.cedula\r\n  inner join gestion.responsable f on f.id_caso = a.id\r\n  inner join gestion.resolutorio h on h.id = f.id_resolutorio\r\n\twhere\r\n\tb.nombre in ($estado) \r\n\tand mun.nombre in ($municipio)\r\n\tAND e.nombre in ($parroquia)\r\n\tand c.name in ($sub_categoria)\r\n\tand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\n\tand a.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL  %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (select count(*) as \"TOTAL\"\r\n                                            from gestion.caso a\r\n                                            inner JOIN  gestion.estatus i ON a.id_estatus = i.id \r\n                                            inner join gestion.category c on c.id = a.id_sub_categoria\r\n                                            inner join gestion.estado b on b.id = a.id_estado\r\n                                            inner join gestion.municipio mun on mun.id = a.id_municipio\r\n                                            inner join gestion.parroquia e on e.id = a.id_parroquia\r\n                                            inner join gestion.denunciante de on de.id = a.id_denunciante\r\n                                            inner join psuv.ubch_structures ub on ub.dni = de.cedula\r\n                                            inner join gestion.responsable f on f.id_caso = a.id\r\n                                            inner join gestion.resolutorio h on h.id = f.id_resolutorio\r\n                                            where  b.id < 25 and f.principal is true\r\n                                            and b.nombre in ($estado) \r\n                                            and mun.nombre in ($municipio)\r\n                                            AND e.nombre in ($parroquia)\r\n                                            and c.name in ($sub_categoria)\r\n                                            and (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\n                                            AND a.id_estatus in (1,2,3,4,6,8))::Decimal, 2) as porcentaje\r\n\t\tFROM gestion.caso a\r\n\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id \r\n\t\tinner join gestion.category c on c.id = a.id_sub_categoria\r\n\t\tinner join gestion.estado f on f.id = a.id_estado\r\n\t\tinner join gestion.municipio mun on mun.id = a.id_municipio\r\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\t\tinner join gestion.denunciante de on de.id = a.id_denunciante\r\n  \tinner join psuv.ubch_structures ub on ub.dni = de.cedula\r\n  \tinner join gestion.responsable ff on ff.id_caso = a.id\r\n    inner join gestion.resolutorio h on h.id = ff.id_resolutorio\r\n\t\twhere \r\n\t\tf.nombre in ($estado) and ff.principal is true\r\n\t\tand mun.nombre in ($municipio)\r\n\t\tAND e.nombre in ($parroquia)\r\n\t\tand c.name in ($sub_categoria)\r\n\t\tand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\n\t\tand a.id_estatus in (6) \r\n\t\tand (a.feedback >= 2 or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "SATISFACCIÓN",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \r\n\t\t\tFROM gestion.caso a\r\n\t\t\tinner JOIN  gestion.estatus i ON a.id_estatus = i.id \r\n\t\t\tinner join gestion.category c on c.id = a.id_sub_categoria\r\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\r\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\r\n\t\t\tinner join gestion.municipio mun on mun.id = a.id_municipio\r\n\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\t\t\tinner join gestion.denunciante de on de.id = a.id_denunciante\r\n  \t\tinner join psuv.ubch_structures ub on ub.dni = de.cedula\r\n  \t\tinner join gestion.responsable ff on ff.id_caso = a.id\r\n      inner join gestion.resolutorio h on h.id = ff.id_resolutorio\r\n\t\t\twhere \r\n\t\t\tf.nombre in ($estado) and ff.principal is true\r\n\t\t\tand mun.nombre in ($municipio)\r\n\t\t  and e.nombre in ($parroquia)\r\n\t\t  and c.name in ($sub_categoria)\r\n\t\t  and (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\n\t\t\tand a.id_estatus in (6) and a.feedback is not null"
    }
   ]
  },
  {
   "title": "  ",
   "type": "table",
   "gridPos": { "h": 25, "w": 1, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select id as \"RANKING\"\r\nfrom gestion.estado\r\nwhere  id < 25\r\norder by id asc"
    }
   ]
  },
  {
   "title": "ESTADO",
   "type": "table",
   "gridPos": { "h": 25, "w": 6, "x": 1, "y": 4 },
   "targets": [
    {
     "rawSql": "select b.nombre::Text \"ESTADO\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) and (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner JOIN  gestion.estatus i ON a.id_estatus = i.id \r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.estado b on b.id = a.id_estado\r\ninner join gestion.municipio mun on mun.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\r\ninner join gestion.denunciante de on de.id = a.id_denunciante\r\ninner join psuv.ubch_structures ub on ub.dni = de.cedula\r\ninner join gestion.responsable f on f.id_caso = a.id\r\ninner join gestion.resolutorio h on h.id = f.id_resolutorio\r\nwhere b.id < 25 and f.principal is true\r\nand b.nombre in ($estado)\r\nand mun.nombre in ($municipio)\r\nAND e.nombre in ($parroquia)\r\nand c.name in ($sub_categoria)\r\nand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\nAND a.id_estatus in (1,2,3,4,6,8)\r\ngroup by b.nombre\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "  ",
   "type": "table",
   "gridPos": { "h": 25, "w": 1, "x": 7, "y": 4 },
   "targets": [
    {
     "rawSql": "select id as \"RANKING\"\r\nfrom gestion.estado\r\nwhere  id < 25\r\norder by id asc"
    }
   ]
  },
  {
   "title": "MUNICIPIO",
   "type": "table",
   "gridPos": { "h": 25, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "select mun.nombre || ' (' || b.nombre || ')' ::Text \"MUNICIPIOS\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner JOIN  gestion.estatus i ON a.id_estatus = i.id \r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.estado b on b.id = a.id_estado\r\ninner join gestion.municipio mun on mun.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\r\ninner join gestion.denunciante de on de.id = a.id_denunciante\r\ninner join psuv.ubch_structures ub on ub.dni = de.cedula\r\ninner join gestion.responsable f on f.id_caso = a.id\r\ninner join gestion.resolutorio h on h.id = f.id_resolutorio\r\nwhere a.id_estatus in (1,2,3,4,6,8) and f.principal is true\r\nand b.nombre in ($estado)\r\nand mun.nombre in ($municipio)\r\nAND e.nombre in ($parroquia)\r\nand c.name in ($sub_categoria)\r\nand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\nand b.id < 25 \r\ngroup by mun.nombre, b.nombre\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "  ",
   "type": "table",
   "gridPos": { "h": 25, "w": 1, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "select id as \"RANKING\"\r\nfrom gestion.estado\r\nwhere  id < 25\r\norder by id asc"
    }
   ]
  },
  {
   "title": "PARROQUIA",
   "type": "table",
   "gridPos": { "h": 25, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "rawSql": "select e.nombre || ' (' || b.nombre || ')' ::Text \"PARROQUIA\",\r\nsum(CASE WHEN a.id_estatus in (1,2,3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\nsum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\r\ntrunc(sum(CASE WHEN a.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\r\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\nfrom gestion.caso a\r\ninner JOIN  gestion.estatus i ON a.id_estatus = i.id \r\ninner join gestion.category c on c.id = a.id_sub_categoria\r\ninner join gestion.estado b on b.id = a.id_estado\r\ninner join gestion.municipio mun on mun.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\r\ninner join gestion.denunciante de on de.id = a.id_denunciante\r\ninner join psuv.ubch_structures ub on ub.dni = de.cedula\r\ninner join gestion.responsable f on f.id_caso = a.id\r\ninner join gestion.resolutorio h on h.id = f.id_resolutorio\r\nwhere a.id_estatus in (1,2,3,4,6,8) and f.principal is true\r\nand b.nombre in ($estado)\r\nand mun.nombre in ($municipio)\r\nAND e.nombre in ($parroquia)\r\nand c.name in ($sub_categoria)\r\nand (h.nombre in ($resolutor) or h.nombre in ($subresolutor))\r\nand b.id < 25 \r\ngroup by e.nombre, b.nombre\r\norder by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  { "title": "CASOS DETALLADO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CASOS DETALLADOS (UBCH)",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "     SELECT\r\n      \ta.descripcion::TEXT \"DESCRIP\",\r\n      \ta.nombre::Text \"CODIGO\",\r\n      \te.cedula::Text \"CEDULA\",\r\n      \te.nombre::TEXT \"DENUNCIANTE\",\r\n\t    \tub.state || ' - ' || ub.municipality || ' - ' || ub.parish || ' - ' || ub.ubch as \"UBCH\",\r\n      \te.telefono::Text \"TELEFONO\",\r\n      \tb.nombre::Text \"ESTADO\",\r\n      \tc.nombre::Text \"MUNICIPIO\",\r\n      \td.nombre::Text \"PARROQ\",\r\n  \t\t  re.nombre::Text \"RESPONSABLES\",\r\n\t\t  est.nombre::Text \"ESTATUS\",\r\n  \t  \ta.fecha::Text \"FECHA CREACION\"\r\n\t  \tFROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            --inner JOIN  gestion.estatus i ON d.id_estatus = i.id \r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n      \t\t\tinner join psuv.ubch_structures ub on ub.dni = e.cedula\r\n\t\t\t\t    inner join gestion.estatus est on est.id = a.id_estatus \r\n      \t\t\tleft join gestion.responsable r on r.id_caso = a.id and r.principal is true\r\n      \t\t\tleft join gestion.resolutorio re on re.id = r.id_resolutorio\r\n      \twhere a.id_estatus in (1,2,3,4,6,8)\r\n    \t\t\tand b.nombre in ($estado)\r\n    \t\t\tand c.nombre in ($municipio)\r\n    \t\t\tAND d.nombre in ($parroquia)\r\n    \t\t\tand g.name in ($sub_categoria)\r\n    \t\t\tand (re.nombre in ($resolutor) or re.nombre in ($subresolutor))"
    }
   ]
  }
 ]
}