{
 "title": "INDICE DE SATISFACCIÓN V3",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ministerio",
    "label": "MINISTERIO E INSTITUCIÓN",
    "query": "SELECT nombre FROM gestion.resolutorio\n\twhere id_tipo_resolutorio in (3,4)"
   },
   {
    "name": "gobernaciones",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio where id_tipo_resolutorio = 1 ORDER BY nombre "
   }
  ]
 },
 "panels": [
  {
   "title": "INDICE DE SATISFACCIÓN MINISTERIO E INSTITUCCIÓN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "MUY SATISFECHO%",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true and r.id_tipo_resolutorio in (3,4)\n\t\t\tand a.id_estatus in (6) and a.feedback >= 3.5 \t"
      }
     ]
    },
    {
     "title": "SATISFECHO%",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 3.5 and a.feedback >= 2.5 \t"
      }
     ]
    },
    {
     "title": "INSATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 2.5 and a.feedback >= 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "MUY POCO SATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 1.5 and a.verificado = 'SI' \t"
      }
     ]
    },
    {
     "title": "CONFIRMADOS-SIN VALORACIÓN %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI'\tand a.feedback is null"
      }
     ]
    },
    {
     "title": "REVISADO POR OPERADORES %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n                                      \t\t\tand r.nombre in ($ministerio) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))"
      }
     ]
    },
    {
     "title": "MUY SATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback >= 3.5 \t"
      }
     ]
    },
    {
     "title": "SATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 3.5 and a.feedback\t>= 2.5"
      }
     ]
    },
    {
     "title": "INSATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand (a.feedback < 2.5 and a.feedback >= 1.5) and a.verificado = 'SI'\n\t\t\t\n\t\t\t"
      }
     ]
    },
    {
     "title": "MUY POCO SATISFECHO ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.feedback < 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "CONFIRMADOS-SIN VALORACIÓN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI' and a.feedback is null"
      }
     ]
    },
    {
     "title": "REVISADO POR OPERADORES ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (3,4)\n\t\t\tand r.nombre in ($ministerio) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))\n\t\t"
      }
     ]
    },
    {
     "title": "INDICE DE SATISFACCIÓN MINISTERIO E INSTITUCCIÓN ($ministerio)",
     "type": "table",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT \n      r.nombre as \"MINISTERIO E INSTITUCCIÓN\", \n      sum(CASE WHEN a.feedback >= 3.5 THEN 1 ELSE 0 END) AS \"MUY SATISFECHO\",\n      sum(CASE WHEN a.feedback < 3.5 and a.feedback >= 2.5 THEN 1 ELSE 0 END) AS \"SATISFECHO\",\n      sum(CASE WHEN a.feedback < 2.5 and a.feedback >= 1.5 THEN 1 ELSE 0 END) AS \"INSATISFECHO\",\n\t\t\tsum(CASE WHEN a.feedback < 1.5 THEN 1 ELSE 0 END) AS \"MUY POCO SATISFACHO\",\n\t\t  CONCAT(case when round(avg(a.feedback)) = 1 then 'MUY POCO SATISFACHO'\n                  when round(avg(a.feedback)) = 2 then 'INSATISFECHO'\n                  when round(avg(a.feedback)) = 3 then 'SATISFECHO'\n                  when round(avg(a.feedback)) > 3 then 'MUY SATISFECHO'\n                  when round(avg(a.feedback)) is null then 'SIN VALORACIÓN'\n                  end) as \"PROMEDIO\",\n      sum(CASE WHEN (a.feedback is null and a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"SIN VALORACIÓN Y CONFIRMADO\",\n      count(*) AS \"TOTAL ATENDIDO\"\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro)\n\t\t\t--AND b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,453,553,561,597,563,566,354,503,599)\n\t\t\tand r.nombre in ($ministerio)\n\t\t\tand r.id_tipo_resolutorio in (3,4)\n\t\t\tand b.principal is true\n\t\t\tand a.id_estatus in (6) and ((a.feedback >= 2.5) or (a.verificado = 'SI'))\t\n\t\t\tgroup by r.nombre ORDER BY \"MUY SATISFECHO\" desc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN GOBERNACIONES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MUY SATISFECHO%",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n                                      \t\t\tand r.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 1\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback >= 3.5"
      }
     ]
    },
    {
     "title": "SATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n                                      \t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback < 3.5\tAND a.feedback >= 2.5\t"
      }
     ]
    },
    {
     "title": "INSATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n                                      \t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback < 2.5\tAND a.feedback >= 1.5\tand a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "MUY POCO SATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n                                      \t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback < 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "CONFIRMADOS-SIN VALORACIÓN %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n                                      \t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI'\tand a.feedback is null"
      }
     ]
    },
    {
     "title": "REVISADO POR OPERADORES %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (1)\n                                      \t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) \n                                      \t\t\tand ((a.feedback >= 2.5) or (a.verificado = 'SI'))\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (1)\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))"
      }
     ]
    },
    {
     "title": "MUY SATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\t    SELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback >= 3.5\t"
      }
     ]
    },
    {
     "title": "SATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      SELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback < 3.5\tAND a.feedback >= 2.5"
      }
     ]
    },
    {
     "title": "INSATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\t    SELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback < 2.5\tAND a.feedback >= 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "MUY POCO SATISFECHO ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.feedback < 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "CONFIRMADOS-SIN VALORACIÓN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\t  SELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI'\tand a.feedback is null"
      }
     ]
    },
    {
     "title": "REVISADO POR OPERADORES ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio in (1)\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))\n\t\t"
      }
     ]
    },
    {
     "title": "INDICE DE SATISFACCIÓN GOBERNACIONES",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT \n      --ROW_NUMBER (),\n      r.nombre as \"GOBERNACIÓN\", \n      sum(CASE WHEN a.feedback >= 3.5 THEN 1 ELSE 0 END) AS \"MUY SATISFECHO\",\n      sum(CASE WHEN a.feedback < 3.5 and a.feedback >= 2.5 THEN 1 ELSE 0 END) AS \"SATISFECHO\",\n      sum(CASE WHEN a.feedback < 2.5 and a.feedback >= 1.5 and a.verificado = 'SI' THEN 1 ELSE 0 END) AS \"INSATISFECHO\",\n\t\t\tsum(CASE WHEN a.feedback < 1.5 and a.verificado = 'SI' THEN 1 ELSE 0 END) AS \"MUY POCO SATISFACHO\",\n\t\t  CONCAT(case when round(avg(a.feedback)) = 1 then 'MUY POCO SATISFACHO'\n                  when round(avg(a.feedback)) = 2 then 'INSATISFECHO'\n                  when round(avg(a.feedback)) = 3 then 'SATISFECHO'\n                  when round(avg(a.feedback)) > 3 then 'MUY SATISFECHO'\n                  when round(avg(a.feedback)) is null then 'SIN VALORACIÓN'\n                  end) as \"PROMEDIO\",\n      sum(CASE WHEN (a.feedback is null and a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"SIN VALORACIÓN Y CONFIRMADO\",\n      count(*) AS \"TOTAL ATENDIDO\"\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\twhere \n\t\t\t$__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 1\n\t\t\tand r.nombre in ($gobernaciones) and b.principal is true\n\t\t\tand a.id_estatus in (6) \n\t\t\tand (a.feedback >= 2.5 or a.verificado = 'SI')\t\n\t\t\tgroup by r.nombre ORDER BY \"MUY SATISFECHO\" desc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN ALCALDÍAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "MUY SATISFECHO%",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true\n                                      \t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback >= 3.5"
      }
     ]
    },
    {
     "title": "SATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n                                      \t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback < 3.5 AND  a.feedback >= 2.5"
      }
     ]
    },
    {
     "title": "INSATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a \n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 2\n                                      \t\t\tand rr.nombre in ($gobernaciones) and b.principal is true\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true\n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback < 2.5 AND a.feedback >= 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "MUY POCO SATISFECHO %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 2\n                                      \t\t\tand rr.nombre in ($gobernaciones) and b.principal is true \n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback < 1.5 and a.verificado = 'SI'\t"
      }
     ]
    },
    {
     "title": "CONFIRMADOS-SIN VALORACIÓN %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n                                      \t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI'\tand a.feedback is null"
      }
     ]
    },
    {
     "title": "REVISADO POR OPERADORES %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\n\t\tSELECT \n       ROUND(count(a.id)::Decimal * 100 / ( SELECT \n                                             count(a.id)\n                                      \t\t\tFROM gestion.caso a\n                                      \t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n                                      \t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n                                      \t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n                                      \t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n                                      \t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n                                      \t\t\tand a.id_estatus in (6) and (a.feedback >= 2.5 or a.verificado = 'SI')\n                                             )::Decimal, 2) as porcentaje\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) \n\t\t\t\tand ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))"
      }
     ]
    },
    {
     "title": "MUY SATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback >= 3.5"
      }
     ]
    },
    {
     "title": "SATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\t\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback < 3.5 AND  a.feedback >= 2.5"
      }
     ]
    },
    {
     "title": "INSATISFECHO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\t   \tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback < 2.5 AND a.feedback >= 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "MUY POCO SATISFECHO ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) AND a.feedback < 1.5 and a.verificado = 'SI'"
      }
     ]
    },
    {
     "title": "CONFIRMADOS-SIN VALORACIÓN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) and a.verificado = 'SI'\tand a.feedback is null"
      }
     ]
    },
    {
     "title": "REVISADO POR OPERADORES ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT \n       count(a.id)\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id \n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\twhere $__timeFilter(a.fecha_registro) and b.principal is true \n\t\t\tand rr.nombre in ($gobernaciones) and r.id_tipo_resolutorio = 2\n\t\t\tand a.id_estatus in (6) \n\t\t  and ((a.verificado = 'SI'\tand a.feedback is null) or (a.feedback < 2.5 and a.verificado = 'SI'))"
      }
     ]
    },
    {
     "title": "INDICE DE SATISFACCIÓN ALCALDIAS",
     "type": "table",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \n      --ROW_NUMBER (),\n      r.nombre || ' (' || es.nombre || ')' as \"GOBERNACIÓN\", \n      sum(CASE WHEN a.feedback >= 3.5 THEN 1 ELSE 0 END) AS \"MUY SATISFECHO\",\n      sum(CASE WHEN a.feedback < 3.5 and a.feedback >= 2.5 THEN 1 ELSE 0 END) AS \"SATISFECHO\",\n      sum(CASE WHEN a.feedback < 2.5 and a.feedback >= 1.5 THEN 1 ELSE 0 END) AS \"INSATISFECHO\",\n\t\t\tsum(CASE WHEN a.feedback < 1.5 THEN 1 ELSE 0 END) AS \"MUY POCO SATISFACHO\",\n      CONCAT(case when round(avg(a.feedback)) = 1 then 'MUY POCO SATISFACHO'\n                  when round(avg(a.feedback)) = 2 then 'INSATISFECHO'\n                  when round(avg(a.feedback)) = 3 then 'SATISFECHO'\n                  when round(avg(a.feedback)) > 3 then 'MUY SATISFECHO'\n                  when round(avg(a.feedback)) is null then 'SIN VALORACIÓN'\n                  end) as \"PROMEDIO\",\n      sum(CASE WHEN (a.feedback is null and a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"SIN VALORACIÓN Y CONFIRMADO\",\n      count(*) AS \"TOTAL ATENDIDO\"\n\t\t\tFROM gestion.caso a \n\t\t\tinner join gestion.responsable b on b.id_caso =  a.id\n\t\t\tinner join gestion.resolutorio r on r.id = b.id_resolutorio\n\t\t\tinner join gestion.resolutorio rr on rr.id_estado = r.id_estado\n\t\t\tinner join gestion.estado es on es.id = r.id_estado\n\t\t\twhere \n\t\t\t$__timeFilter(a.fecha_registro) and r.id_tipo_resolutorio = 2\n\t\t\tand rr.nombre in ($gobernaciones) and b.principal is true \n\t\t\tand a.id_estatus in (6) \n\t\t  and (a.feedback >= 2.5 or  a.verificado = 'SI')\n\t\t\tgroup by r.nombre, es.nombre ORDER BY \"MUY SATISFECHO\" desc"
      }
     ]
    }
   ]
  }
 ]
}