{
 "title": "SESIONES ABIERTA POR USUARIOS Y ROLES V3 DEFINIR TABLA SESIONES EN ESQUEMA PUBLIC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ministerio",
    "query": "SELECT nombre FROM gestion.resolutorio\n\twhere id_tipo_resolutorio in (3,4)\nand id in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,\n595,596,598,354,553,561,597,563, 566,599,503,453)"
   }
  ]
 },
 "panels": [
  { "title": "BUSQUEDA POR RESOLUTORES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL DE SESIONES ABIERTA POR ROLES GENERAL (POR BUSQUEDA)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", \n    UPPER(u.username)::Text \"USUARIO\",\n    UPPER(usd.name || ' ' || usd.last_name)::TEXT \"NOMBRE Y APELLIDO\",\n    UPPER(res.nombre)::TEXT \"RESOLUTOR\", count(*) as \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on u.id = usd.user_id\n\t\tinner join gestion.resolutorio res on res.id = usd.id_resolutorio\n\t\twhere res.nombre in ($ministerio)\n\t\t GROUP BY us.user_id, \"USUARIO\", \"NOMBRE Y APELLIDO\", res.nombre\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
    }
   ]
  },
  {
   "title": "TOTAL DE USUARIOS CONECTADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "USUARIOS CONECTADOS PCP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \n\t\tINNER join public.session s on s.user_id::integer = us.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = us.id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial');\n\t\t"
      }
     ]
    },
    {
     "title": "USUARIOS CONECTADOS RESOLUTORES",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 7, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \n\t\tINNER join public.session s on s.user_id::integer = us.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = us.id\n\t\twhere c.item_name in ('resolutor-nacional', 'resolutor');\n\t\t"
      }
     ]
    },
    {
     "title": "TOTAL USUARIOS CONECTADOS ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \n\t\tINNER join public.session s on s.user_id::integer = us.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = us.id\n\t\twhere c.item_name in ('resolutor-nacional', 'resolutor', 'operador','operador-nacional','coordinador','supervisor-especial');\n\t\t"
      }
     ]
    }
   ]
  },
  {
   "title": "TOTAL DE SESIONES  ACTIVAS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL DE SESIONES  USUARIOS PCP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial');"
      }
     ]
    },
    {
     "title": "TOTAL DE SESIONES  USUARIOS RESOLUTORES",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 7, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('resolutor-nacional', 'resolutor');"
      }
     ]
    },
    {
     "title": "TOTAL DE SESIONES  USUARIOS RESOLUTORES",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial','resolutor-nacional', 'resolutor');"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTES GENERAL DE SESIONES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL DE SESIONES ABIERTA POR ROLES GENERAL",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": " SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\",  UPPER(c.item_name)::Text \"USUARIOS ROLES\", count(*) as \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name not in ('admin')\n\t\t GROUP BY c.item_name\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
      }
     ]
    },
    {
     "title": "CANTIDAD DE SESIONES ABIERTAS POR MINISTERIOS E INSTITUCIONES",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": " SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", res.nombre::Text \"MINISTERIO E INSTITUCION\", count(*) as \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\tinner join gestion.resolutorio res on res.id = usd.id_resolutorio\n\t\twhere --c.item_name in ('operador','operador-nacional','coordinador')\n\t\tres.id_tipo_resolutorio IN (3,4)\n\t\t GROUP BY res.nombre\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
      }
     ]
    },
    {
     "title": "CANTIDAD DE SESIONES ABIERTAS POR ROLES EN PCP",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": " SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", UPPER(c.item_name)::Text \"USUARIOS ROLES\", count(*) as \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial')\n\t\t GROUP BY c.item_name\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
      }
     ]
    },
    {
     "title": "CANTIDAD DE SESIONES ABIERTAS POR USUARIOS EN PCP",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "rawSql": "  SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", UPPER(u.username)::Text \"USUARIO\", UPPER(usd.name) || ' ' || UPPER(usd.last_name)::Text \"NOMBRE APELLIDO\", UPPER(c.item_name)::TEXT \"ROL\", \n \t\tcount(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial')\n\t\tGROUP BY u.username, \"NOMBRE APELLIDO\", c.item_name\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
      }
     ]
    },
    {
     "title": "CANTIDAD DE SESIONES ABIERTAS POR GOBERNACIONES",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": " SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\",  res.nombre::Text \"GOBERNACIONES\", count(*) as \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\tinner join gestion.resolutorio res on res.id = usd.id_resolutorio\n\t\twhere --c.item_name in ('operador','operador-nacional','coordinador')\n\t\tres.id_tipo_resolutorio IN (1)\n\t\t GROUP BY res.nombre\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
      }
     ]
    },
    {
     "title": "CANTIDAD DE SESIONES ABIERTAS POR ALCALDÍAS",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "rawSql": " SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", res.nombre || ' (' || es.nombre || ')'::Text \"ALCADIAS\", count(*) as \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\tinner join gestion.resolutorio res on res.id = usd.id_resolutorio\n\t\tinner join gestion.estado es on es.id = res.id_estado\n\t\twhere --c.item_name in ('operador','operador-nacional','coordinador')\n\t\tres.id_tipo_resolutorio IN (2)\n\t\t GROUP BY res.nombre, es.nombre\n\t   HAVING (COUNT(*) > 0) \n\t   order by count(*) desc"
      }
     ]
    },
    {
     "title": "CANTIDAD DE USUARIOS CONECTADOS",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "rawSql": "SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", \r\n    UPPER(u.username)::Text \"USUARIO\",\r\n    UPPER(usd.name || ' ' || usd.last_name)::TEXT \"NOMBRE Y APELLIDO\",\r\n\tUPPER(c.item_name)::TEXT \"ROL\"\r\n   -- UPPER(res.nombre)::TEXT \"RESOLUTOR\", count(*) as \"TOTAL\"\r\n\t\tFROM public.session us\r\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\r\n\t\tinner join public.user u on u.id = usd.user_id\r\n\t\t--inner join gestion.resolutorio res on res.id = usd.id_resolutorio\r\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\r\n\t\twhere --res.nombre is not null\r\n\t\tc.item_name in ('operador','operador-nacional','coordinador','coordinador-especial','supervisor-especial', 'resolutor','resolutor-nacional')\r\n\t\tGROUP BY us.user_id, c.item_name, \"USUARIO\", \"NOMBRE Y APELLIDO\", u.username\r\n\t   HAVING (COUNT(*) > 0) \r\n\t   order by count(*) desc"
      }
     ]
    }
   ]
  }
 ]
}