{
 "title": "CARACAS V3",
 "time": { "from": "2021-02-25T05:26:07.561Z", "to": "2023-12-16T05:26:07.561Z" },
 "templating": {
  "list": [
   {
    "name": "subcateg",
    "label": "SUB CATEG",
    "query": "SELECT  c.name FROM gestion.category c\n inner join gestion.category cc on cc.id = c.parent where cc.parent is null and c.id <= 17\n order by c.id asc"
   },
   {
    "name": "resolutorg",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio a where a.id_tipo_resolutorio = 1  and id = 1"
   },
   {
    "name": "resolutorea",
    "label": "ALCALDIAS",
    "query": "SELECT a.nombre FROM gestion.resolutorio a inner join gestion.resolutorio b on a.id_estado = b.id_estado where a.id_tipo_resolutorio = 2 and b.nombre in ($resolutorg) "
   }
  ]
 },
 "panels": [
  {
   "title": "CASOS  REGIONALES",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT(\r\nSELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category  g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.nombre in ($resolutorg)\r\n                        and g.name in ($subcateg)\r\n                        and r.id_tipo_resolutorio in (1,2)\r\n                        --and d.active = 1\r\n                        and e.principal is true\r\n                        and d.id_estatus in (3,4,6,7,8))\r\n      group by id_caso\r\n      HAVING count(id_caso) >= 1) as Total)\r\n+\r\n(SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.id in (SELECT id \r\n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\r\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorea)\r\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n                        and g.name in ($subcateg)\r\n                        --and d.active = 1\r\n                        and e.principal is true\r\n                        and d.id_estatus in (3,4,6,7,8))\r\n      group by id_caso\r\n      HAVING count(id_caso) > 0) as Total)"
    }
   ]
  },
  {
   "title": "GOBERNACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nfrom (SELECT id_caso,count(*)\n      FROM gestion.responsable\n      where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.nombre in ($resolutorg)\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (3,4,6,8))\n      group by id_caso\n      HAVING count(id_caso) >= 1\n      ) as Total\n"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nfrom (SELECT id_caso,count(*)\n      FROM gestion.responsable\n      where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.nombre in ($resolutorg)\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (6)\n                        and a.verificado is null\n                        and (a.feedback < 3 or a.feedback is null))\n      group by id_caso\n      HAVING count(id_caso) = 1) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nfrom (SELECT id_caso,count(*)\n      FROM gestion.responsable\n      where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.nombre in ($resolutorg)\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (6)\n                        and (a.feedback >= 3   or  a.verificado = 'SI'))\n      group by id_caso\n      HAVING count(id_caso) = 1) as Total "
    }
   ]
  },
  {
   "title": "GOBERNACIÓN %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT trunc(((SELECT (COUNT(*)::decimal)as atendido\n                from (SELECT id_caso,count(*)\n                      FROM gestion.responsable\n                      where id_caso in (select a.id\n                      from gestion.caso a\n                      inner join gestion.category g on g.id = a.id_categoria\n                      inner join gestion.historico d on d.id_caso = a.id\n                      inner join gestion.responsable e on e.id_caso = a.id\n                      inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                      where r.nombre in ($resolutorg)\n                      and g.name in ($subcateg)\n                      --and d.active = 1\n                      and e.principal is true\n                      and d.id_estatus in (6)\n                      and (a.feedback >= 3   or  a.verificado = 'SI'))\n                      group by id_caso\n                      HAVING count(id_caso) = 1) as Total)*100/(SELECT (COUNT(*)::decimal)\n                                                                from (SELECT id_caso,count(*)\n                                                                FROM gestion.responsable\n                                                                where id_caso in (select a.id\n                                                                from gestion.caso a\n                                                                inner join gestion.category g on g.id = a.id_categoria\n                                                                inner join gestion.historico d on d.id_caso = a.id\n                                                                inner join gestion.responsable e on e.id_caso = a.id\n                                                                inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                                                                where r.nombre in ($resolutorg)\n                                                                and g.name in ($subcateg)\n                                                                --and d.active = 1\n                                                                and e.principal is true\n                                                                and d.id_estatus in (3,4,6,8))\n                                                                group by id_caso\n                                                                HAVING count(id_caso) = 1) as Total))::decimal,2) as porcentaje; "
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nfrom (SELECT id_caso,count(*)\n      FROM gestion.responsable\n      where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.id in (SELECT id \n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorea)\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (3,4,6,8))\n      group by id_caso\n      HAVING count(id_caso) > 0) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nfrom (SELECT id_caso,count(*)\n      FROM gestion.responsable\n      where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.id in (SELECT id \n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorea)\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (6)\n                        and a.verificado is null \n                        and (a.feedback < 3 or a.feedback is null))\n      group by id_caso\n      HAVING count(id_caso) = 1) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nfrom (SELECT id_caso,count(*)\n      FROM gestion.responsable\n      where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.id in (SELECT id \n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorea)\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (6)\n                        and (a.feedback >= 3   or  a.verificado = 'SI'))\n      group by id_caso\n      HAVING count(id_caso) > 0) as Total\n"
    }
   ]
  },
  {
   "title": "ALCALDÍA  %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(((SELECT COUNT(*)\n                from (SELECT id_caso,count(*)\n                FROM gestion.responsable\n                where id_caso in (select a.id\n                        from gestion.caso a\n                        inner join gestion.category g on g.id = a.id_categoria\n                        inner join gestion.historico d on d.id_caso = a.id\n                        inner join gestion.responsable e on e.id_caso = a.id\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                        where r.id in (SELECT id \n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorea)\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\n                        and g.name in ($subcateg)\n                        --and d.active = 1\n                        and e.principal is true\n                        and d.id_estatus in (6)\n                        and (a.feedback >= 3   or  a.verificado = 'SI'))\n      group by id_caso\n      HAVING count(id_caso) > 0) as Total)*100/(SELECT (COUNT(*)::decimal)\n                                                from (SELECT id_caso,count(*)\n                                                FROM gestion.responsable\n                                                where id_caso in (select a.id\n                                                from gestion.caso a\n                                                inner join gestion.category g on g.id = a.id_categoria\n                                                inner join gestion.historico d on d.id_caso = a.id\n                                                inner join gestion.responsable e on e.id_caso = a.id\n                                                inner join gestion.resolutorio r on r.id = e.id_resolutorio\n                                                where r.id in (SELECT id \n\t\t\t\t\t\t\t\t\t\t\t                                         FROM gestion.resolutorio\n\t\t\t\t\t\t\t\t\t\t\t                                         where nombre in ($resolutorea)\n\t\t\t\t\t\t\t\t\t\t\t                                         and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\n                                                and g.name in ($subcateg)\n                                                --and d.active = 1\n                                                and e.principal is true\n                                                and d.id_estatus in (3,4,6,8))\n                                                group by id_caso\n                                                HAVING count(id_caso) > 0) as Total))::decimal,2) as porcentaje; "
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS CON RESPONSABILIDAD COMPARTIDA  ($resolutorg )",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT a.nombre ::Text \"GOBERNACION UNICOS\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n    \ta.direccion::Text \"DIR\",\n      \ta.descripcion::TEXT \"DESCRIP\", \n\t  \tf.name /*f.nombre::Text*/ \"CATEGORIA\",\n\t  \tg.name::Text \"SUBCATEG\",\n\t  \t--null /*z.latitud::decimal*/ \"LATITUD\",\n\t  \t--null /*z.longitud::decimal*/ \"LONGITUD\",\n\t  \tto_char(a.fecha,'dd-mm-YY') as \"FECHA GENERADO\",\n    \tto_char(h.fecha_registro,'dd-mm-YY') as \"FECHA ULTIMO ESTATUS\",\n\t   case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n\t\ti.nombre::Text \"ESTATUS\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN  gestion.historico h ON h.id_caso = a.id\n            inner JOIN  gestion.estatus i ON h.id_estatus = i.id \n          --  inner join gestion.ubicacion z on z.id_caso = a.id\n            LEFT JOIN  gestion.responsable j ON j.id_caso = h.id_caso --and j.id_user is not null\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            --LEFT JOIN  public.user_detail v ON w.id = v.user_id\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n      where -- h.active = 1\n\t\t\t k.nombre in ($resolutorg)\n\t\t\tand f.name in ($subcateg)\n\t\t\tand j.principal is true\n\t\t\tand h.id_estatus in (3,4,6,7,8)"
    },
    {
     "rawSql": "SELECT a.nombre::Text \"ALCALDIA UNICOS\",\n    \te.cedula::Text \"CEDULA\",\n    \te.nombre::TEXT \"DENUNCIANTE\",\n    \te.telefono::Text \"TELEFONO\",\n    \tb.nombre::Text \"ESTADO\",\n    \tc.nombre::Text \"MUNICIPIO\",\n    \td.nombre::Text \"PARROQ\",\n    \ta.direccion::Text \"DIR\",\n    \ta.descripcion::TEXT \"DESCRIP\", \n\t  \tf.name::Text \"CATEGORIA\",\n\t    g.name::Text \"SUBCATEG\",\n\t  \t--z.latitud::decimal \"LATITUD\",\n\t  --\tz.longitud::decimal \"LONGITUD\",\n\t  \tto_char(a.fecha,'dd-mm-YY') as \"FECHA GENERADO\",\n    \tto_char(h.fecha_registro,'dd-mm-YY') as \"FECHA ULTIMO ESTATUS\",\n\t  case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n\t\ti.nombre::Text \"ESTATUS\"\n        FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN  gestion.historico h ON h.id_caso = a.id\n            inner JOIN  gestion.estatus i ON h.id_estatus = i.id\n            --inner join gestion.ubicacion z on z.id_caso = a.id\n            inner JOIN  gestion.responsable j ON j.id_caso = h.id_caso --and j.id_user is not null\n            inner JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n\t\t\tinner JOIN  gestion.resolutorio kk ON kk.id_estado = k.id_estado \n            LEFT JOIN  public.user w ON w.id = j.id_user\n            --LEFT JOIN  public.user_detail v ON w.id = v.user_id\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n      where  /*h.active = 1\n\t\t\tand*/ k.nombre in ($resolutorea) and kk.nombre in ($resolutorg)\n\t\t\tand f.name in ($subcateg)\n\t\t\tand j.principal is true\n\t\t\tand h.id_estatus in (3,4,6,7,8)\n      --and h.active = 1"
    }
   ]
  },
  {
   "title": "ALCALDIAS ($resolutorg)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \n    m.nombre::Text \"ALCALDIAS\",\n\t\tsum(CASE WHEN d.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\n\t\tsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \n\t\ttrunc(sum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\n\t\tfrom gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id\n\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\n\t\tinner join gestion.municipio m on m.id = z.id_municipio\n\t\twhere  /*d.active = 1 \n\t\tand*/ d.id_estatus in (1,2,3,4,6,7,8)\n\t\tand z.id_tipo_resolutorio in (2)\n\t\tand z.nombre in ($resolutorea) and zz.nombre in ($resolutorg)\n\t\tand e.principal is true\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" DESC"
    }
   ]
  },
  {
   "title": "GOBERNACION POR PARROQUIAS ($resolutorg)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \n\t\tm.nombre::Text \"PARROQUIAS\",\n\t\tsum(CASE WHEN d.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\n\t\tsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \n\t\ttrunc(sum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\n\t\tfrom gestion.caso a\n\t\tinner join gestion.parroquia m on m.id = a.id_parroquia\n\t\tinner join gestion.historico d on d.id_caso = a.id\n\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\n\t\t--inner join gestion.resolutorio zz on zz.id =  z.id_estado\n\t\twhere /* d.active = 1 and*/ d.id_estatus in (1,2,3,4,6,7,8)\n\t\t--and e.id_resolutorio = 125 \n\t\tand z.nombre in ($resolutorg) --and zz.nombre in ($resolutorg)\n\t\tand e.principal = true\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" desc"
    }
   ]
  },
  {
   "title": "ALCALDIAS POR PARROQUIAS ($resolutorea)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \n\t\tm.nombre::Text \"PARROQUIAS\",\n\t\tsum(CASE WHEN d.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\n\t\tsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \n\t\ttrunc(sum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\n\t\tfrom gestion.caso a\n\t\tinner join gestion.parroquia m on m.id = a.id_parroquia\n\t\tinner join gestion.historico d on d.id_caso = a.id\n\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\n\t\twhere  /*d.active = 1 and*/ d.id_estatus in (1,2,3,4,6,7,8)\n\t\t--and e.id_resolutorio = 125 \n\t\tand z.nombre in ($resolutorea) and zz.nombre in ($resolutorg)\n\t\tand e.principal = true\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" desc"
    }
   ]
  }
 ]
}