{
 "title": "GOBERNACION DEL ESTADO GUÁRICO V3",
 "time": { "from": "2021-02-25T05:26:07.561Z", "to": "2023-12-16T05:26:07.561Z" },
 "templating": {
  "list": [
   {
    "name": "subcateg",
    "label": "SUB CATEG",
    "query": "SELECT  c.name FROM gestion.category c\n inner join gestion.category cc on cc.id = c.parent where cc.parent is null and c.id <= 17\n order by c.id asc"
   },
   {
    "name": "resolutorg",
    "label": "GOBERNACIONES",
    "query": "SELECT nombre FROM gestion.resolutorio a where a.id_tipo_resolutorio = 1  and id = 11"
   },
   {
    "name": "resolutorea",
    "label": "ALCALDIAS",
    "query": "SELECT a.nombre FROM gestion.resolutorio a inner join gestion.resolutorio b on a.id_estado = b.id_estado where a.id_tipo_resolutorio = 2 and b.nombre in ($resolutorg) "
   }
  ]
 },
 "panels": [
  {
   "title": "CASOS  REGIONALES",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select (SELECT(  \r\nSELECT COUNT(*) \r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.nombre in ($resolutorg)\r\n                        and g.name in ($subcateg)\r\n                        --and d.active = 1\r\n                        and e.principal is true\r\n                        and d.id_estatus in (3,4,6,8))\r\n      group by id_caso\r\n      HAVING count(id_caso) >= 1) as Total)\r\n+\r\n(SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.id in (SELECT id \r\n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\r\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorg)\r\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n                        and g.name in ($subcateg)\r\n                        --and d.active = 1\r\n                        and e.principal is true\r\n                        and d.id_estatus in (3,4,6,8))\r\n      group by id_caso\r\n      HAVING count(id_caso) > 0) as Total) CASOS_REGIONALES)"
    }
   ]
  },
  {
   "title": "GOBERNACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category  g on g.id = a.id_categoria \r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.nombre in ($resolutorg)\r\n                        and g.name in ($subcateg)\r\n                        and d.id_estatus  = 1\r\n                        and e.principal is true\r\n                        and d.id_estatus in (3,4,6,8))\r\ngroup by id_caso\r\nHAVING count(id_caso) = 1) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.nombre in ($resolutorg)\r\n                        and g.name in ($subcateg)\r\n                        and e.principal is true\r\n                        and d.id_estatus in (6)\r\n                        and a.verificado is null\r\n                        and (a.feedback < 3 or a.feedback is null))\r\n      group by id_caso \r\n      HAVING count(id_caso) = 1) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.nombre in ($resolutorg)\r\n                        and g.name in ($subcateg)\r\n                        and e.principal is true\r\n                        and d.id_estatus in (6)\r\n                        and (a.feedback >= 3   or  a.verificado = 'SI'))\r\n      group by id_caso\r\n      HAVING count(id_caso) = 1) as Total "
    }
   ]
  },
  {
   "title": "GOBERNACIÓN %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(((SELECT (COUNT(*)::decimal)as atendido\r\n                from (SELECT id_caso,count(*)\r\n                      FROM gestion.responsable\r\n                      where id_caso in (select a.id\r\n                      from gestion.caso a\r\n                      inner join gestion.category g on g.id = a.id_categoria\r\n                      inner join gestion.historico d on d.id_caso = a.id\r\n                      inner join gestion.responsable e on e.id_caso = a.id\r\n                      inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                      where r.nombre in ($resolutorg)\r\n                      and g.name in ($subcateg)\r\n                      and e.principal is true\r\n                      and d.id_estatus in (6)\r\n                      and (a.feedback >= 3   or  a.verificado = 'SI'))\r\n                      group by id_caso\r\n                      HAVING count(id_caso) = 1) as Total)*100/(SELECT (COUNT(*)::decimal)\r\n                                                                from (SELECT id_caso,count(*)\r\n                                                                FROM gestion.responsable\r\n                                                                where id_caso in (select a.id\r\n                                                                \t\t\t\t  from gestion.caso a\r\n                                                                \t\t\t\t\tinner join gestion.category g on g.id = a.id_categoria\r\n                                                                \t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id\r\n                                                               \t\t\t\t\t\tinner join gestion.responsable e on e.id_caso = a.id\r\n                                                                \t\t\t\t\tinner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                                                                \t\t\t\t  where r.nombre in ($resolutorg)\r\n                                                                \t\t\t\t  and g.name in ($subcateg)\r\n                                                                \t\t\t\t  and e.principal is true\r\n                                                                \t\t\t\t  and d.id_estatus in (3,4,6,8))\r\n                                                                \t\t\t\t  group by id_caso\r\n                                                                \t\t\t\t  HAVING count(id_caso) = 1)as Total))::decimal,2) as porcentaje"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria \r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.id in (SELECT id \r\n\t\t\t\t\t\t\t\t\t\tFROM gestion.resolutorio\r\n\t\t\t\t\t\t\t\t\t\twhere nombre in ($resolutorea)\r\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n                        and g.name in ($subcateg)\r\n\t\t\t\t\t          and e.principal is true\r\n                    and d.id_estatus in (3,4,6,8))\r\n group by id_caso\r\n      HAVING count(id_caso) > 0) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria \r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.id in (SELECT id \r\n\t\t\t\t\t\t\t\t\t   FROM gestion.resolutorio\r\n\t\t\t\t\t\t\t\t\t   where nombre in ($resolutorea)\r\n\t\t\t\t\t\t\t\t\t   and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n\t\t\t\t\t\t\t\t\t   and g.name in ($subcateg)\r\n                     and e.principal is true\r\n                     and d.id_estatus in (6)\r\n                     and a.verificado is null \r\n                     and (a.feedback < 3 or a.feedback is null))\r\n      group by id_caso\r\n      HAVING count(id_caso) > 0) as Total"
    }
   ]
  },
  {
   "title": "ATENDIDOS CON VALORACION",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nfrom (SELECT id_caso,count(*)\r\n      FROM gestion.responsable\r\n      where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.id in (SELECT id \r\n\t\t\t\t\t         FROM gestion.resolutorio\r\n\t\t\t\t\t\t   where nombre in ($resolutorea)\r\n\t\t\t\t\t         and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n\t\t\t\t\t\t   and g.name in ($subcateg)\r\n                        and e.principal is true\r\n                        and d.id_estatus in (6)\r\n                        and (a.feedback >= 3   or  a.verificado = 'SI'))\r\n      group by id_caso\r\n      HAVING count(id_caso) > 0) as Total\r\n"
    }
   ]
  },
  {
   "title": "ALCALDÍA  %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(((SELECT COUNT(*)\r\n                from (SELECT id_caso,count(*)\r\n                FROM gestion.responsable\r\n                where id_caso in (select a.id\r\n                        from gestion.caso a\r\n                        inner join gestion.category g on g.id = a.id_categoria\r\n                        inner join gestion.historico d on d.id_caso = a.id\r\n                        inner join gestion.responsable e on e.id_caso = a.id\r\n                        inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                        where r.id in (SELECT id \r\n\t\t\t\t\t\t\t\t\t\t\t                 FROM gestion.resolutorio\r\n\t\t\t\t\t\t\t\t\t\t\t                 where nombre in ($resolutorea)\r\n\t\t\t\t\t\t\t\t\t\t\t                 and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n                        and g.name in ($subcateg)\r\n                       -- and d.active = 1\r\n                        and e.principal is true\r\n                        and d.id_estatus in (6)\r\n                        and (a.feedback >= 3   or  a.verificado = 'SI'))\r\n      group by id_caso\r\n      HAVING count(id_caso) > 0) as Total)*100/(SELECT (COUNT(*)::decimal)\r\n                                                from (SELECT id_caso,count(*)\r\n                                                FROM gestion.responsable\r\n                                                where id_caso in (select a.id\r\n                                                from gestion.caso a\r\n                                                inner join gestion.category g on g.id = a.id_categoria\r\n                                                inner join gestion.historico d on d.id_caso = a.id\r\n                                                inner join gestion.responsable e on e.id_caso = a.id\r\n                                                inner join gestion.resolutorio r on r.id = e.id_resolutorio\r\n                                                where r.id in (SELECT id \r\n\t\t\t\t\t\t\t\t\t\t\t                                         FROM gestion.resolutorio\r\n\t\t\t\t\t\t\t\t\t\t\t                                         where nombre in ($resolutorea)\r\n\t\t\t\t\t\t\t\t\t\t\t                                         and id_estado in (SELECT id FROM gestion.resolutorio where nombre in ($resolutorg)))\r\n                                                and g.name in ($subcateg)\r\n                                                --and d.active = 1\r\n                                                and e.principal is true\r\n                                                and d.id_estatus in (3,4,6,8))\r\n                                                group by id_caso\r\n                                                HAVING count(id_caso) > 0) as Total))::decimal,2) as porcentaje;\r\n                                                "
    }
   ]
  },
  { "title": "DETALLADO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "LISTADO DE CASOS CON RESPONSABILIDAD COMPARTIDA  ($resolutorg )",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT a.nombre::Text \"GOBERNACION UNICOS\",\r\n    \te.cedula::Text \"CEDULA\",\r\n    \te.nombre::TEXT \"DENUNCIANTE\",\r\n    \te.telefono::Text \"TELEFONO\",\r\n    \tb.nombre::Text \"ESTADO\",\r\n    \tc.nombre::Text \"MUNICIPIO\",\r\n    \td.nombre::Text \"PARROQ\",\r\n    \ta.descripcion::TEXT \"DESCRIP\", \r\n\t  \tf.name::Text \"CATEGORIA\",\r\n\t  \t--g.nombre::Text \"SUBCATEG\",\r\n\t  --\tcase when m.nombre is null then 'Sin ExtCateg' else m.nombre end::Text \"EXTCATEG\", \r\n\t\t  i.nombre::Text \"ESTATUS\",\r\n\t\t   k.nombre::Text \"RESPONSABLE\",\r\n\t\t  to_char(a.fecha,'dd-mm-YY') as \"FECHA GENERADO\",\r\n    \tto_char(h.fecha_registro,'dd-mm-YY') as \"FECHA ULTIMO ESTATUS\",\r\n\t\t  CASE WHEN h.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 'VERIFICADO' ELSE 'NO VERIFICADO' END AS \"VERIFICACION\"\r\n        FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            --inner join gestion.sub_categoria g on g.id = a.id_sub_categoria\r\n            inner JOIN  gestion.historico h ON h.id_caso = a.id\r\n            inner JOIN  gestion.estatus i ON h.id_estatus = i.id            \r\n           LEFT JOIN  gestion.responsable j ON j.id_caso = h.id_caso and j.principal is true\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT join gestion.resolutorio zz on zz.id =  k.id_estado \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n           -- LEFT JOIN  public.user_detail v ON w.id = v.user_id\r\n           --LEFT JOIN  gestion.extra_categoria m ON m.id = a.id_extra_categoria\r\n      \t\twhere k.nombre in ($resolutorg, $resolutorea) and g.name in ($subcateg)\r\n      \t\tand zz.nombre in ($resolutorg)\r\n      \t\t     and j.principal is true and h.id_estatus in (3,4,6,8)"
    }
   ]
  },
  {
   "title": "ALCALDIAS ($resolutorg)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "Select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \r\n    m.nombre::Text \"ALCALDIAS\",\r\n\t\tsum(CASE WHEN d.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\n\t\tsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \r\n\t\ttrunc(sum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\r\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\n\t\tfrom gestion.caso a\r\n\t\tinner join gestion.historico d on d.id_caso = a.id\r\n\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso\r\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\r\n\t\tinner join gestion.municipio m on m.id = z.id_municipio\r\n\t\twhere d.id_estatus in (1,2,3,4,6,7,8)\r\n\t\tand z.id_tipo_resolutorio in (2)\r\n\t\tand z.nombre in ($resolutorea) \r\n\t\tand zz.nombre in ($resolutorg)\r\n\t\tand e.principal is true\r\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" DESC;"
    }
   ]
  },
  {
   "title": "PARROQUIAS ($resolutorea)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select --row_number() OVER (ORDER BY m.nombre) AS \"NUM\", \r\n\t\tm.nombre::Text \"PARROQUIAS\",\r\n\t\tsum(CASE WHEN d.id_estatus in (1,2,3,4,6,7,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\r\n\t\tsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", \r\n\t\ttrunc(sum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI')\r\n\t\tTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\r\n\t\tfrom gestion.caso a\r\n\t\tinner join gestion.parroquia m on m.id = a.id_parroquia\r\n\t\tinner join gestion.historico d on d.id_caso = a.id\r\n\t\tinner join gestion.responsable e on e.id_caso =  d.id_caso\r\n\t\tinner join gestion.resolutorio z on z.id =  e.id_resolutorio\r\n\t\tinner join gestion.resolutorio zz on zz.id =  z.id_estado\r\n\t\twhere  d.id_estatus in (1,2,3,4,6,7,8)\r\n\t\tand z.nombre in ($resolutorea) \r\n\t\tand zz.nombre in ($resolutorg)\r\n\t\tand e.principal = true\r\n\t\tgroup by m.nombre order by \"% EFECTIVIDAD %\" desc"
    }
   ]
  }
 ]
}