{
 "title": "GOBERNACIONES Y ALCALDÍAS DETALLADO V3",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estado",
    "label": "Estado",
    "query": "SELECT nombre FROM gestion.estado where id < 26 order by id"
   },
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "SELECT a.nombre  FROM gestion.municipio a inner join gestion.estado b on a.id_estado = b.id where  b.nombre in ($estado) "
   },
   {
    "name": "parroquia",
    "label": "Parroquia",
    "query": "SELECT a.nombre FROM gestion.parroquia a \n\tinner join gestion.municipio b on a.id_municipio = b.id \n\tinner join gestion.estado c on c.id = b.id_estado\n\twhere  c.nombre in ($estado)  and b.nombre in ($municipio)"
   }
  ]
 },
 "panels": [
  {
   "title": "REPORTE GENERAL 1X10 DEL BUEN GOBIERNO ($estado)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://i.ibb.co/jzLgsT1/PLAN-1x10.png\" alt=\"texto_alternativo\" width=\"100%\" height=\"100%\">\n"
   },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "RECIBIDOS POR VENAPP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n  inner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado b on b.id = a.id_estado\n\tinner join gestion.municipio c on c.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n  where b.nombre in ($estado) AND c.nombre in ($municipio) AND e.nombre in ($parroquia)\n  and $__timeFilter(a.fecha)\n  --AND d.active = 1"
    }
   ]
  },
  {
   "title": "ASIGNADOS MINISTERIOS ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (3,4)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand $__timeFilter(a.fecha)\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) \n"
    }
   ]
  },
  {
   "title": "ASIGNADOS GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (1,2)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand $__timeFilter(a.fecha)\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "INDICE DE SATISFACCIÓN GLOBAL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\twhere \n\t\t\t--b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,453,553,561,597,563,566,354,503,599)\n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\tand $__timeFilter(a.fecha)\n\t\t\t/*and d.active = 1*/ and d.id_estatus in (6) \n\t\t\t--and a.feedback is not null\t"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "<img src=\"https://i.ibb.co/jzLgsT1/PLAN-1x10.png\" alt=\"texto_alternativo\" width=\"100%\" height=\"100%\">\n"
   },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "SISTEMA 1X10",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.historico d on d.id_caso = a.id  \n    inner join gestion.estado b on b.id = a.id_estado\n\t  inner join gestion.municipio c on c.id = a.id_municipio\n\t  inner join gestion.parroquia e on e.id = a.id_parroquia\n  where --cc.id_tipo_resolutorio in (1,2,3,4) and\n    b.nombre in ($estado) AND c.nombre in ($municipio) \n    and $__timeFilter(a.fecha)\n    AND e.nombre in ($parroquia)\n    /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "ATENDIDOS-MINISTERIOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (3,4)\n\tand $__timeFilter(a.fecha)\n\t--and\tb.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,553,561,597,563,566,599,503,453)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ATENDIDOS-GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere c.id_tipo_resolutorio in (1,2)\n\tand $__timeFilter(a.fecha)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "POR ATENDER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.historico d on d.id_caso = a.id \r\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \r\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\tinner join gestion.estado f on f.id = a.id_estado\r\n\tinner join gestion.municipio g on g.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\twhere c.id_tipo_resolutorio in (1,2,3,4)\r\n\tand $__timeFilter(a.fecha)\r\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) \r\n)\r\n-\r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.historico d on d.id_caso = a.id \r\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \r\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\tinner join gestion.estado f on f.id = a.id_estado\r\n\tinner join gestion.municipio g on g.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\twhere c.id_tipo_resolutorio in (1,2,3,4) and $__timeFilter(a.fecha)\r\n\t--and\tb.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,553,561,597,563,566,599,503,453)\r\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')) as total"
    }
   ]
  },
  {
   "title": "POR ATENDER-MINISTERIOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.historico d on d.id_caso = a.id \r\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \r\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\tinner join gestion.estado f on f.id = a.id_estado\r\n\tinner join gestion.municipio g on g.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\twhere c.id_tipo_resolutorio in (3,4)\r\n\tand $__timeFilter(a.fecha)\r\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) \r\n)\r\n-\r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.historico d on d.id_caso = a.id \r\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \r\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\tinner join gestion.estado f on f.id = a.id_estado\r\n\tinner join gestion.municipio g on g.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\twhere c.id_tipo_resolutorio in (3,4) \r\n\tand $__timeFilter(a.fecha)\r\n\t--and\tb.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,553,561,597,563,566,599,503,453)\r\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')) as total"
    }
   ]
  },
  {
   "title": "POR ATENDER-GOB-ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.historico d on d.id_caso = a.id \r\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \r\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\tinner join gestion.estado f on f.id = a.id_estado\r\n\tinner join gestion.municipio g on g.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\twhere c.id_tipo_resolutorio in (1,2) and $__timeFilter(a.fecha)\r\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) )\r\n-\r\n(SELECT count(a.id)\r\n\tFROM gestion.caso a\r\n\tinner join gestion.historico d on d.id_caso = a.id \r\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \r\n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\r\n\tinner join gestion.estado f on f.id = a.id_estado\r\n\tinner join gestion.municipio g on g.id = a.id_municipio\r\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\r\n\twhere c.id_tipo_resolutorio in (1,2) and $__timeFilter(a.fecha)\r\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n\tand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')) as total"
    }
   ]
  },
  {
   "title": "TOTAL CASOS ATENDIDOS 1X10 DEL BUEN GOBIERNO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\twhere c.id_tipo_resolutorio in (1,2,3,4) and $__timeFilter(a.fecha) and\n\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true \n\t--and d.active = 1 \n\tand d.id_estatus in (6) and (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL ATENDIDOS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1,2,3,4) and $__timeFilter(a.fecha)\n\t\t\t\t\t\t\t\t\t\t   \t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t  --and a.id_sub_categoria in (1,2,3,4,5,6,7,8) \n\t\t\t\t\t\t\t\t\t\t\t\t  and b.principal is true /*and d.active = 1*/\n\t\t\t\t\t\t\t\t\t\t\t\t  and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (1,2,3,4)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand $__timeFilter(a.fecha)\n\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\t--and d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL  MINISTERIOS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (3,4) and $__timeFilter(a.fecha)\n\t\t\t\t\t\t\t\t\t\t   \t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t  --and a.id_sub_categoria in (1,2,3,4,5,6,7,8) \n\t\t\t\t\t\t\t\t\t\t\t\t  and b.principal is true /*and d.active = 1*/\n\t\t\t\t\t\t\t\t\t\t\t\t  and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (3,4)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\tand $__timeFilter(a.fecha)\n\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\t--and d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL GOB-ALCALDIAS %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t   \t\tinner join gestion.estado f on f.id = a.id_estado\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1,2) and $__timeFilter(a.fecha)\n\t\t\t\t\t\t\t\t\t\t   \tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true /*and d.active = 1*/\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\t\n\t\tinner join gestion.estado f on f.id = a.id_estado\n\t\tinner join gestion.municipio g on g.id = a.id_municipio\n\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\t\twhere c.id_tipo_resolutorio in (1,2) and $__timeFilter(a.fecha)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\t--and d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 18, "w": 2, "x": 0, "y": 13 },
   "options": {
    "content": "<img src=\"https://i.ibb.co/bvqtPfs/BANNER-LATERAL-3-Mesa-de-trabajo-33.png\" alt=\"texto_alternativo\" width=\"100%\" height=\"100%\">\n"
   },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id \n                                            inner join gestion.responsable b on b.id_caso =  d.id_caso\t\t\n                      \t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                      \t\t\t\t\t\t\t\t\t\t\tinner join gestion.municipio g on g.id = a.id_municipio\n                      \t\t\t\t\t\t\t\t\t\t\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\t\t\t\t\t\t\t\t\t\t\n                                            where b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n                                            and $__timeFilter(a.fecha)\n\t\t\t\t\t\t\t\t\t\t\t                      and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true --and d.active = 1\n                                            and d.id_estatus in (3,4,6,8) )::decimal, 2) as porcentaje\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand $__timeFilter(a.fecha)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\t/*and d.active = 1*/ and d.id_estatus in (6) \n\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (597,563,566) and $__timeFilter(a.fecha)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (597,563,566) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (354) and $__timeFilter(a.fecha)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (354) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / ( SELECT count(a.id) \n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id\n                                            inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                            inner join gestion.estado f on f.id = a.id_estado\n                                            inner join gestion.municipio g on g.id = a.id_municipio\n                                            inner join gestion.parroquia e on e.id = a.id_parroquia\n                                            where b.id_resolutorio in (553) and $__timeFilter(a.fecha)\n                                            and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                            and b.principal is true\n                                            --and d.active = 1\n                                            and d.id_estatus in (3,4,6,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (553) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (599) and $__timeFilter(a.fecha)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (599) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2  or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (503) and $__timeFilter(a.fecha)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (503) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-UNIVERSI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           inner join gestion.estado f on f.id = a.id_estado\n                                           inner join gestion.municipio g on g.id = a.id_municipio\n                                           inner join gestion.parroquia e on e.id = a.id_parroquia\n                                           where b.id_resolutorio in (561) and $__timeFilter(a.fecha)\n                                           and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,8))::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (561) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc((count(a.id)::decimal * 100) / ( SELECT count(a.id)\n                                              FROM gestion.caso a\n                                              inner join gestion.historico d on d.id_caso = a.id\n                                              inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                              inner join gestion.estado f on f.id = a.id_estado\n                                              inner join gestion.municipio g on g.id = a.id_municipio\n                                              inner join gestion.parroquia e on e.id = a.id_parroquia\n                                              where b.id_resolutorio in (453) and $__timeFilter(a.fecha)\n                                              and f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n                                              and b.principal is true\n                                              --and d.active = 1\n                                              and d.id_estatus in (3,4,6,8) )::decimal,2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (453) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOBER",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                        inner join gestion.municipio g on g.id = a.id_municipio\n                        inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha)\n\t\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\t\t\t\t\t\t\t\t\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\t--and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\twhere c.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\t--and d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / ( SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\t\tinner join gestion.estado f on f.id = a.id_estado\n                        inner join gestion.municipio g on g.id = a.id_municipio\n                        inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\t\t\t\t\t\t\t\t\t\twhere c.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha)\n\t\t\t\t\t\t\t\t\t\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t\t\t\t\t\t\t\t\t\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\t\t\t\t\t\t\t\t\t\t\tand b.principal is true\n\t\t\t\t\t\t\t\t\t\t\t\t--and d.active = 1\n\t\t\t\t\t\t\t\t\t\t\t\tand d.id_estatus in (3,4,6,8))::Decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\tinner join gestion.estado f on f.id = a.id_estado\n    inner join gestion.municipio g on g.id = a.id_municipio\n    inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\twhere c.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha)\n\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\t\t--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\n\t\tand b.principal is true\n\t\t--and d.active = 1\n\t\tand d.id_estatus in (6) \n\t\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 18, "w": 2, "x": 22, "y": 13 },
   "options": {
    "content": "<img src=\"https://i.ibb.co/bvqtPfs/BANNER-LATERAL-3-Mesa-de-trabajo-33.png\" alt=\"texto_alternativo\" width=\"100%\" height=\"100%\">\n"
   },
   "targets": [
    { "rawSql": "SELECT " }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\twhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand $__timeFilter(a.fecha)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true\t/*and d.active = 1*/ and d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (597,563,566) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8)"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (354) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8)"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (553) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (599) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8)"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (503) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8)"
    }
   ]
  },
  {
   "title": "EDUCA-UNIVERS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (561) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,6,8)"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (453) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "GOBER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.historico d on d.id_caso = a.id \r\ninner join gestion.responsable b on b.id_caso =  d.id_caso \r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\n--and d.active = 1\r\nand d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.historico d on d.id_caso = a.id \r\ninner join gestion.responsable b on b.id_caso =  d.id_caso \r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\n--and d.active = 1\r\nand d.id_estatus in (3,4,6,8) "
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =10)--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand $__timeFilter(a.fecha)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\t/*and d.active = 1*/\tand d.id_estatus in (6) \n\tand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =9) --(597,563,566) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =8) --(354) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =14)--(553) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =5)--(599) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =6)--(503) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-UNIVERSI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =15)--(561) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =13)--(453) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GOBER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere c.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere c.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 2   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso =  d.id_caso \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\t\n\twhere b.id_resolutorio in ( SELECT id FROM gestion.resolutorio where id_categoria =10)--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand $__timeFilter(a.fecha)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\tand b.principal is true\t/*and d.active = 1*/ and d.id_estatus in (3,4,8) "
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =9)--(597,563,566) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,8)"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =8)--(354) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,8)"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =14)--(553) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,8) "
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =5)--(599)\nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,8)"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =6)--(503) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,8)"
    }
   ]
  },
  {
   "title": "EDUCA-UNIVERS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =15)--(561) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (3,4,8)"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =13)--(453) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,8) "
    }
   ]
  },
  {
   "title": "GOBER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.historico d on d.id_caso = a.id \r\ninner join gestion.responsable b on b.id_caso =  d.id_caso \r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\n--and d.active = 1\r\nand d.id_estatus in (3,4,8) "
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\r\nFROM gestion.caso a\r\ninner join gestion.historico d on d.id_caso = a.id \r\ninner join gestion.responsable b on b.id_caso =  d.id_caso \r\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\r\ninner join gestion.estado f on f.id = a.id_estado\r\ninner join gestion.municipio g on g.id = a.id_municipio\r\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\r\nwhere c.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha)\r\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\r\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\r\nand b.principal is true\r\n--and d.active = 1\r\nand d.id_estatus in (3,4,8) "
    }
   ]
  },
  {
   "title": "MIN-AGUAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.historico d on d.id_caso = a.id  \n\tinner join gestion.estado f on f.id = a.id_estado\n\tinner join gestion.municipio g on g.id = a.id_municipio\n\tinner join gestion.parroquia e on e.id = a.id_parroquia\n\twhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =10)--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\tand $__timeFilter(a.fecha)\n\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n\tand b.principal is true\t/*and d.active = 1*/\tand d.id_estatus in (6) \n\tAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))\n"
    }
   ]
  },
  {
   "title": "TELECOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =9)--(597,563,566)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6) and $__timeFilter(a.fecha)\nAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "MIN-ELECTRI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =8)--(354) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "EDUCA-BASICA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =14)--(553) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\n\tAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "G-COMUNAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =5)--(599) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\n\tAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "G-DIRECTO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =6)--(503) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\n\tAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "MIN-UNIVERSI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =15)--(561)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true /*and d.active = 1*/ and d.id_estatus in (6)\nAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "MIN-SALUD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =13)--(453) \nand $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\n\tAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "GOBER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\t\nwhere c.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \n\tAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "ALCALDIAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \ninner join gestion.resolutorio c on c.id = b.id_resolutorio\ninner join gestion.estado f on f.id = a.id_estado\ninner join gestion.municipio g on g.id = a.id_municipio\ninner join gestion.parroquia e on e.id = a.id_parroquia\nwhere c.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha)\nand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\n--and a.id_sub_categoria in (1,2,3,4,5,6,7,8)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nAND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null))"
    }
   ]
  },
  {
   "title": "SATISF-AGUAS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =10)--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true and $__timeFilter(a.fecha)\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-TELECOM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =9)--(597,563,566) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-ELECTRI",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =8)--(354) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-BASICA",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =14)--(553) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-G-COMUNAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =5)--(599) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-G-DIRECTO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =6)--(503) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-UNIVERS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =15)--(561) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-SALUD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  b.id_resolutorio in (SELECT id FROM gestion.resolutorio where id_categoria =13)--(453) \n\t\t\tand $__timeFilter(a.fecha)\n\t\t\tand f.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-GOBER",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  \n\t\t\t--b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t\t\tc.id_tipo_resolutorio in (1) and $__timeFilter(a.fecha) AND \n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  },
  {
   "title": "SATISF-ALCAL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT round(avg(a.feedback))::Text \"Average\" \n\t\t\tFROM gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable b on b.id_caso =  d.id_caso\n\t\t\tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\t\t\tinner join gestion.estado f on f.id = a.id_estado\n      inner join gestion.municipio g on g.id = a.id_municipio\n      inner join gestion.parroquia e on e.id = a.id_parroquia\n\t\t\twhere  \n\t\t\t--b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t\t\tc.id_tipo_resolutorio in (2) and $__timeFilter(a.fecha) AND \n\t\t\tf.nombre in ($estado) AND g.nombre in ($municipio) AND e.nombre in ($parroquia)\t\n\t\t\tand b.principal is true\n\t\t\t--and d.active = 1 \n\t\t\tand d.id_estatus in (6) \n\t\t\tand a.feedback is not null\t"
    }
   ]
  }
 ]
}