{
 "title": "Cartelera METRO DE CARACAS V3",
 "time": { "from": "2022-09-02T19:42:50.269Z", "to": "2022-09-02T22:22:50.269Z" },
 "panels": [
  {
   "title": "LISTADO DE CASOS  DE METRO DE CARACAS EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "\r\n\tSELECT a.nombre::Text \"CODIGO CASO\", \r\n     \t\te.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", --g.nombre::Text \"SUBCATEG\",case when m.nombre is null then 'Sin ExtCateg' else m.nombre end::Text \"EXTCATEG\", \r\n      --case when n.nombre is null then 'SIN CATEG 5TO NIVEL' else n.nombre end::Text \"CATEG ADI\",\r\n\t  -- case when nv.nombre is null then 'SIN CATEG DE 5TO NIVEL' else nv.nombre end::Text \"CATEG 5TO NIVEL\",\r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n\t\t\tto_char(a.fecha, 'dd-mm-YY')::Text \"FECHA CREACION\",\r\n\t\t\tto_char(h.fecha_registro, 'dd-mm-YY')::Text \"FECHA INCIDENCIA\",\r\n      case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\"\r\n      --case when v.name is null then 'Analizando' else (v.name || ' ' || v.last_name ) end::Text \"RESPONSABLE\",\r\n\t\t\t--v.phone::Text \"TELF. RESP\"\r\n      FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t-- inner join lista.ubch z on z.cedula = e.cedula usuario ubch\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            --inner join gestion.sub_categoria g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.historico h ON h.id_caso = a.id\r\n            inner JOIN gestion.estatus i ON h.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = h.id_caso and j.principal = true\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n           -- LEFT JOIN  public.user_detail v ON w.id = v.user_id\r\n            --LEFT JOIN  gestion.extra_categoria m ON m.id = a.id_extra_categoria\r\n            --LEFT JOIN  gestion.adicional_categoria n ON n.id = a.id_adicional_categoria\r\n\t\t\t--LEFT JOIN  gestion.categoria_n_v nv ON nv.id = a.id_categoria_n_v\r\n            where h.id_estatus in (1,2,3,4,6,7,8) \r\n\t\t\t--and h.active = 1 \r\n\t\t\tand a.id_categoria in (3)"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE METRO DE CARACAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_categoria in (3)\n    --and d.active = 1"
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 2 },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_categoria in (3)\n    --and d.active = 1\n    and d.id_estatus in (5) "
      }
     ]
    },
    {
     "title": "CASOS VALIDADO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 11, "y": 2 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_categoria in (3)\n    --and d.active = 1\n    and a.id_origen = 2 "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_categoria in (3)\n    --and d.active = 1\n   and d.id_estatus in (1,2,3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "EN RECIBIDO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\nwhere \na.id_categoria in (3) \n--and d.active = 1\nand d.id_estatus in (1,2)"
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\nwhere \na.id_categoria in (3) \n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 14, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\nwhere \na.id_categoria in (3)\n--and d.active = 1\nand d.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\nwhere \na.id_categoria in (3)\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           where \n                                           a.id_categoria in (3)\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere \na.id_categoria in (3)\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "        SELECT m.name as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.historico d on d.id_caso = a.id  \n                inner join gestion.denunciante e on e.id = a.id_denunciante\n               \tinner JOIN gestion.category m ON m.id = a.id_extra_categoria               \n            where d.id_estatus in (1,2,3,4,6,7,8) --and d.active = 1\n            and a.id_categoria in (3) \n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
     "targets": [
      {
       "rawSql": "     SELECT m.name as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.historico d on d.id_caso = a.id  \n                inner join gestion.denunciante e on e.id = a.id_denunciante\n               \tinner JOIN gestion.category m ON m.id = a.id_extra_categoria               \n            where d.id_estatus in (6) /*and d.active = 1*/ and a.id_categoria in (3)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\nselect  to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'YYYY-mm-dd') as fechao,\n\tcount(a.fecha) as total\n    from gestion.caso a\n        inner join gestion.historico d on d.id_caso = a.id  \n\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)  and \n\t  \ta.id_categoria in (3) /*and d.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham, fechao\n        order by fechao"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DETALLADO POR LAS CATEGORIAS DEL METRO ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA (LINEA DEL METRO DE CARACAS)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "  SELECT m.name as categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.historico d on d.id_caso = a.id  \n\t\t\t    inner JOIN gestion.category m ON m.id = a.id_extra_categoria   \n            where a.id_categoria in (3) \n            and d.id_estatus in (1,2,3,4,6,7,8) \n\t\t\t     -- and d.active = 1\n\t\t\t   GROUP BY categoria ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (ESTACIONES DEL METRO DE CARACAS)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": " SELECT m.name || ' (' || e.name || ')' as categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n                inner join gestion.historico d on d.id_caso = a.id  \r\n\t\t\t\tinner JOIN gestion.category e ON e.id = a.id_extra_categoria\r\n\t\t\t    inner JOIN gestion.category m ON m.id = a.id_adicional_categoria\r\n            where a.id_categoria in (3) \r\n            and d.id_estatus in (1,2,3,4,6,7,8) \r\n\t\t\t      --and d.active = 1\r\n\t\t\t   GROUP BY categoria ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (5TO NIVEL DEL METRO DE CARACAS)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": " SELECT m.name  as categoria, COUNT(a.id) as total \r\n\t         FROM gestion.caso a \r\n                inner join gestion.historico d on d.id_caso = a.id  \r\n\t\t\t\tinner JOIN gestion.category m ON m.id = a.id_adicional_categoria\r\n            where a.id_categoria in (3) \r\n            and d.id_estatus in (1,2,3,4,6,7,8) \r\n\t\t\t     -- and d.active = 1\r\n\t\t\t   GROUP BY categoria ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE METRO DE CARACAS DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": " SELECT i.nombre as estatus, count(a.id) as subtotal,\n            (SELECT count(a.id) FROM gestion.caso a\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n    \t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n    \t\t\t\t\tinner JOIN  gestion.estatus i ON h.id = i.id\n    \t\t\t \t\twhere /*h.active = 1 and */h.id_estatus in (1,2,3,4,6,7,8) and a.id_categoria in (3) and e.ubch = 1)::Text \"Total\"\n      FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join  gestion.historico h ON h.id_caso = a.id\n            inner JOIN  gestion.estatus i ON h.id = i.id\n\twhere /*h.active = 1 and */h.id_estatus in (1,2,3,4,6,7,8) and a.id_categoria = 3 and e.ubch = 1 group by estatus"
      }
     ]
    },
    {
     "title": "REVISIÓN-UBCH",
     "type": "gauge",
     "description": "Total de casos generados",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n\t\t\t\t\tinner JOIN  gestion.estatus i ON h.id = i.id\n\t\t\t \t\twhere /*h.active = 1 and*/ h.id_estatus in (1,2) \n\t\t\t\t\tand a.id_categoria in (3) and e.ubch = 1"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n        SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n\t\t\t\t\tinner JOIN  gestion.estatus i ON h.id_estatus = i.id\n\t\t\t \t\twhere /*h.active = 1 and*/ h.id_estatus in (3,4,7,8) \n\t\t\t\t\tand a.id_categoria in (3) and e.ubch = 1"
      }
     ]
    },
    {
     "title": "ATENDIDOS-UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n\t\t\t\t\tinner JOIN  gestion.estatus i ON h.id_estatus = i.id\n\t\t\t \t\twhere /*h.active = 1 and*/ h.id_estatus in (6) \n\t\t\t\t\tand a.id_categoria in (3) and e.ubch = 1"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "        SELECT m.name as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.historico d on d.id_caso = a.id  \n                inner join gestion.denunciante e on e.id = a.id_denunciante\n               \tinner JOIN gestion.category m ON m.id = a.id_sub_categoria               \n            where d.id_estatus in (1,2,3,4,6,7,8) /*and d.active = 1 */and a.id_categoria in (3) and e.ubch = 1\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS ATENDIDOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
     "targets": [
      {
       "rawSql": "     SELECT m.name as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.historico d on d.id_caso = a.id  \n                inner join gestion.denunciante e on e.id = a.id_denunciante\n               \tinner JOIN gestion.category m ON m.id = a.id_sub_categoria               \n            where d.id_estatus in (6) /*and d.active = 1*/ and a.id_categoria in (3) and e.ubch = 1\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS UBCH RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\nselect  to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'YYYY-mm-dd') as fechao,\n\tcount(a.fecha) as total\n    from gestion.caso a\n        inner join gestion.historico d on d.id_caso = a.id  \n\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)  and \n\t  \ta.id_categoria in (3) /*and d.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8) and e.ubch = 1\n        group by fecham, fechao\n        order by fechao"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE METRO DE CARACAS DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \r\n      --a.codigo::Text \"CODIGO CASO\",\r\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n            case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n\t\t\tto_char(a.fecha, 'dd-mm-YY')::Text \"FECHA CREACION\",\r\n\t\t\tto_char(h.fecha_registro, 'dd-mm-YY')::Text \"FECHA INCIDENCIA\",\r\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\"\r\n            --case when v.name is null then 'Analizando' else (v.name || ' ' || v.last_name ) end::Text \"RESPONSABLE\",\r\n\t\t\t--v.phone::Text \"TELF. RESP\"\r\n            FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\tinner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.historico h ON h.id_caso = a.id\r\n            inner JOIN gestion.estatus i ON h.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = a.id --and j.id_user is not null\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n           --LEFT JOIN  public.user w ON w.id = j.id_user\r\n            --LEFT JOIN  public.user_detail v ON w.id = v.user_id\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\r\n            where h.id_estatus in (1,2,3,4,6,7,8) --and h.active = 1 \r\n            and a.id_categoria in (3) and e.ubch = 1"
      }
     ]
    }
   ]
  }
 ]
}