{
 "title": "Cartelera Min Agua V3",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hidro",
    "label": "Hidro",
    "query": "SELECT  nombre FROM gestion.resolutorio a where   id_padre  = 478"
   }
  ]
 },
 "panels": [
  {
   "title": "$hidro",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE AGUA",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select count(a.id) as TOTAL\n        from gestion.caso a\n          inner join gestion.historico d on d.id_caso = a.id  \n\t\t\t\t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\tinner join gestion.resolutorio b on b.id = c.id_resolutorio\n       where --a.id_sub_categoria in (1) and \n\t\t\t\td.id_estatus in (1,2,3,4,6,7,8) --and d.active = 1\n\t\t\t\tand b.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (AGUA)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "       select count(*) as TOTAL\n                from gestion.caso a\n                inner join gestion.historico c on c.id_caso = a.id  \n\t\t\t\tinner join gestion.responsable d on d.id_caso = a.id\n\t\t\t\tinner join gestion.resolutorio b on b.id = d.id_resolutorio\n            where a.id_sub_categoria in (1) and \n                c.id_estatus in (1,2,3,4,6,7,8)\n\t\t\t\t        and a.id_extra_categoria is not null\n\t\t\t\t        and b.nombre in ($hidro)\n                --and c.active = 1"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (AGUA)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "        select count(*) as TOTAL\n      \tfrom gestion.caso a\n          inner join gestion.historico d on d.id_caso = a.id \n\t\t  inner join gestion.responsable b on b.id_caso = a.id\n\t\t  inner join gestion.resolutorio c on c.id = b.id_resolutorio\n      where a.id_sub_categoria in (1) and \n            d.id_estatus in (1,2,3,4,6,7,8) /*and d.active = 1*/ and a.id_extra_categoria is null\n\t        and c.nombre in ($hidro)\n                    "
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  AGUA)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "  SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.historico d on d.id_caso = a.id  \n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\t\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria   \n            where c.id in (1) and \n\t\t\t   d.id_estatus in (1,2,3,4,6,7,8) \n\t\t\t   --and d.active = 1\n\t\t\t   and e.nombre in ($hidro)\n            GROUP BY sub_categoria order by total desc"
      }
     ]
    },
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT --DISTINCT ON (a.codigo) a.codigo::Text \"CODIGO CASO\", \r\n    a.nombre::Text \"CODIGO CASO\", \r\n\t  e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\r\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.direccion::TEXT \"DIRECCION\", a.descripcion::TEXT \"DESCRIP\", \r\n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \r\n      case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\r\n\t\t\ti.nombre::Text \"ESTATUS\",\r\n\t\t\tto_char(a.fecha, 'dd-mm-YY  hh:mm:ss')::Text \"FECHA\",\r\n\t\t\tto_char(h.fecha_registro,'dd-mm-YY hh:mm:ss') as \"FECHA ESTATUS\",\r\n      case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\r\n      --case when v.name is null then 'Analizando' else (v.name || ' ' || v.last_name ) end::Text \"RESPONSABLE\",\r\n\t --\tv.phone::Text \"TELF. RESP\",\r\n\t\t\tCASE WHEN h.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 'VERIFICADO' ELSE 'NO VERIFICADO' END AS \"VERIFICACION\",\r\n\t\t\tcase when a.feedback >= 1 and a.feedback < 1.5 then 'MUY POCO SATISFACHO'\r\n                  when a.feedback >= 1.5 and a.feedback < 2.5 then 'INSATISFECHO'\r\n                  when a.feedback >= 2.5 and a.feedback < 3.5 then 'SATISFECHO'\r\n                  when a.feedback > 3.5 then 'MUY SATISFECHO'\r\n                  when a.feedback is null then 'SIN VALORACIÓN'\r\n                  end as \"VALORACION\"\r\n\t\t\t\r\n\t\t\t--CONCAT(case when round(avg(a.feedback)) = 1 then 'MUY POCO SATISFACHO'\r\n                 -- when round(avg(a.feedback)) = 2 then 'INSATISFECHO'\r\n                  --when round(avg(a.feedback)) = 3 then 'SATISFECHO'\r\n                 -- when round(avg(a.feedback)) > 3 then 'MUY SATISFECHO'\r\n                  --when round(avg(a.feedback)) is null then 'SIN VALORACIÓN'\r\n                 -- end) as \"PROMEDIO\"\r\n\t\t  --a.feedback is\t(CASE WHEN a.feedback >= 3.5 THEN 1) AS \"MUY SATISFECHO\",\r\n\t\t\t--(CASE WHEN a.feedback < 3.5 and a.feedback >= 2.5 THEN 1 ELSE 0 END) AS \"SATISFECHO\",\r\n     -- (CASE WHEN a.feedback < 2.5 and a.feedback >= 1.5 THEN 1 ELSE 0 END) AS \"INSATISFECHO\",\r\n\t\t--\t(CASE WHEN a.feedback < 1.5 THEN 1 ELSE 0 END) AS \"MUY POCO SATISFACHO\"\r\n\t\t\t--a.feedback as \"Valoracion\"\r\n\t\t\t\r\n      FROM gestion.caso a\r\n            inner join gestion.estado b on b.id = a.id_estado\r\n            inner join gestion.municipio c on c.id = a.id_municipio\r\n            inner join gestion.parroquia d on d.id = a.id_parroquia\r\n            inner join gestion.denunciante e on e.id = a.id_denunciante\r\n\t\t\t-- inner join lista.ubch z on z.cedula = e.cedula usuario ubch\r\n            inner join gestion.category f on f.id = a.id_categoria\r\n            inner join gestion.category g on g.id = a.id_sub_categoria\r\n            inner JOIN gestion.historico h ON h.id_caso = a.id\r\n            inner JOIN gestion.estatus i ON h.id_estatus = i.id            \r\n            LEFT JOIN  gestion.responsable j ON j.id_caso = h.id_caso --a.id and j.id_user is not null\r\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \r\n            LEFT JOIN  public.user w ON w.id = j.id_user\r\n            --LEFT JOIN  public.user_detail v ON w.id = v.user_id\r\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\r\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\r\n            where h.id_estatus in (3,4,6,7,8) \r\n\t\t\t--and h.active = 1 \r\n\t\t\tand a.id_sub_categoria in (1)\r\n\t\t\tand k.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and a.id_origen = 1\n    and d.id_estatus in (1,2,3,4,5,6,7,8) \n    --and a.id_estado in (22)"
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and a.id_origen = 1\n    and d.id_estatus in (5) \n    --and a.id_estado in (22)"
      }
     ]
    },
    {
     "title": "CASOS RECIBIDO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\nSELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and a.id_origen = 2\n    and d.id_estatus in (1,2,3,4,6,7,8) \n    and a.id_estado in (1)"
      }
     ]
    },
    {
     "title": "DEVUELTO A PATRIA",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
     "targets": [
      {
       "rawSql": "     SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and a.id_origen = 2\n    and d.id_estatus in (9) \n    and a.id_estado in (1)\n            "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and \td.active = 1\n  and d.id_estatus in (3,4,5,6,7,8)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and d.active = 1\n  and d.id_estatus in (3,4,6,7,8)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and\td.active = 1\n  and d.id_estatus in (3,4,7,8)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "RESUELTOS",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n  SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and\td.active = 1\n  and d.id_estatus in (6)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n\t\t\t\t\t\t\t\t\t\t\tFROM gestion.caso a\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\t\t\t\t\t\t\t\t\tinner join gestion.historico d on d.id_caso = a.id  \n\t\t\t\t\t\t\t\t\t\t  \tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\t\t\t\t\t\t\t\t\t\t\twhere a.id_sub_categoria in (1) /*and d.active = 1 */and d.id_estatus in (3,4,6,7,8)\n\t\t\t\t\t\t\t\t\t \t\tand e.nombre in ($hidro))::decimal, 2) as porcentaje\n\t\tFROM gestion.caso a\n\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\tinner join gestion.historico d on d.id_caso = a.id  \n\t\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\t\twhere a.id_sub_categoria in (1)\n\t\tand e.nombre in ($hidro)\n\t\t--and d.active = 1 \n\t\tand d.id_estatus in (6);"
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "--Total de Casos por Fecha\nselect to_char(a.fecha, 'dd-mm-YY') as fecham, count(a.fecha) as total\n    \tfrom gestion.caso a\n        inner join gestion.historico d on d.id_caso = a.id \n    \t\tinner join gestion.responsable b on b.id_caso = a.id\n    \t \tinner join gestion.resolutorio c on c.id = b.id_resolutorio\n\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)\n\t\t/*and d.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8)\n\t\tand c.nombre in ($hidro)\n        group by fecham \n        order by fecham"
      }
     ]
    },
    {
     "title": "SERVICIOS PRIORIZADOS",
     "type": "barchart",
     "description": "Total de Casos por Sub-Categoría",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "           SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.historico d on d.id_caso = a.id  \n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria \n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\t\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n            where c.id in (1)\n               and d.id_estatus in (1,2,3,4,6,7,8) --and d.active = 1 \n\t\t\t   and e.nombre in ($hidro)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "SERVICIOS PRIORIZADOS",
     "type": "barchart",
     "description": "Total de Casos por Sub-Categoría",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "        SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.historico d on d.id_caso = a.id  \n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria \n\t\t\t\tinner join gestion.responsable b on b.id_caso = a.id\n\t\t\t\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n            where c.id in (1)\n               and d.id_estatus in (6) --and d.active = 1 \n\t\t\t   and e.nombre in ($hidro)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select \tc.nombre as municipio, count(a.id) as total\n    from gestion.caso a\n\t   inner join gestion.estado b on b.id = a.id_estado\n     inner join gestion.municipio c on c.id = a.id_municipio\n   \t inner join gestion.historico d on d.id_caso = a.id  \n\t   inner join gestion.responsable e on e.id_caso = a.id\n\t   inner join gestion.resolutorio f on f.id = e.id_resolutorio\n\t where  a.id_sub_categoria in (1) /*and d.active = 1*/ and d.id_estatus in (3,4,6,7,8) \n\t and f.nombre in ($hidro)\n    group by municipio\n    order by total desc  Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS RESUELTOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select \n\tc.nombre as municipio, count(a.id) as total\n    from \n\tgestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   inner join gestion.municipio c on c.id = a.id_municipio\n   inner join gestion.historico d on d.id_caso = a.id  \n\t inner join gestion.responsable e on e.id_caso = a.id\n\t inner join gestion.resolutorio f on f.id = e.id_resolutorio\n\t where  a.id_sub_categoria in (1) /*and d.active = 1 */and d.id_estatus in (6) \n\t and f.nombre in ($hidro)\n    group by municipio\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "TOTAL DE CASOS EN EL SISTEMA- $hidro",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and \n\t--d.active = 1\n  and d.id_estatus in (3,4,6,7,8)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "TOTAL DE CASOS RESUELTOS DE $hidro",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and d.active = 1\n  and d.id_estatus in (6)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "CASOS - $hidro ",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    select \n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n\t\t\tinner join gestion.resolutorio f on f.id = e.id_resolutorio\n       where a.id_sub_categoria in (1) /*and\n\t   \td.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8)\n        and f.nombre in ($hidro)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS RESUELTO - $hidro ",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   select \n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n\t\t\tinner join gestion.resolutorio f on f.id = e.id_resolutorio\n       where a.id_sub_categoria in (1)/* and\n\t   \td.active = 1 */and d.id_estatus in (6)\n        and f.nombre in ($hidro)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "TOTAL CASOS -  $hidro  ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "       SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and d.active = 1\n  and d.id_estatus in (3,4,6,7,8)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS -  $hidro  ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "       SELECT count(a.id)\n\tFROM gestion.caso a\n\tinner join gestion.historico d on d.id_caso = a.id \n\tinner join gestion.responsable b on b.id_caso = a.id\n\tinner join gestion.resolutorio e on e.id = b.id_resolutorio\n\twhere  \n\ta.id_sub_categoria in (1) --and\td.active = 1\n  and d.id_estatus in (6)\n\tand e.nombre in ($hidro)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n\t\t\tinner join gestion.resolutorio f on f.id = e.id_resolutorio\n     \twhere a.id_sub_categoria in (1) /*and \n\t \t\td.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8)  \n\t\t\tand f.nombre in ($hidro)\n       \t\tgroup by c.nombre, b.nombre order by TOTAL desc;"
      }
     ]
    },
    {
     "title": "TOTAL CASOS RESUELTOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n\t\t\tinner join gestion.resolutorio f on f.id = e.id_resolutorio\n     \twhere a.id_sub_categoria in (1) /*and \n\t \t\td.active = 1*/ and d.id_estatus in (6)  \n\t\t\tand f.nombre in ($hidro)\n       \t\tgroup by c.nombre, b.nombre order by TOTAL desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE-DETALLADO-POR-ESTADOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESTADOS ($hidro)",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select b.nombre::Text \"ESTADOS\",\nsum(CASE WHEN d.id_estatus in (3,4,6,8) THEN 1 ELSE 0 END) AS \"RECIBIDO\",\nsum(CASE WHEN d.id_estatus in (3) THEN 1 ELSE 0 END) AS \"ASIGNADO\",\nsum(CASE WHEN d.id_estatus in (4,8) THEN 1 ELSE 0 END) AS \"EN PROCESO\",\nsum(CASE WHEN d.id_estatus in (6) AND ((a.feedback < 2 and a.verificado is null) or (a.feedback is null and a.verificado is null)) THEN 1 ELSE 0 END) AS \"POR CONFIRMAR\",\nsum(CASE WHEN d.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 1 ELSE 0 END) AS \"ATENDIDO\", --, count(a.id) as \"TOTAL\"\ntrunc(sum(CASE WHEN d.id_estatus in (6)  and  e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) AND (a.feedback >= 2 or a.verificado = 'SI')\nTHEN 1 ELSE 0 END)::decimal*100/count(*)::decimal,2) AS \"% EFECTIVIDAD %\"\nfrom gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.category c on c.id = a.id_sub_categoria\ninner join gestion.responsable e on e.id_caso =  d.id_caso\ninner join gestion.resolutorio z on z.id =  e.id_resolutorio\ninner join gestion.estado b on b.id = a.id_estado\nwhere  /*d.active = 1 and*/ d.id_estatus in (3,4,6,8)\n--and z.id_tipo_resolutorio in (3) \nand b.id < 25 and  e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\nand e.principal is true and z.nombre in ($hidro)\ngroup by b.nombre\nHAVING count(*) > 1\norder by \"% EFECTIVIDAD %\" desc"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE AGUA EN LA BASE DE DATOS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT a.nombre::Text \"CODIGO CASO\", \n\t     e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n\t\t\t e.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.direccion::TEXT \"DIRECCION\", a.descripcion::TEXT \"DESCRIP\", \n\t\t\t f.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n       case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\n\t\t\t i.nombre::Text \"ESTATUS\",\n\t\t\t to_char(a.fecha, 'dd-mm-YY  hh:mm:ss')::Text \"FECHA\",\n\t\t\t to_char(h.fecha_registro,'dd-mm-YY hh:mm:ss') as \"FECHA ESTATUS\",\n       case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\",\n      -- case when v.name is null then 'Analizando' else (v.name || ' ' || v.last_name ) end::Text \"RESPONSABLE\",\n\t\t\t-- v.phone::Text \"TELF. RESP\",\n\t\t\t CASE WHEN h.id_estatus in (6) AND (a.feedback >= 2 or a.verificado = 'SI') THEN 'VERIFICADO' ELSE 'NO VERIFICADO' END AS \"VERIFICACION\",\n\t\t\t  case when a.feedback >= 1 and a.feedback < 1.5 then 'MUY POCO SATISFACHO'\n                  when a.feedback >= 1.5 and a.feedback < 2.5 then 'INSATISFECHO'\n                  when a.feedback >= 2.5 and a.feedback < 3.5 then 'SATISFECHO'\n                  when a.feedback > 3.5 then 'MUY SATISFECHO'\n                  when a.feedback is null then 'SIN VALORACIÓN'\n                  end as \"VALORACION\"\nFROM gestion.caso a\ninner join gestion.estado b on b.id = a.id_estado\ninner join gestion.municipio c on c.id = a.id_municipio\ninner join gestion.parroquia d on d.id = a.id_parroquia\ninner join gestion.denunciante e on e.id = a.id_denunciante\ninner join gestion.category f on f.id = a.id_categoria\ninner join gestion.category g on g.id = a.id_sub_categoria\ninner JOIN gestion.historico h ON h.id_caso = a.id\ninner JOIN gestion.estatus i ON h.id_estatus = i.id            \nLEFT JOIN  gestion.responsable j ON j.id_caso = h.id_caso \nLEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \nLEFT JOIN  public.user w ON w.id = j.id_user\n--LEFT JOIN  public.user_detail v ON w.id = v.user_id\nLEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\nLEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\nwhere h.id_estatus in (3,4,7,8) \n--and h.active = 1 \nand j.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\nand j.principal is true"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE LOS CASOS DE AGUA ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS RECIBIDOS VENAPP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    --and d.id_estatus in (1,2,3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "DEVUELTO A VENAPP",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (5) "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDO POR PATRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (15) "
      }
     ]
    },
    {
     "title": "DEVUELTO A PATRIA",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "targets": [
      {
       "rawSql": "      SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (21) "
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "CASOS RECIBIDOS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (1,2,3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "CASOS EN EL SISTEMA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8) "
      }
     ]
    },
    {
     "title": "EN PROCESO",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8) "
      }
     ]
    },
    {
     "title": "ATENDIDOS CON BAJA VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
      }
     ]
    },
    {
     "title": "ATENDIDOS CON VALORACION",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
      }
     ]
    },
    {
     "title": "PORCENTAJE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id \n                                            inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                            where b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n                                            and b.principal is true\n                                            --and d.active = 1\n                                            and d.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI') "
      }
     ]
    },
    {
     "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
     "type": "barchart",
     "description": "Total de Casos por Fecha",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'mm-dd') as fechaa, count(a.fecha) as total\nfrom gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso = d.id_caso--a.id\ninner join gestion.resolutorio c on c.id = b.id_resolutorio\nwhere a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)\nand b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n--and d.active = 1 \nand d.id_estatus in (1,2,3,4,6,7,8)\nand b.principal is true\ngroup by fecham, fechaa\norder by fechaa"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\nselect \n\tb.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   \tinner join gestion.historico c on c.id_caso = a.id  \n\t inner join gestion.responsable d on d.id_caso = c.id_caso --a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595) \n\t /*and c.active = 1*/ and c.id_estatus in (3,4,6,7,8)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    },
    {
     "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDOS",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "-- Total de Casos por Estado\nselect \n\tb.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   \tinner join gestion.historico c on c.id_caso = a.id  \n\t inner join gestion.responsable d on d.id_caso = c.id_caso --a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t --and c.active = 1 \n\t and c.id_estatus in (6)\n    group by estado\n    order by total desc\n    Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CATEGORÍAS AGUA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE AGUA",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select count(a.id) as TOTAL\n\tfrom gestion.caso a\n\t  inner join gestion.historico b on b.id_caso = a.id  \n\t  inner join gestion.responsable c on c.id_caso = b.id_caso --a.id\n\t  where  a.id_sub_categoria in (1) \n\t        and b.id_estatus in (3,4,6,7,8) --and b.active = 1\n\t\t      and c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "CASOS CATEGORIZADOS (AGUA)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 9, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "       \n         select count(*) as TOTAL\n                from gestion.caso a\n                inner join gestion.historico c on c.id_caso = a.id  \n\t\t\t\tinner join gestion.responsable d on d.id_caso = c.id_caso --a.id\n            where a.id_sub_categoria in (1) and \n                c.id_estatus in (3,4,6,7,8)\n\t\t\t\t        and a.id_extra_categoria is not null\n\t\t\t\t        and d.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n                --and c.active = 1"
      }
     ]
    },
    {
     "title": "POR CATEGORIZAR (AGUA)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select count(*) as TOTAL\n      from gestion.caso a\n          inner join gestion.historico d on d.id_caso = a.id \n\t\t\t\t\tinner join gestion.responsable b on b.id_caso = d.id_caso --a.id\n      where a.id_sub_categoria in (1) and \n            d.id_estatus in (1,2,3,4,6,7,8) /*and d.active = 1*/ and a.id_extra_categoria is null\n\t\t\t\t    and b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "CASOS EN SISTEMA (CATEGORÍAS  AGUA)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "  SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.historico d on d.id_caso = a.id  \n\t\t\t\t        inner join gestion.responsable b on b.id_caso = d.id_caso --a.id\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria   \n            where c.id in (1) and \n\t\t\t   d.id_estatus in (1,2,3,4,6,7,8) \n\t\t\t   --and d.active = 1\n\t\t\t   and b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL CASO DE AGUA DE UBCH EN EL SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS EN SISTEMA-UBCH",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "  SELECT i.nombre as estatus, count(a.id) as subtotal,\n            (SELECT count(a.id) FROM gestion.caso a\n    \t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n    \t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n    \t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n    \t\t\t\t\tinner JOIN  gestion.estatus i ON h.id_estatus = i.id\n    \t\t\t \t\tinner join gestion.responsable c on c.id_caso = h.id_caso --a.id\n    \t\t\t\t\twhere /*h.active = 1 and*/ h.id_estatus in (3,4,6,7,8) and a.id_sub_categoria in (1)\n    \t\t\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598))::Text \"Total\"\n      FROM gestion.caso a\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n            inner join  gestion.historico h ON h.id_caso = a.id\n            inner JOIN  gestion.estatus i ON h.id_estatus = i.id\n\t\t\t      inner join gestion.responsable c on c.id_caso =  h.id_caso --a.id\n         where /*h.active = 1 and*/ h.id_estatus in (3,4,6,7,8) and a.id_sub_categoria in (1)\n\t\t and c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595)\n         group by estatus"
      }
     ]
    },
    {
     "title": "PROCESO-UBCH",
     "type": "gauge",
     "description": "Total de casos Asignados",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
     "targets": [
      {
       "rawSql": "-- Casos Recibidos\n        SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n\t\t\t\t\tinner JOIN  gestion.estatus i ON h.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = h.id_caso --a.id\n\t\t\t\t\twhere /*h.active = 1 and*/ h.id_estatus in (3,4,7,8) and a.id_sub_categoria in (1)\n\t\t\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "ATENDIDOS-UBCH",
     "type": "gauge",
     "description": "Total de casos cerrados",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT count(a.id) FROM gestion.caso a\n\t\t\t\t\tinner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t\t\tinner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t\tinner join  gestion.historico h ON h.id_caso = a.id\n\t\t\t\t\tinner JOIN  gestion.estatus i ON h.id_estatus = i.id\n\t\t\t \t\tinner join gestion.responsable c on c.id_caso = a.id\n\t\t\t\t\twhere /*h.active = 1 and*/ h.id_estatus in (6) and a.id_sub_categoria in (1)\n\t\t\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "HORA VENEZUELA",
     "type": "grafana-clock-panel",
     "description": "FECHA HORA",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
     "targets": [
      {
       "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
      }
     ]
    },
    {
     "title": "UBCH-CASOS EN SISTEMA-SERVICIOS  ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": " SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.historico d on d.id_caso = a.id  \n                inner join gestion.denunciante e on e.id = a.id_denunciante\n                inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\tinner join gestion.responsable b on b.id_caso = d.id_caso --a.id\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n            where a.id_sub_categoria in (1) and d.id_estatus in (1,2,3,4,6,7,8) --and d.active = 1\n\t\t\tand b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-CASOS ATENDIDOS- SERVICIOS ",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 11 },
     "targets": [
      {
       "rawSql": "     SELECT case when m.name is null then c.name else m.name end as sub_categoria, COUNT(a.id) as total \n\t         FROM gestion.caso a \n                inner join gestion.category c on c.id = a.id_sub_categoria\n                inner join gestion.historico d on d.id_caso = a.id  \n                inner join gestion.denunciante e on e.id = a.id_denunciante\n                inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t\t        inner join gestion.responsable b on b.id_caso = d.id_caso --a.id\n                LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria               \n            where d.id_estatus in (6) --and d.active = 1\n\t\t\tand b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n            GROUP BY sub_categoria\n            ORDER BY total desc;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES CON MAS CASOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.historico d on d.id_caso = a.id  \n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t      inner join gestion.responsable c on c.id_caso = d.id_caso --a.id\n\t where /* d.active = 1 and*/ d.id_estatus in (1,2,3,4,6,7,8) and a.id_sub_categoria in (1)\n\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n            group by estado order by total desc Limit 10;"
      }
     ]
    },
    {
     "title": "UBCH-ENTIDADES FEDERALES-CASOS ATENDIDOS  ",
     "type": "barchart",
     "description": "Total de Casos por Estado",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select b.nombre as estado, count(a.id) as total\n  from gestion.caso a\n\t          inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.historico d on d.id_caso = a.id  \n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\t      inner join gestion.responsable c on c.id_caso = a.id\n\t where  /*d.active = 1 and */ d.id_estatus in (6) and a.id_sub_categoria in (1)\n\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n            group by estado order by total desc Limit 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "LISTADO DE CASOS  DE AGUA DE LA BASE DE DATOS (UBCH)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "LISTADO DE CASOS  DE LA BASE DE DATOS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "    SELECT DISTINCT ON (a.nombre) a.nombre::Text \"CODIGO CASO\", \n      --a.codigo::Text \"CODIGO CASO\",\n      e.cedula::Text \"CEDULA\", e.nombre::TEXT \"DENUNCIANTE\",\n\t\t\te.telefono::Text \"TELEFONO\", b.nombre::Text \"ESTADO\", c.nombre::Text \"MUNICIPIO\", d.nombre::Text \"PARROQ\", a.direccion::Text \"DIRECCION\", a.descripcion::TEXT \"DESCRIP\", \n\t\t\tf.name::Text \"CATEGORIA\", g.name::Text \"SUBCATEG\",case when m.name is null then 'Sin ExtCateg' else m.name end::Text \"EXTCATEG\", \n            case when n.name is null then 'Sin Categ Adi' else n.name end::Text \"CATEG ADI\",\n\t\t\ti.nombre::Text \"ESTATUS\",\n            case when k.nombre is null then 'Analizando' else k.nombre end::Text \"INSTITUCION\"--,\n      --      case when v.name is null then 'Analizando' else (v.name || ' ' || v.last_name ) end::Text \"RESPONSABLE\",\n\t\t\t--v.phone::Text \"TELF. RESP\"\n            FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.parroquia d on d.id = a.id_parroquia\n            inner join gestion.denunciante e on e.id = a.id_denunciante\n\t\t\t      inner join lista.ubch z on z.cedula = e.cedula -- usuario ubch\n            inner join gestion.category f on f.id = a.id_categoria\n            inner join gestion.category g on g.id = a.id_sub_categoria\n            inner JOIN gestion.historico h ON h.id_caso = a.id\n            inner JOIN gestion.estatus i ON h.id_estatus = i.id            \n            LEFT JOIN  gestion.responsable j ON j.id_caso = h.id_caso --a.id and j.id_user is not null\n            LEFT JOIN  gestion.resolutorio k ON k.id = j.id_resolutorio \n            LEFT JOIN  public.user w ON w.id = j.id_user\n           -- LEFT JOIN  public.user_detail v ON w.id = v.user_id\n            LEFT JOIN  gestion.category m ON m.id = a.id_extra_categoria\n            LEFT JOIN  gestion.category n ON n.id = a.id_adicional_categoria\n            where h.id_estatus in (3,4,6,7,8) /*and h.active = 1*/ and a.id_sub_categoria in (1)\n            and j.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598);"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE GENERAL DE AGUA POR ENTIDADES FEDERALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CASOS  EN PROCESO  DE AGUA ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.historico d on d.id_caso = a.id  \n    inner join gestion.responsable b on b.id_caso = d.id_caso --a.id\n    inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t  --c.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (3,4,7,8) "
      }
     ]
    },
    {
     "title": "CASOS  ATENDIDOS  DE AGUA ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.historico d on d.id_caso = a.id  \n    inner join gestion.responsable b on b.id_caso = d.id_caso --a.id\n    inner join gestion.resolutorio c on c.id = b.id_resolutorio\n    where b.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n\t  --c.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (6) "
      }
     ]
    },
    {
     "title": "CASOS EN PROCESO POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select \n\tb.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   inner join gestion.historico c on c.id_caso = a.id  \n\t inner join gestion.responsable d on d.id_caso = c.id_caso --a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595) \n\t /*and c.active = 1*/ and c.id_estatus in (3,4,7,8)\n    group by estado\n    order by total desc;"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS POR ENT. FEDERALES",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "        select \n\tb.nombre as estado, count(a.id) as total\n    from gestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   inner join gestion.historico c on c.id_caso = a.id  \n\t inner join gestion.responsable d on d.id_caso = c.id_caso --a.id\n\t inner join gestion.resolutorio e on e.id = d.id_resolutorio\n\t where  d.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595) \n\t /*and c.active = 1*/ and c.id_estatus in (6)\n    group by estado\n    order by total desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE AGUA DE UBCH RECIBIDOS-ATENDIDOS (POR ENTIDADES  FEDERALES) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE AGUA DE UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " select \n            b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.historico d on d.id_caso = a.id  \n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\tinner join gestion.responsable c on c.id_caso = d.id_caso --a.id\n       \twhere a.id_sub_categoria in (1) /*and d.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8)\n\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n        group by b.nombre order by TOTAL desc"
      }
     ]
    },
    {
     "title": "TOTAL CASOS DE AGUA ATENDIDOS DE  UBCH - ENT. FEDERALES (SERVICIOS PRIORIZADOS) ",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "         select \n            b.nombre::Text \"ESTADO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.historico d on d.id_caso = a.id  \n            inner join gestion.denunciante e on e.id = a.id_denunciante\n            inner join lista.ubch z on z.cedula = e.cedula\n\t\t\tinner join gestion.responsable c on c.id_caso = d.id_caso --a.id\n       \twhere a.id_sub_categoria in (1) /*and d.active = 1*/ and d.id_estatus in (6)\n\t\t\tand c.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n        group by b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE AGUA RECIBIDO-ATENDIDO POR MUNICIPIOS(CAPITALES DE ENTIDADES FEDERALES )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS DE AGUA POR MUN. CAPITALES",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n    where --a.id_sub_categoria in (1)and\n    /*d.active = 1\n    and*/ d.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\tand e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS  - AGUA (MUN. CAPITALES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso  --a.id\n    where --a.id_sub_categoria in (1) and \n    /*d.active = 1\n    and*/ d.id_estatus in (6) \n    and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\tand e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "CASOS DE AGUA POR MUN. CAPITALES",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select \n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n       where --a.id_sub_categoria in (1) and\n       /*d.active = 1 and*/ d.id_estatus in (1,2,3,4,6,7,8)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t   and e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS  - AGUA (MUN. CAPITALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "        select \n           (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n       where --a.id_sub_categoria in (1) and \n       /*d.active = 1 and*/ d.id_estatus in (6)\n       and c.id in (22,21,142,148,167,172,190,195,236,265,269,315,327,31,43,67,94,113,121,122,335, 214,250,296)\n\t   and e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n        group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE AGUA RECIBIDO-ATENDIDOS DE OTROS MUNICIPIOS  (CIUDADES IMPORTANTES)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS -  AGUA  (CIUDADES IMPORTANTES)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id\n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n    where --a.id_sub_categoria in (1) and\n    /*d.active = 1\n    and*/ d.id_estatus in (1,2,3,4,6,7,8) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\tand e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)"
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS - AGUA  (CD. IMPORTANTE)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      SELECT count(a.id)\n\t  FROM gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id\n\t\t\tinner join gestion.responsable e on e.id_caso = a.id\n    where a.id_sub_categoria in (1)\n    --and d.active = 1\n    and d.id_estatus in (6) \n    and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\tand e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595)"
      }
     ]
    },
    {
     "title": "CASOS - AGUA (CIUDADES IMPORTANTES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "      select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n     where --a.id_sub_categoria in (1) and \n        /*d.active = 1 and*/ d.id_estatus in (1,2,3,4,6,7,8)\n        and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t      and e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n       group by c.nombre, b.nombre order by TOTAL desc"
      }
     ]
    },
    {
     "title": "CASOS ATENDIDOS - AGUA (CD. IMPORTANTE)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"MUNICIPIO\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.municipio c on c.id = a.id_municipio\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\t      inner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n     where --a.id_sub_categoria in (1) and \n     /*d.active = 1 and*/ d.id_estatus in (6)\n     and c.id in (127,184,24,32,255,51,182,149,204,20,239,212,290,166) \n\t   and e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n       group by c.nombre, b.nombre\n        order by TOTAL desc"
      }
     ]
    }
   ]
  },
  {
   "title": "REPORTE DE CASOS DE AGUA RECIBIDOS-ATENDIDOS  POR ENTIDADES PARROQUIALES (50 PRIMERAS PARROQUIAS) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL CASOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "     select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n     where --a.id_sub_categoria in (1) and \n        /*d.active = 1 and*/ d.id_estatus in (3,4,6,7,8)\n\t  \t\tand e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n       group by c.nombre, b.nombre\n        order by TOTAL desc limit 50\n    "
      }
     ]
    },
    {
     "title": "TOTAL CASOS ATENDIDOS (ENTIDADES PARROQUIALES)",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 11, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "    select (c.nombre || ' (' || b.nombre || ')')::Text \"PARROQUIAS\", \n            count(a.id) as TOTAL\n            from gestion.caso a\n            inner join gestion.estado b on b.id = a.id_estado\n            inner join gestion.parroquia c on c.id = a.id_parroquia\n            inner join gestion.historico d on d.id_caso = a.id  \n\t\t\tinner join gestion.responsable e on e.id_caso = d.id_caso --a.id\n     where --a.id_sub_categoria in (1) and \n       /* d.active = 1 and*/ d.id_estatus in (6)\n\t  \t\tand e.id_resolutorio in (478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598)\n       group by c.nombre, b.nombre\n        order by TOTAL desc limit 50"
      }
     ]
    }
   ]
  }
 ]
}