{
 "title": "MONITOREO CASO SEDE V3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "dia",
    "query": "SELECT to_char(CAST(now()::timestamp AS DATE), 'dd-MM-YYYY')"
   }
  ]
 },
 "panels": [
  {
   "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "--Total de Casos por Fecha\nselect  to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'YYYY-mm-dd') as fechao,\n\tcount(a.fecha) as total\n    from gestion.caso a\n        inner join gestion.historico d on d.id_caso = a.id  \n\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL)  \n\tand a.id_sub_categoria in (10,12,13, 5,6,7,8,9,11,16,17)--(1,2,3,4,5,7,8,9) \n\t--and d.active = 1\n\tand d.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham, fechao\n        order by fechao"
    }
   ]
  },
  {
   "title": "HISTÓRICO DE CASOS RECIBIDOS POR HORA PARA EL DIA $dia DE VENAPP ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "--Total de Casos por Fecha\nselect  to_char(a.fecha, 'HH24') as fecham, to_char(a.fecha, 'YYYY-mm-dd') as fechao,\tcount(a.fecha) as total\n    from gestion.caso a\n        inner join gestion.historico d on d.id_caso = a.id  \n\twhere  to_char(a.fecha, 'YYYY-mm-dd') = to_char(CAST(now()::timestamp AS DATE), 'YYYY-mm-dd') --CAST(now()::timestamp AS DATE) - CAST('1 days' AS INTERVAL)  \n\tand a.id_sub_categoria in (10,12,13, 5,6,7,8,9,11,16,17)--(1,2,3,4,5,7,8,9) \n\t--and d.active = 1\n\tand d.id_estatus in (1,2,3,4,6,7,8)\n        group by fecham, fechao\n        order by fechao\n        limit 24;"
    }
   ]
  },
  {
   "title": "USUARIOS CONECTADOS PCP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \ninner join public.user_rol ur  on us.id= ur.id_usuario\ninner join public.rol r on r.id = ur.id_role;\n\n/*SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \n\t\t--INNER join public.session s on s.user_id::integer = us.id\n\t\t--INNERINNER join public.auth_assignment c on c.user_id::integer = us.id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial');*/\n\t\t"
    }
   ]
  },
  {
   "title": "USUARIOS CONECTADOS RESOLUTORES",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \ninner join public.user_rol ur  on us.id= ur.id_usuario\ninner join public.rol r on r.id = ur.id_role;\n\n/*SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \n\t\tINNER join public.session s on s.user_id::integer = us.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = us.id\n\t\twhere c.item_name in ('resolutor-nacional', 'resolutor');*/\n\t\t"
    }
   ]
  },
  {
   "title": "TOTAL USUARIOS CONECTADOS ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \ninner join public.user_rol ur  on us.id= ur.id_usuario\ninner join public.rol r on r.id = ur.id_role;\n\n/*SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \n\t\tINNER join public.session s on s.user_id::integer = us.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = us.id\n\t\twhere c.item_name in ('resolutor-nacional', 'resolutor', 'operador','operador-nacional','coordinador','supervisor-especial');*/\n\t\t"
    }
   ]
  },
  {
   "title": "TOTAL DE SESIONES  USUARIOS PCP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(distinct us.id) AS \"TOTAL\" \n\t\tFROM public.user us \ninner join public.user_rol ur  on us.id= ur.id_usuario\ninner join public.rol r on r.id = ur.id_role;\n\n/*SELECT count(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial');*/"
    }
   ]
  },
  {
   "title": "TOTAL DE SESIONES  USUARIOS RESOLUTORES",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(*) AS \"TOTAL\" \n\t\tFROM public.user us \ninner join public.user_rol ur  on us.id= ur.id_usuario\ninner join public.rol r on r.id = ur.id_role;\n\n/*SELECT count(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('resolutor-nacional', 'resolutor');*/"
    }
   ]
  },
  {
   "title": "TOTAL DE SESIONES  USUARIOS ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(*) AS \"TOTAL\" \n\t\tFROM public.user us \ninner join public.user_rol ur  on us.id= ur.id_usuario\ninner join public.rol r on r.id = ur.id_role;\n\n/*SELECT count(*) AS \"TOTAL\"\n\t\tFROM public.session us\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\n\t\tinner join public.user u on us.user_id::integer = u.id\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\n\t\twhere c.item_name in ('operador','operador-nacional','coordinador','supervisor-especial','resolutor-nacional', 'resolutor');*/"
    }
   ]
  },
  {
   "title": "DETALLE USUARIO ACTIVO EN EL SISTEMA 1X10",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "CANTIDAD DE USUARIOS CONECTADOS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "\r\n SELECT \r\n ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\",\r\n  UPPER(us.username)::Text \"USUARIO\",\r\n    UPPER(us.first_name  || ' ' || us.last_name)::TEXT \"NOMBRE Y APELLIDO\",\r\n\t  UPPER(r.nombre)::TEXT \"ROL\",\r\n    UPPER(res.nombre)::TEXT \"RESOLUTOR\", count(*) as \"TOTAL SESIONES\"\r\nFROM public.user us \r\ninner join public.user_rol ur  on us.id= ur.id_usuario\r\ninner join public.rol r on r.id = ur.id_role\r\nLEFT join gestion.resolutorio res on res.id  = us.id_resolutorio\r\n\tGROUP BY us.username, r.nombre, \"NOMBRE Y APELLIDO\", res.nombre\r\n\t   HAVING (COUNT(*) > 0) \r\n\t   order by count(*) desc;\r\n\r\n/*SELECT ROW_NUMBER () OVER (ORDER BY count(*) desc) as \"NUM\", \r\n    UPPER(u.username)::Text \"USUARIO\",\r\n    UPPER(usd.name || ' ' || usd.last_name)::TEXT \"NOMBRE Y APELLIDO\",\r\n\t  UPPER(c.item_name)::TEXT \"ROL\",\r\n    UPPER(res.nombre)::TEXT \"RESOLUTOR\", count(*) as \"TOTAL SESIONES\"\r\n\t\tFROM public.session us\r\n\t\tinner join public.user_detail usd on us.user_id::integer = usd.user_id\r\n\t\tinner join public.user u on u.id = usd.user_id\r\n\t\tLEFT join gestion.resolutorio res on res.id = usd.id_resolutorio\r\n\t\tINNER join public.auth_assignment c on c.user_id::integer = usd.user_id\r\n\t\twhere --res.nombre is not null\r\n\t\tc.item_name in ('operador','operador-nacional','coordinador','coordinador-especial','supervisor-especial', 'resolutor','resolutor-nacional')\r\n\t\tGROUP BY us.user_id, c.item_name, \"USUARIO\", \"NOMBRE Y APELLIDO\", u.username, res.nombre\r\n\t   HAVING (COUNT(*) > 0) \r\n\t   order by count(*) desc*/"
    }
   ]
  },
  {
   "title": "CANTIDAD DE CASOS RECIBIDOS POR SUB-CATEGORIA. $dia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "HISTÓRICO DE CASOS RECIBIDO POR HORA PARA EL DIA $dia DE VENAPP POR CATEGORIA",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "--Total de Casos por Fecha\n  select  sc.name::text \"SUB-CATEGORIA\", count(*) as total\n  from gestion.caso a\n  inner join gestion.historico d on d.id_caso = a.id  \n  inner join gestion.category sc on sc.id = a.id_sub_categoria\n\twhere  to_char(a.fecha, 'YYYY-mm-dd') = to_char(CAST(now()::timestamp AS DATE), 'YYYY-mm-dd')   \n\t/*and d.active = 1*/ and d.id_estatus in (1,2,3,4,6,7,8)\n\tand a.id_sub_categoria in (SELECT  c.id FROM gestion.category c\n                 inner join gestion.category cc on cc.id = c.parent where cc.parent is null and c.id <= 17\n                 order by c.id asc) \n        group by sc.name\n        order by count(*) desc\n        limit 24;"
    }
   ]
  }
 ]
}