{
 "title": "Cartelera VicePresidencia de los Servicios V3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "REPORTE GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SERVICIO-TELECOMUNICACIONES",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (9)\n    --and d.active = 1\n    and d.id_estatus in (1,2,3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "SERVICIO-AGUA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "   SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (10)\n    --and d.active = 1\n    and d.id_estatus in (1,2,3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "SERVICIO-ELECTRICIDAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (8)\n    --and d.active = 1\n    and d.id_estatus in (1,2,3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "SERVICIO-GAS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\tFROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (5,6,11)--(4)\n    --and d.active = 1\n    and d.id_estatus in (1,2,3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "VENEZUELA",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "-- Casos Cerrados\n select \n          ec.tx_nom_edo_caso::Text estatus,\n          d.tx_nom_sub_categoria::Text servicio,\n          count(c.id_caso)::Text subtotal,\n          (select count(*) from caso where id_edo_caso in (7))::Text Total\n        from \n            caso c \n            inner join edo_caso ec on c.id_edo_caso = ec.id_edo_caso \n            inner join public.caso_sub_categoria d on d.id_caso_sub_categoria = c.id_caso_subcateg\n        where \n            ec.id_edo_caso in (7)\n            GROUP BY ec.tx_nom_edo_caso, servicio;\n            "
    }
   ]
  },
  {
   "title": "CASOS-REVISIÓN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\n\t  FROM gestion.caso a\n    inner join gestion.category c on c.id = a.id_sub_categoria\n    inner join gestion.historico d on d.id_caso = a.id  \n    where a.id_sub_categoria in (10,8,5,6,11, 9) --(1,3,4,7)\n    --and d.active = 1\n    and d.id_estatus in (1,2) "
    }
   ]
  },
  {
   "title": "CASOS EN PROCESO",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,597,563,566,599,503) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
    }
   ]
  },
  {
   "title": "BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,597,563,566,599,503) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,597,563,566,599,503) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "PORCENTAJE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id \n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso \n                                           where b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,597,563,566,599,503)\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8) )::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,597,563,566,599,503) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TOTAL CASOS-SERVICIOS ",
   "type": "stat",
   "gridPos": { "h": 20, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso \nwhere b.id_resolutorio in (SELECT a.id  FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598,354,597,563,566,599,503) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8) \n"
    }
   ]
  },
  {
   "title": "MINAGUAS-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id \ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10,8,9,6,11))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8) "
    }
   ]
  },
  {
   "title": "MINAGUA-PROCESO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
    }
   ]
  },
  {
   "title": "BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "MINAGUA %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Porcentaje de Eficiencia Casos Cerrados\nSELECT trunc(count(a.id)::decimal * 100 / (-- Casos Recibidos\n                                            SELECT count(a.id)\n                                            FROM gestion.caso a\n                                            inner join gestion.historico d on d.id_caso = a.id \n                                            inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                            where b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \n                                            and b.principal is true\n                                            --and d.active = 1\n                                            and d.id_estatus in (3,4,6,7,8) )::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.responsable b on b.id_caso = a.id\ninner join gestion.historico d on d.id_caso = a.id  \nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where   id_categoria  in (10))--(478,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,598) \nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6) \nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ELECTRICIDAD-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (8))--(354)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "ELECTRICIDAD-PROCESO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (8))--(354)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
    }
   ]
  },
  {
   "title": "BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (8))--(354)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (8))--(354)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ELECTRICIDAD %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           where b.id_resolutorio in (SELECT a.id  FROM gestion.resolutorio a where  id_categoria  in (8))--(354)\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (8))--(354)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOMUNICACIONES-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (9))--(597,563,566)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "TELECOMUNICACIONES-PROCESO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (9))--(597,563,566)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
    }
   ]
  },
  {
   "title": "BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (9)) --(597,563,566)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (9)) --(597,563,566)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "TELECOMUNICACIONES %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           where b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (9)) --(597,563,566)\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (9)) --(597,563,566)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GAS COMUNAL-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (5))--(599)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "GAS COMUNAL-PROCESO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in ((SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (5)))--(599)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
    }
   ]
  },
  {
   "title": "BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (5))--(599)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (5))--(599)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GAS %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           where b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (5))--(599)\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (5))--(599)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GAS-PDVSA-CASOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (6))--(503)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,6,7,8)"
    }
   ]
  },
  {
   "title": "GAS-PROCESO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id  FROM gestion.resolutorio a where  id_categoria  in (6))--(503)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (3,4,7,8)"
    }
   ]
  },
  {
   "title": "BAJA VALORACION",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (6))--(503)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand a.verificado is null \nand (a.feedback < 3 or a.feedback is null)"
    }
   ]
  },
  {
   "title": "ATENDIDO -VALOR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(a.id)\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (6))--(503)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "GAS %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT trunc(count(a.id)::Decimal * 100 / (SELECT count(a.id)\n                                           FROM gestion.caso a\n                                           inner join gestion.historico d on d.id_caso = a.id\n                                           inner join gestion.responsable b on b.id_caso =  d.id_caso\n                                           where b.id_resolutorio in (SELECT a.id  FROM gestion.resolutorio a where  id_categoria  in (6))--(503)\n                                           and b.principal is true\n                                           --and d.active = 1\n                                           and d.id_estatus in (3,4,6,7,8))::Decimal, 2) as porcentaje\nFROM gestion.caso a\ninner join gestion.historico d on d.id_caso = a.id\ninner join gestion.responsable b on b.id_caso =  d.id_caso\nwhere b.id_resolutorio in (SELECT a.id FROM gestion.resolutorio a where  id_categoria  in (6))--(503)\nand b.principal is true\n--and d.active = 1\nand d.id_estatus in (6)\nand (a.feedback >= 3   or  a.verificado = 'SI')"
    }
   ]
  },
  {
   "title": "ESTADOS CON MAYOR NUMERO DE CASOS EN EL SISTEMA ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- Total de Casos por Estado\n select \n\tb.nombre as estado, count(a.id) as total\n    from \n\tgestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   inner join gestion.historico d on d.id_caso = a.id  \n\t where  a.id_sub_categoria in (1,8,5,6,11,9) --(1,3,4,7) --and d.active = 1 \n\t and d.id_estatus in (1,2,3,4,6,7,8)\n    group by estado\n    order by total desc\n    Limit 10;"
    }
   ]
  },
  {
   "title": "ESTADOS CON MAYOR NUMERO DE CASOS ATENDIDO",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- Total de Casos por Estado\n select \n\tb.nombre as estado, count(a.id) as total\n    from \n\tgestion.caso a\n\t inner join gestion.estado b on b.id = a.id_estado\n   inner join gestion.historico d on d.id_caso = a.id  \n\t where  a.id_sub_categoria in (10,8,5,6,11,9)--(1,3,4,7) --and d.active = 1 \n\t and d.id_estatus in (6)\n    group by estado\n    order by total desc\n    Limit 10;"
    }
   ]
  },
  {
   "title": "HISTÓRICO DE CASOS RECIBIDO EN EL SISTEMA DESDE LA VENAPP (ÚLTIMOS DÍAS)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "--Total de Casos por Fecha\nselect to_char(a.fecha, 'dd-mm-YYYY') as fecham, to_char(a.fecha, 'YYYY-mm-dd') as fechao, count(a.fecha) as total\n\t\tfrom gestion.caso a\n\t\t\tinner join gestion.historico d on d.id_caso = a.id  \n\t\twhere  a.fecha > CAST(now()::timestamp AS DATE) - CAST('15 days' AS INTERVAL) and \n\t\ta.id_sub_categoria in (10,8,5,6,11,9)--(1,3,4,7) and d.active = 1 \n\t\tand d.id_estatus in (1,2,3,4,6,7,8)\n\t\t\tgroup by fecham, fechao\n\t\t\torder by fechao"
    }
   ]
  }
 ]
}